-- =====================================================================
-- FINLAB — Content v5: interactive practice for every lesson.
-- Run AFTER migration 0008. Safe to re-run (upserts by lesson + slug).
-- =====================================================================

insert into public.lesson_activities (lesson_id, slug, position, kind, title, instructions, content)
select l.id, v.slug, v.pos, v.kind, v.title, v.instructions, v.content::jsonb
from (values
-- ── The Three Financial Statements ─────────────────────────────────
('three-statements', 'which-statement', 1, 'matching', 'Which statement does it live on?',
 'Drag each item to the statement where it appears (or tap an item, then a category).',
 $j${"categories":[{"id":"is","label":"Income statement"},{"id":"bs","label":"Balance sheet"},{"id":"cfs","label":"Cash flow statement"}],
     "items":[{"id":"i1","label":"Revenue"},{"id":"i2","label":"Accounts receivable"},{"id":"i3","label":"Depreciation expense"},
              {"id":"i4","label":"Retained earnings"},{"id":"i5","label":"Capital expenditure"},{"id":"i6","label":"Dividends paid"},
              {"id":"i7","label":"Inventory"},{"id":"i8","label":"Interest expense"},{"id":"i9","label":"Repayment of debt"}]}$j$),
('three-statements', 'income-statement-errors', 2, 'spot_error', 'Spot the errors: Luzon Roastery P&L',
 'Two lines contain calculation mistakes. Select the rows that are wrong, then check.',
 $j${"context":"Tax rate is 25%. All figures in ₱ millions.","columns":["Line item","FY2025"],"select_count":2,
     "rows":[{"id":"r1","cells":["Revenue","1,000"]},{"id":"r2","cells":["Cost of goods sold","(600)"]},{"id":"r3","cells":["Gross profit","400"]},
             {"id":"r4","cells":["Operating expenses","(250)"]},{"id":"r5","cells":["EBIT","200"]},{"id":"r6","cells":["Interest expense","(30)"]},
             {"id":"r7","cells":["Pre-tax income","120"]},{"id":"r8","cells":["Tax (25%)","(30)"]},{"id":"r9","cells":["Net income","100"]}]}$j$),
-- ── Building the Cash Flow Statement ───────────────────────────────
('cash-flow-statement', 'cash-flow-sections', 1, 'matching', 'Sort the cash flows',
 'Place each item in the section of the cash flow statement where it belongs.',
 $j${"categories":[{"id":"op","label":"Operating"},{"id":"inv","label":"Investing"},{"id":"fin","label":"Financing"}],
     "items":[{"id":"i1","label":"Net income"},{"id":"i2","label":"Depreciation add-back"},{"id":"i3","label":"Increase in receivables"},
              {"id":"i4","label":"Purchase of equipment"},{"id":"i5","label":"Sale of a subsidiary"},{"id":"i6","label":"Proceeds from a bond issue"},
              {"id":"i7","label":"Dividends paid"},{"id":"i8","label":"Share buyback"},{"id":"i9","label":"Increase in accounts payable"}]}$j$),
('cash-flow-statement', 'build-cfo-fcf', 2, 'worked_example', 'Worked example: from net income to free cash flow',
 'Solve each step in order. Hints are available but cost points.',
 $j${"intro":"Visayas Bakeries FY2025 (₱m): net income 180, D&A 40, receivables up 25, inventory up 15, payables up 10, capex 70.",
     "steps":[{"id":"s1","prompt":"Net income plus non-cash D&A (₱m)?","unit":"₱m"},
              {"id":"s2","prompt":"Net working-capital effect on cash (₱m, negative if it uses cash)?","unit":"₱m"},
              {"id":"s3","prompt":"Cash flow from operations (₱m)?","unit":"₱m"},
              {"id":"s4","prompt":"Free cash flow after capex (₱m)?","unit":"₱m"}]}$j$),
-- ── Ratio Analysis Toolkit ─────────────────────────────────────────
('ratio-analysis', 'ratio-lab', 1, 'calculator', 'Ratio lab',
 'Move the inputs and watch margins, returns and liquidity react. Try the prompts below.',
 $j${"calculator":"ratios","defaults":{"revenue":1000,"cogs":650,"opex":200,"interest":20,"taxRate":25,"assets":1200,"equity":600,"currentAssets":450,"inventory":150,"currentLiabilities":300},
     "prompts":["Cut COGS by 50 — how much does ROE rise?","Double equity with the same profit — what happens to ROE and the equity multiplier?","Raise inventory to 300 — the current ratio stays put, but what happens to the quick ratio?"]}$j$),
('ratio-analysis', 'ratio-sheet-errors', 2, 'spot_error', 'Spot the errors: analyst ratio sheet',
 'A junior analyst computed these ratios. Two are wrong — find them.',
 $j${"context":"Revenue 2,000 · Net income 100 · Average equity 500 · Average assets 1,250 · Current assets 600 · Inventory 200 · Current liabilities 400","columns":["Ratio","Value"],"select_count":2,
     "rows":[{"id":"r1","cells":["Net margin","5.0%"]},{"id":"r2","cells":["ROE","20.0%"]},{"id":"r3","cells":["ROA","10.0%"]},
             {"id":"r4","cells":["Current ratio","1.5x"]},{"id":"r5","cells":["Quick ratio","1.5x"]},{"id":"r6","cells":["Asset turnover","1.6x"]}]}$j$),
-- ── Credit Analysis Basics ─────────────────────────────────────────
('credit-analysis', 'covenant-headroom', 1, 'worked_example', 'Worked example: covenant headroom',
 'A lender asks how much room Northwind Retail has under its 3.0x leverage covenant.',
 $j${"intro":"Northwind Retail (₱m): debt 4,200, cash 600, EBITDA 1,500, interest expense 300. Covenant: net debt / EBITDA ≤ 3.0x.",
     "steps":[{"id":"s1","prompt":"Net debt (₱m)?","unit":"₱m"},{"id":"s2","prompt":"Net debt / EBITDA (x)?","unit":"x"},
              {"id":"s3","prompt":"Minimum EBITDA that still complies with 3.0x (₱m)?","unit":"₱m"},
              {"id":"s4","prompt":"How far can EBITDA fall before a breach (%)?","unit":"%"},
              {"id":"s5","prompt":"EBITDA interest coverage (x)?","unit":"x"}]}$j$),
('credit-analysis', 'loan-request', 2, 'branching', 'Case: the loan request',
 'You are the credit officer. Make the calls — each choice has consequences.',
 $j${"start":"n1","nodes":{
   "n1":{"text":"Northwind Retail (net leverage 2.4x, covenant 3.0x, EBITDA ₱1,500m) asks for an extra ₱500m to open 40 stores. What do you do first?",
         "choices":[{"id":"a","label":"Approve immediately — the relationship is valuable","next":"n2a"},{"id":"b","label":"Run a downside case on EBITDA before deciding","next":"n2b"},{"id":"c","label":"Decline outright — retail is risky","next":"end_decline"}]},
   "n2a":{"text":"You approved. Six months later same-store sales fall 15%; EBITDA drops to ₱1,200m and net debt is ₱4,100m (3.4x). The covenant is breached.",
         "choices":[{"id":"a","label":"Quietly waive the covenant and move on","next":"end_bad"},{"id":"b","label":"Negotiate amortization, collateral and tighter reporting","next":"end_mid"}]},
   "n2b":{"text":"Downside case: EBITDA −20% → ₱1,200m. With the new loan net debt would be ₱4,100m → 3.4x, breaching 3.0x. How do you structure it?",
         "choices":[{"id":"a","label":"Approve the full ₱500m with no conditions","next":"end_mid2"},{"id":"b","label":"Approve ₱250m now and ₱250m on hitting store targets, with quarterly reporting and a 3.25x step-down","next":"end_good"},{"id":"c","label":"Decline — the downside breaches the covenant","next":"end_decline2"}]},
   "end_bad":{"end":true,"text":"The borrower defaulted a year later. Waiving without protection left the bank with large losses."},
   "end_mid":{"end":true,"text":"You recovered most of the exposure, but only after a painful restructuring that analysis upfront could have avoided."},
   "end_mid2":{"end":true,"text":"It worked out this time, but you took downside risk you had already identified without being paid for it."},
   "end_good":{"end":true,"text":"Excellent. Staged funding and covenants protected the bank while supporting a good client. The expansion succeeded."},
   "end_decline":{"end":true,"text":"The client moved to a competitor. You turned away a sound relationship without doing the analysis."},
   "end_decline2":{"end":true,"text":"Defensible, but a structured deal would have captured the opportunity with acceptable risk."}}}$j$),
-- ── Valuation with Multiples ───────────────────────────────────────
('valuation-multiples', 'multiples-lab', 1, 'calculator', 'Multiples lab',
 'Set EPS, book value and target multiples to see target prices and the implied rating.',
 $j${"calculator":"multiples","defaults":{"eps":4.2,"pe":12,"bvps":30,"pb":1.6,"price":42},
     "prompts":["What target P/E turns this BUY into a HOLD?","If ROE falls and the P/B target drops to 1.2x, what happens to the blended target?","Find the price at which the stock becomes a SELL."]}$j$),
('valuation-multiples', 'which-multiple', 2, 'matching', 'Which multiple fits best?',
 'Match each company to the multiple an analyst would most likely anchor on.',
 $j${"categories":[{"id":"pe","label":"P/E"},{"id":"pb","label":"P/B"},{"id":"ev","label":"EV/EBITDA"}],
     "items":[{"id":"i1","label":"A commercial bank"},{"id":"i2","label":"An insurance company"},{"id":"i3","label":"A stable consumer-staples company with steady profits"},
              {"id":"i4","label":"A highly leveraged telecom compared with debt-free peers"},{"id":"i5","label":"A capital-intensive port operator with heavy D&A"},
              {"id":"i6","label":"A profitable software firm with steady earnings"},{"id":"i7","label":"A company with a net loss this year but positive EBITDA"}]}$j$),
-- ── Cost of Capital ────────────────────────────────────────────────
('cost-of-capital', 'wacc-lab', 1, 'calculator', 'WACC lab',
 'Adjust CAPM inputs, debt cost and leverage to see WACC move.',
 $j${"calculator":"wacc","defaults":{"rf":6,"beta":1.1,"mrp":6,"kd":7,"tax":25,"debtWeight":30},
     "prompts":["Raise beta from 1.1 to 1.5 — how many basis points does WACC rise?","Increase the debt weight to 50%. Why does WACC fall in this simple model?","What happens if the tax rate drops to 0%?"]}$j$),
('cost-of-capital', 'build-wacc', 2, 'worked_example', 'Worked example: build a WACC',
 'Solve each step; the next one unlocks when you get it right.',
 $j${"intro":"Mindoro Utilities: risk-free 5.5%, beta 1.3, market risk premium 6%, pre-tax cost of debt 8%, tax 25%, equity ₱700m and debt ₱300m (market values).",
     "steps":[{"id":"s1","prompt":"Cost of equity (%)?","unit":"%"},{"id":"s2","prompt":"After-tax cost of debt (%)?","unit":"%"},
              {"id":"s3","prompt":"Equity weight (%)?","unit":"%"},{"id":"s4","prompt":"WACC (%)?","unit":"%"}]}$j$),
-- ── DCF Fundamentals ───────────────────────────────────────────────
('dcf-fundamentals', 'dcf-lab', 1, 'calculator', 'DCF lab',
 'Change growth, margins, WACC and terminal growth and watch value per share and the terminal-value share of EV.',
 $j${"calculator":"dcf","defaults":{"baseRevenue":1000,"years":5,"revenueGrowthPct":8,"ebitMarginPct":18,"taxRatePct":25,"daPctRevenue":4,"capexPctRevenue":5,"nwcPctRevenue":10,"waccPct":10,"terminalGrowthPct":3,"netDebt":300,"sharesOutstanding":100},
     "prompts":["Move WACC from 10% to 9%. By what % does value per share change?","Push terminal growth toward WACC — what happens, and why is it dangerous?","Which input moves value more: +2pp EBIT margin or −1pp WACC?"]}$j$),
('dcf-fundamentals', 'dcf-errors', 2, 'spot_error', 'Spot the errors: a two-year DCF',
 'WACC 10%, terminal growth 3%, net debt ₱300m, 50m shares. Two rows are wrong.',
 $j${"context":"Year-end cash flows. Terminal value is calculated at the end of Year 2.","columns":["Step","Value (₱m)"],"select_count":2,
     "rows":[{"id":"r1","cells":["FCFF Year 1","100.0"]},{"id":"r2","cells":["PV of Year 1 (÷ 1.10)","90.9"]},{"id":"r3","cells":["FCFF Year 2","110.0"]},
             {"id":"r4","cells":["PV of Year 2 (÷ 1.21)","90.9"]},{"id":"r5","cells":["Terminal value = 110 × 1.03 ÷ (10% − 3%)","1,618.6"]},
             {"id":"r6","cells":["PV of terminal value (÷ 1.10)","1,471.5"]},{"id":"r7","cells":["Enterprise value (using the correct PV of TV)","1,519.5"]},
             {"id":"r8","cells":["Net debt","300.0"]},{"id":"r9","cells":["Equity value = EV + net debt","1,819.5"]},{"id":"r10","cells":["Value per share (₱, correct equity ÷ 50m)","24.39"]}]}$j$),
-- ── Anatomy of an Equity Research Report ───────────────────────────
('equity-research-report', 'which-section', 1, 'matching', 'Which section does it belong in?',
 'Each sentence comes from a Jollibee initiation report. Put it in the right section.',
 $j${"categories":[{"id":"thesis","label":"Investment thesis"},{"id":"company","label":"Company overview"},{"id":"industry","label":"Industry overview"},{"id":"competitive","label":"Competitive analysis"},{"id":"financial","label":"Financial analysis"},{"id":"valuation","label":"Valuation"},{"id":"risks","label":"Risks"}],
     "items":[{"id":"i1","label":"BUY, ₱290 target: international store growth is underpriced"},{"id":"i2","label":"Revenue mix is 60% Philippines, 40% international"},
              {"id":"i3","label":"The PH quick-service restaurant market grows about 8% a year"},{"id":"i4","label":"45% market share versus 15% for the nearest rival"},
              {"id":"i5","label":"Gross margin expanded 120bp to 32% over three years"},{"id":"i6","label":"DCF at 9% WACC and 4% terminal growth"},
              {"id":"i7","label":"A commodity price spike could compress margins by 200bp"}]}$j$),
('equity-research-report', 'report-errors', 2, 'spot_error', 'Spot the problems: a draft report summary',
 'Your senior analyst flags two lines that would never pass compliance or a PM review. Find them.',
 $j${"context":"Draft summary box of an initiation report on a PSE-listed bank.","columns":["Field","Draft"],"select_count":2,
     "rows":[{"id":"r1","cells":["Rating","BUY"]},{"id":"r2","cells":["Current price / target","₱128 / ₱131"]},{"id":"r3","cells":["Valuation","Justified P/B 1.55x (ROE 13%, COE 10%, g 4.5%)"]},
             {"id":"r4","cells":["Key catalyst","Q4 results on 15 Feb: NIM expansion"]},{"id":"r5","cells":["Key risk","None — the bank is very safe"]},{"id":"r6","cells":["Sources","FY2025 annual report; BSP banking statistics"]}]}$j$),
-- ── How to Structure a Stock Pitch ─────────────────────────────────
('stock-pitch-structure', 'strong-or-weak', 1, 'matching', 'Strong or weak pitch statement?',
 'Sort each statement. Strong = specific, quantified, testable.',
 $j${"categories":[{"id":"strong","label":"Strong"},{"id":"weak","label":"Weak"}],
     "items":[{"id":"i1","label":"BDO trades at 1.3x book despite a sustainable 13% ROE"},{"id":"i2","label":"Great management team"},
              {"id":"i3","label":"Q4 results on 15 Feb should confirm 150bp of NIM expansion"},{"id":"i4","label":"The stock is cheap"},
              {"id":"i5","label":"If NPLs exceed 3% the thesis breaks — we track monthly BSP data"},{"id":"i6","label":"Everyone loves the brand"},
              {"id":"i7","label":"Target ₱165 (16% upside) from a 1.55x P/B"}]}$j$),
('stock-pitch-structure', 'pitch-the-pm', 2, 'branching', 'Case: pitch the portfolio manager',
 'You have 60 seconds with a PM. Every answer counts.',
 $j${"start":"n1","nodes":{
   "n1":{"text":"PM, glancing at the clock: \"You have 60 seconds. What's the idea?\"",
         "choices":[{"id":"a","label":"Start with the company's history since 1968","next":"n2x"},{"id":"b","label":"\"BUY BDO, 16% upside to ₱165. The market underprices NIM expansion; Q4 results are the catalyst.\"","next":"n2"},{"id":"c","label":"Read the full report summary aloud","next":"n2x"}]},
   "n2x":{"text":"PM: \"Get to the point. What's the call?\"",
         "choices":[{"id":"a","label":"State the rating, target and why","next":"n2"},{"id":"b","label":"Keep going with background","next":"end_lost"}]},
   "n2":{"text":"PM: \"Everyone owns BDO. What's your edge?\"",
         "choices":[{"id":"a","label":"\"It's simply a great bank.\"","next":"n3w"},{"id":"b","label":"\"Consensus models flat NIM, but deposits reprice two quarters after loans, so NIM rises about 20bp.\"","next":"n3"}]},
   "n3w":{"text":"PM: \"That's not an edge. Why would I pay for this?\"",
         "choices":[{"id":"a","label":"Acknowledge it and give the variant view on deposit repricing","next":"n3"},{"id":"b","label":"Repeat that it's a great bank","next":"end_lost"}]},
   "n3":{"text":"PM: \"What makes you wrong?\"",
         "choices":[{"id":"a","label":"\"Nothing — it's a sure thing.\"","next":"end_over"},{"id":"b","label":"\"A BSP cut of 50bp or more, or NPLs above 3%. I track the monthly BSP data.\"","next":"end_good"}]},
   "end_lost":{"end":true,"text":"The PM moved on to the next analyst. Lead with the call."},
   "end_over":{"end":true,"text":"The PM passed: no analyst is ever sure. Risks and monitoring signals build credibility."},
   "end_good":{"end":true,"text":"The PM sized a position and asked for your Q4 preview. That's a successful pitch."}}}$j$),
-- ── Portfolio Construction Basics ──────────────────────────────────
('portfolio-construction', 'portfolio-lab', 1, 'calculator', 'Portfolio lab',
 'Blend equities, bonds and cash. Watch expected return, volatility, Sharpe and concentration.',
 $j${"calculator":"portfolio","defaults":{"wEq":60,"wBd":30,"rEq":10,"rBd":5,"rCash":4,"volEq":18,"volBd":6,"corr":0.2,"rf":4},
     "prompts":["Lower the equity–bond correlation to −0.2. What happens to volatility?","Find a mix with a Sharpe ratio above 0.40.","Go 100% equities — how much extra volatility do you take for the extra return?"]}$j$),
('portfolio-construction', 'rebalance-call', 2, 'branching', 'Case: the rebalancing call',
 'You manage a client portfolio with a 60/40 mandate (equity band 55–65%).',
 $j${"start":"n1","nodes":{
   "n1":{"text":"After a strong rally, equities are now 72% of the portfolio. The client calls, excited: \"Let it ride!\"",
         "choices":[{"id":"a","label":"Do nothing — the client is happy","next":"n2a"},{"id":"b","label":"Rebalance back to 60/40 and explain why","next":"n2b"},{"id":"c","label":"Buy more equities — momentum is strong","next":"n2c"}]},
   "n2a":{"text":"Next quarter the market falls 20%. The portfolio drops more than the client's agreed risk tolerance. The client is upset.",
         "choices":[{"id":"a","label":"Sell everything to stop the pain","next":"end_panic"},{"id":"b","label":"Rebalance now and review the investment policy together","next":"end_late"}]},
   "n2b":{"text":"Client: \"Why are you selling my winners?\"",
         "choices":[{"id":"a","label":"\"Drift pushed your risk above what we agreed; rebalancing restores it and locks in gains.\"","next":"end_good"},{"id":"b","label":"\"Compliance made me do it.\"","next":"end_ok"}]},
   "n2c":{"text":"Equities are now 80%. The market then falls 20%.",
         "choices":[{"id":"a","label":"Rebalance now","next":"end_late"},{"id":"b","label":"Hold and hope","next":"end_bad"}]},
   "end_panic":{"end":true,"text":"Selling at the bottom locked in the loss and the client missed the recovery."},
   "end_late":{"end":true,"text":"Better late than never, but the drawdown exceeded the mandate. Discipline beats reaction."},
   "end_good":{"end":true,"text":"The client understood the risk logic and trusted the process. When the market fell, losses stayed within the mandate."},
   "end_ok":{"end":true,"text":"The right action, but the client didn't learn why. Explaining risk builds trust."},
   "end_bad":{"end":true,"text":"The portfolio fell far beyond the client's risk tolerance. The mandate exists for exactly this moment."}}}$j$),
-- ── M&A: Accretion / Dilution ──────────────────────────────────────
('accretion-dilution', 'accretion-lab', 1, 'calculator', 'Accretion / dilution lab',
 'Change deal terms and see pro forma EPS, accretion and break-even synergies.',
 $j${"calculator":"accretion","defaults":{"acqNi":500,"acqShares":100,"tgtNi":60,"newShares":20,"synergies":10},
     "prompts":["How many new shares can you issue before the deal turns dilutive (no synergies)?","What synergies make this deal break even?","Halve the new shares by paying partly with cash (assume no interest cost). What happens?"]}$j$),
('accretion-dilution', 'deal-steps', 2, 'worked_example', 'Worked example: is the deal accretive?',
 'Work through the merger math one step at a time.',
 $j${"intro":"Archipelago Foods (acquirer): net income ₱800m, 200m shares. Target: net income ₱150m. All-stock deal issuing 50m new shares. After-tax synergies ₱30m.",
     "steps":[{"id":"s1","prompt":"Acquirer standalone EPS (₱)?","unit":"₱"},{"id":"s2","prompt":"Pro forma net income incl. synergies (₱m)?","unit":"₱m"},
              {"id":"s3","prompt":"Pro forma share count (m)?","unit":"m"},{"id":"s4","prompt":"Pro forma EPS (₱)?","unit":"₱"},
              {"id":"s5","prompt":"Accretion / (dilution) (%)? Negative if dilutive.","unit":"%"},{"id":"s6","prompt":"Synergies needed to break even (₱m)?","unit":"₱m"}]}$j$),
-- ── Investment Committee Memo ──────────────────────────────────────
('investment-committee-memo', 'npv-lab', 1, 'calculator', 'NPV / IRR lab',
 'Model a project: cost, annual cash flow, life and hurdle rate. Stress the volumes.',
 $j${"calculator":"npv","defaults":{"cost":500,"cashFlow":90,"years":10,"rate":11,"downside":20},
     "prompts":["At what annual cash flow does NPV hit zero (break-even)?","How does the downside case change your recommendation?","If the hurdle rate rises to 13%, is the project still worth doing?"]}$j$),
('investment-committee-memo', 'defend-at-ic', 2, 'branching', 'Case: defend your project at the IC',
 'You are presenting Cebu Logistics'' ₱500m warehouse expansion to the investment committee.',
 $j${"start":"n1","nodes":{
   "n1":{"text":"You present: NPV ₱30m at an 11% hurdle, IRR 12.4%. The CFO interrupts: \"What if volumes come in 20% lower?\"",
         "choices":[{"id":"a","label":"\"That won't happen — the market is growing.\"","next":"n2bad"},{"id":"b","label":"\"Then NPV is about −₱76m. That's why I propose phasing: build 50% now, the rest when utilization tops 80%.\"","next":"n2good"},{"id":"c","label":"\"I didn't model that.\"","next":"n2bad"}]},
   "n2bad":{"text":"The chair: \"Come back with a downside case.\" The meeting moves on without a decision.",
         "choices":[{"id":"a","label":"Rework the memo with a downside case and a phased option","next":"end_retry"}]},
   "n2good":{"text":"Chair: \"What would make you stop phase 2?\"",
         "choices":[{"id":"a","label":"\"Utilization below 70% for two quarters, or anchor contracts not renewed.\"","next":"end_good"},{"id":"b","label":"\"Nothing — we'll build it regardless.\"","next":"end_mid"}]},
   "end_retry":{"end":true,"text":"Approved a month later, but you lost credibility. Always walk in with the downside case."},
   "end_mid":{"end":true,"text":"Phase 1 was approved, but phase 2 was left to a later vote. Stop conditions show discipline."},
   "end_good":{"end":true,"text":"Approved with conditions. Clear stop-loss triggers turned a risky project into a controlled bet."}}}$j$)
) as v(lesson, slug, pos, kind, title, instructions, content)
join public.lessons l on l.slug = v.lesson
on conflict (lesson_id, slug) do update
  set position = excluded.position, kind = excluded.kind, title = excluded.title,
      instructions = excluded.instructions, content = excluded.content;

-- Calculators are exploration-only (not required for the quiz).
update public.lesson_activities set is_required = false where kind = 'calculator';

-- Answer keys (admin-only).
insert into public.lesson_activity_keys (activity_id, key)
select a.id, v.key::jsonb
from (values
('three-statements', 'which-statement', $j${"i1":"is","i2":"bs","i3":"is","i4":"bs","i5":"cfs","i6":"cfs","i7":"bs","i8":"is","i9":"cfs"}$j$),
('three-statements', 'income-statement-errors', $j${"errors":["r5","r9"],"explanations":{"r5":"EBIT = gross profit 400 − opex 250 = 150, not 200. (Pre-tax income of 120 = 150 − 30 confirms it.)","r9":"Net income = pre-tax 120 − tax 30 = 90, not 100."}}$j$),
('cash-flow-statement', 'cash-flow-sections', $j${"i1":"op","i2":"op","i3":"op","i4":"inv","i5":"inv","i6":"fin","i7":"fin","i8":"fin","i9":"op"}$j$),
('cash-flow-statement', 'build-cfo-fcf', $j${
  "s1":{"answer":220,"tolerance_pct":0.5,"hint":"Start with net income and add back the non-cash expense.","explanation":"180 + 40 = 220."},
  "s2":{"answer":-30,"tolerance_pct":0.5,"hint":"Increases in receivables and inventory use cash; an increase in payables provides cash.","explanation":"−25 − 15 + 10 = −30."},
  "s3":{"answer":190,"tolerance_pct":0.5,"hint":"Combine the first two steps.","explanation":"220 − 30 = 190."},
  "s4":{"answer":120,"tolerance_pct":0.5,"hint":"FCF = CFO − capex.","explanation":"190 − 70 = 120."}}$j$),
('ratio-analysis', 'ratio-sheet-errors', $j${"errors":["r3","r5"],"explanations":{"r3":"ROA = 100 ÷ 1,250 = 8.0%, not 10.0%.","r5":"Quick ratio = (600 − 200) ÷ 400 = 1.0x. 1.5x is the current ratio."}}$j$),
('credit-analysis', 'covenant-headroom', $j${
  "s1":{"answer":3600,"tolerance_pct":0.5,"hint":"Net debt = debt − cash.","explanation":"4,200 − 600 = 3,600."},
  "s2":{"answer":2.4,"tolerance_pct":1,"hint":"Divide net debt by EBITDA.","explanation":"3,600 ÷ 1,500 = 2.4x."},
  "s3":{"answer":1200,"tolerance_pct":0.5,"hint":"At the limit, net debt ÷ EBITDA = 3.0.","explanation":"3,600 ÷ 3.0 = 1,200."},
  "s4":{"answer":20,"tolerance_pct":1,"hint":"Compare the minimum EBITDA with today's EBITDA.","explanation":"1 − 1,200 ÷ 1,500 = 20%."},
  "s5":{"answer":5,"tolerance_pct":1,"hint":"EBITDA ÷ interest expense.","explanation":"1,500 ÷ 300 = 5.0x."}}$j$),
('credit-analysis', 'loan-request', $j${"max":100,
  "points":{"n1.a":0,"n1.b":40,"n1.c":5,"n2a.a":0,"n2a.b":25,"n2b.a":15,"n2b.b":60,"n2b.c":30},
  "feedback":{"n1.a":"Never approve before analysing the downside.","n1.b":"Right instinct: test the covenant under stress first.","n1.c":"Declining without analysis loses good business.",
              "n2a.a":"Waivers without protection reward the wrong behaviour.","n2a.b":"Sensible damage control.",
              "n2b.a":"You identified the risk but didn't price or protect against it.","n2b.b":"Staged funding plus covenants: textbook structuring.","n2b.c":"Safe, but a structure could have worked."}}$j$),
('valuation-multiples', 'which-multiple', $j${"i1":"pb","i2":"pb","i3":"pe","i4":"ev","i5":"ev","i6":"pe","i7":"ev"}$j$),
('cost-of-capital', 'build-wacc', $j${
  "s1":{"answer":13.3,"tolerance_pct":1,"hint":"CAPM: risk-free + beta × market risk premium.","explanation":"5.5% + 1.3 × 6% = 13.3%."},
  "s2":{"answer":6,"tolerance_pct":1,"hint":"Multiply the pre-tax cost by (1 − tax rate).","explanation":"8% × 0.75 = 6.0%."},
  "s3":{"answer":70,"tolerance_pct":0.5,"hint":"Equity ÷ (equity + debt).","explanation":"700 ÷ 1,000 = 70%."},
  "s4":{"answer":11.11,"tolerance_pct":1,"hint":"Weight each cost by its share of capital.","explanation":"0.7 × 13.3% + 0.3 × 6% = 11.11%."}}$j$),
('dcf-fundamentals', 'dcf-errors', $j${"errors":["r6","r9"],"explanations":{"r6":"The terminal value sits at the end of Year 2, so discount it by 1.21: 1,618.6 ÷ 1.21 = 1,337.7.","r9":"Equity value = EV − net debt = 1,519.5 − 300 = 1,219.5. Net debt is subtracted, not added."}}$j$),
('equity-research-report', 'which-section', $j${"i1":"thesis","i2":"company","i3":"industry","i4":"competitive","i5":"financial","i6":"valuation","i7":"risks"}$j$),
('equity-research-report', 'report-errors', $j${"errors":["r2","r5"],"explanations":{"r2":"₱128 → ₱131 is only 2.3% upside: inconsistent with a BUY under a ±10% convention.","r5":"Every report needs real risks and monitoring signals. \"None\" would not pass a PM or compliance review."}}$j$),
('stock-pitch-structure', 'strong-or-weak', $j${"i1":"strong","i2":"weak","i3":"strong","i4":"weak","i5":"strong","i6":"weak","i7":"strong"}$j$),
('stock-pitch-structure', 'pitch-the-pm', $j${"max":100,
  "points":{"n1.a":0,"n1.b":30,"n1.c":0,"n2x.a":10,"n2x.b":0,"n2.a":0,"n2.b":35,"n3w.a":15,"n3w.b":0,"n3.a":0,"n3.b":35},
  "feedback":{"n1.a":"PMs want the call first.","n1.b":"Rating, target, why, catalyst — perfect opening.","n1.c":"Never read slides at a PM.",
              "n2x.a":"Recovered.","n2x.b":"You lost the room.","n2.a":"Not an edge — everyone knows it.","n2.b":"A specific, testable variant perception.",
              "n3w.a":"Good recovery.","n3w.b":"Repeating a weak point loses credibility.","n3.a":"Overconfidence is a red flag.","n3.b":"Clear risks plus a monitoring signal."}}$j$),
('portfolio-construction', 'rebalance-call', $j${"max":100,
  "points":{"n1.a":0,"n1.b":50,"n1.c":0,"n2a.a":0,"n2a.b":20,"n2b.a":50,"n2b.b":20,"n2c.a":15,"n2c.b":0},
  "feedback":{"n1.a":"The mandate band was breached; inaction is a decision.","n1.b":"Disciplined rebalancing keeps risk where the client agreed.","n1.c":"Adds risk the client never agreed to.",
              "n2a.a":"Panic selling locks in losses.","n2a.b":"Late but correct.","n2b.a":"Clear, risk-based explanation.","n2b.b":"Right action, weak explanation.",
              "n2c.a":"Late but correct.","n2c.b":"Hope is not a strategy."}}$j$),
('accretion-dilution', 'deal-steps', $j${
  "s1":{"answer":4,"tolerance_pct":0.5,"hint":"EPS = net income ÷ shares.","explanation":"800 ÷ 200 = ₱4.00."},
  "s2":{"answer":980,"tolerance_pct":0.5,"hint":"Add both net incomes and the synergies.","explanation":"800 + 150 + 30 = 980."},
  "s3":{"answer":250,"tolerance_pct":0.5,"hint":"Existing shares plus new shares.","explanation":"200 + 50 = 250m."},
  "s4":{"answer":3.92,"tolerance_pct":0.5,"hint":"Pro forma net income ÷ pro forma shares.","explanation":"980 ÷ 250 = ₱3.92."},
  "s5":{"answer":-2,"tolerance_pct":2,"hint":"(Pro forma EPS ÷ standalone EPS) − 1.","explanation":"3.92 ÷ 4.00 − 1 = −2.0% (dilutive)."},
  "s6":{"answer":50,"tolerance_pct":1,"hint":"Find the net income that gives ₱4.00 EPS on 250m shares, then compare with combined net income before synergies.","explanation":"4.00 × 250 = 1,000; 1,000 − 950 = ₱50m."}}$j$),
('investment-committee-memo', 'defend-at-ic', $j${"max":100,
  "points":{"n1.a":0,"n1.b":60,"n1.c":0,"n2bad.a":10,"n2good.a":40,"n2good.b":0},
  "feedback":{"n1.a":"Dismissing the downside destroys credibility.","n1.b":"Quantified downside plus a mitigation: exactly what ICs want.","n1.c":"Always model the downside before the meeting.",
              "n2bad.a":"The right fix, done late.","n2good.a":"Specific stop conditions.","n2good.b":"No exit plan signals poor discipline."}}$j$)
) as v(lesson, slug, key)
join public.lessons l on l.slug = v.lesson
join public.lesson_activities a on a.lesson_id = l.id and a.slug = v.slug
on conflict (activity_id) do update set key = excluded.key, updated_at = now();
