-- seed_010_corpfin_modeling: part 1 of 3. Run the parts in order.
-- =====================================================================
-- FINLAB — Content v10: Corporate Finance & FP&A and Financial Modeling
--   7 lessons (video + 10-question check + 2 practice activities + 10 flashcards),
--   5 case challenges, 2 timed final exams, 2 certifications.
-- Run AFTER seed_009. Safe to re-run.
-- =====================================================================

-- ---------------------------------------------------------------------
-- 1. Lessons
-- ---------------------------------------------------------------------
insert into public.lessons (slug, title, summary, category_id, difficulty, estimated_minutes, sort_order, related_challenge_slugs, video_urls, body) values
('time-value-of-money', 'Time Value of Money', 'Present value, future value, annuities, perpetuities and effective rates.', 'valuation', 'beginner', 15, 30,
 '{corpfin-capital-budget}', '{https://www.youtube.com/watch?v=Y815bf-jUQg}', '
## A peso today is worth more than a peso tomorrow
Money you hold now can be invested, and prices rise over time. So cash flows at different dates must be moved to a **common date** before they are compared.

## The core formulas
- **Future value:** FV = PV × (1 + r)ⁿ
- **Present value:** PV = FV ÷ (1 + r)ⁿ
- **Annuity (level payment C for n periods):** PV = C × [1 − (1 + r)⁻ⁿ] ÷ r
- **Perpetuity (level payment forever):** PV = C ÷ r

## Rate conventions
- **Rule of 72:** years to double ≈ 72 ÷ rate (%).
- **Effective annual rate:** EAR = (1 + nominal ÷ m)ᵐ − 1, where m is compounding periods per year. More frequent compounding means a higher EAR.

## Example
₱100,000 at 8% for 3 years: FV = 100,000 × 1.08³ = **₱125,971**. A ₱200,000 payment in 4 years at 10% is worth 200,000 ÷ 1.1⁴ = **₱136,603** today.

> Every valuation in finance — bonds, stocks, projects — is time value of money applied to a stream of cash flows.
'),
('budgeting-variance-fpa', 'Budgeting & Variance Analysis (FP&A)', 'Budgets, favourable vs unfavourable variances, price-volume analysis and rolling forecasts.', 'financial_analysis', 'intermediate', 15, 31,
 '{corpfin-variance-review}', '{https://www.youtube.com/watch?v=cnUyZ2dZSEk}', '
## What FP&A does
Financial planning & analysis sets the **budget**, tracks **actuals** against it, explains the gaps and updates the **forecast**.

## Variances
- **Variance = Actual − Budget**; **variance % = Variance ÷ Budget**.
- **Favourable:** more revenue or profit than planned, or lower costs. **Unfavourable:** the opposite. (A cost *above* budget is unfavourable.)

## Price-volume decomposition
- **Volume variance** = (Actual units − Budget units) × **Budget price**
- **Price variance** = (Actual price − Budget price) × **Actual units**
- The two add up to the total revenue variance.

## Good practice
- Compare like with like: same periods, same chart of accounts.
- Use **materiality thresholds** so effort goes to the big gaps.
- A **flexible budget** restates the budget at the actual activity level.
- A **rolling forecast** is refreshed regularly (for example, always looking 12 months ahead).
- Commentary should state the **cause**, whether it is one-off or recurring, and the action.

> A variance is a question, not an answer: always explain *why*.
'),
('capital-budgeting-npv-irr', 'Capital Budgeting: NPV, IRR & Payback', 'Choosing projects with NPV, IRR, profitability index and payback.', 'valuation', 'intermediate', 15, 32,
 '{corpfin-capital-budget}', '{https://www.youtube.com/watch?v=y3m8FAGt7Qo}', '
## The question
Should we spend cash today for cash flows later? Discount the future cash flows at the **cost of capital** and compare.

## The tools
- **NPV** = Σ CFₜ ÷ (1 + r)ᵗ − Initial investment. **Accept if NPV > 0.**
- **IRR** = the discount rate that makes NPV = 0. Accept if IRR > required return.
- **Profitability index** = PV of inflows ÷ Investment. Accept if PI > 1.
- **Payback** = years to recover the investment. Simple, but ignores the time value of money and cash flows after payback. **Discounted payback** fixes the first flaw.

## Which should I trust?
**NPV** measures the value created in pesos and is the most reliable. IRR can mislead for mutually exclusive projects or unconventional cash flows; when NPV and IRR disagree, **follow NPV**.

## Example
Invest ₱1,000k to receive ₱450k a year for 3 years at 10%: PV of inflows = 450 × 2.4869 = ₱1,119k, so NPV = **+₱119k**.

> A project that earns exactly the cost of capital has an NPV of zero — it creates no value.
'),
('working-capital-ccc', 'Working Capital & the Cash Conversion Cycle', 'DSO, DIO, DPO and how fast a business turns inventory into cash.', 'financial_analysis', 'intermediate', 15, 33,
 '{corpfin-variance-review}', '{https://www.youtube.com/watch?v=JLxy4cs8Kr8}', '
## Cash is tied up in operations
**Net working capital** = Current assets − Current liabilities. The faster a business turns stock and receivables into cash, the less funding it needs.

## The three days measures
- **DSO** = Receivables ÷ Sales × 365 (how long customers take to pay)
- **DIO** = Inventory ÷ COGS × 365 (how long stock sits)
- **DPO** = Payables ÷ COGS × 365 (how long we take to pay suppliers)

> **Cash conversion cycle = DIO + DSO − DPO**

## Levers
- Collect faster: tighter credit, early-payment discounts.
- Hold less stock: better forecasting, just-in-time ordering.
- Pay later: longer supplier terms (without damaging relationships).

A **negative CCC** means customers pay before suppliers must be paid — the business is financed by its suppliers. Fast-growing companies often need more working capital, because growth ties up cash in stock and receivables.

> Cutting DSO by 10 days frees 10 days of sales in cash.
'),
('model-structure', 'Financial Model Structure & the Three-Statement Link', 'Inputs, schedules, statements, checks and the links between them.', 'financial_analysis', 'intermediate', 15, 34,
 '{modeling-three-statement-roll}', '{https://www.youtube.com/watch?v=-pws4pPiDFs}', '
## Structure: inputs → calculations → outputs
- **Inputs:** every assumption in one clearly labelled place (growth, margins, working-capital days, capex, tax). Blue font for hard-coded inputs.
- **Calculations:** supporting schedules (revenue build, PP&E, working capital, debt) and the three statements.
- **Outputs:** valuation, summary charts, scenarios.
- **Never hard-code a number inside a formula.** One formula per row, consistent across columns.

## How the statements link
- **Net income** → flows into **retained earnings** (less dividends).
- **Depreciation & capex** → roll the **PP&E schedule**: closing = opening + capex − depreciation.
- **Working-capital changes** → adjust cash flow from operations.
- **Cash flow statement** ends with closing cash → **balance sheet cash**.

## Roll-forwards
Closing retained earnings = opening + net income − dividends. CFO = net income + D&A − increase in receivables + increase in payables.

## Integrity
- **Balance check:** Assets − (Liabilities + Equity) = 0 in every period.
- A **revolver** borrows automatically if cash would go negative.
- Beware circular references (interest on average balances) — use a switch.

> A model that doesn''t balance is wrong; a model that balances can still be wrong, so test the assumptions too.
'),
('revenue-drivers-forecasting', 'Driver-Based Revenue Forecasting', 'Price × volume, subscriptions, market share and realistic growth.', 'financial_analysis', 'intermediate', 15, 35,
 '{modeling-scenario-valuation}', '{https://www.youtube.com/watch?v=yiWAE7aE6zk}', '
## Forecast drivers, not totals
A growth rate alone hides what must be true. Build revenue from its **drivers** so each assumption can be tested.

## Common builds
- **Price × volume:** units × price per unit. Growth ≈ (1 + volume growth)(1 + price growth) − 1.
- **Subscriptions:** closing customers = opening × (1 − churn) + new customers; revenue = customers × ARPU.
- **Retail:** same-store sales growth + contribution from new stores.
- **Market share:** market size × share.

## CAGR
CAGR = (End ÷ Start)^(1/years) − 1.

## Sanity checks
Compare with **history**, **capacity** and **market size**. A **hockey stick** (sudden acceleration with no new driver) is a red flag, as is share doubling with no new product.

> Use at least two ways to forecast revenue and check they agree.
'),
('scenarios-sensitivity', 'Scenarios & Sensitivity Analysis', 'Base, bull and bear cases, sensitivity tables and probability-weighted value.', 'financial_analysis', 'advanced', 15, 36,
 '{modeling-scenario-valuation}', '{https://www.youtube.com/watch?v=UsbVUOnBy3Y}', '
## Two different tools
- **Sensitivity analysis** changes **one input at a time** (or two, in a data table) to see how much the output moves. A **tornado chart** ranks inputs by impact.
- **Scenario analysis** changes **several linked inputs together** to tell a coherent story: **bull**, **base**, **bear**.

## Building scenarios
Put all scenario drivers on the inputs sheet with a **scenario switch** (1/2/3 using CHOOSE or INDEX) so the whole model flips together. Keep each case internally consistent: growth, margins, working capital and capex should move in the same direction.

## Probability-weighted value
Expected value = Σ (probability × value). Example: 25% × ₱180 + 50% × ₱120 + 25% × ₱60 = **₱120**.

## Stress the right things
A good bear case tests **liquidity and covenants**, not only earnings.

> Sensitivities show which assumption matters; scenarios show what could happen.
')
on conflict (slug) do nothing;

-- ---------------------------------------------------------------------
-- 2. Knowledge checks
-- ---------------------------------------------------------------------
with qs(slug, questions, answers) as (values
('time-value-of-money',
 convert_from(decode('W3siaWQiOiJxMSIsInR5cGUiOiJudW1lcmljIiwibGFiZWwiOiJGdXR1cmUgdmFsdWUiLCJwcm9tcHQiOiLigrExMDAsMDAwIGlzIGludmVzdGVkIGF0IDglIGEgeWVhciBmb3IgMyB5ZWFycy4gRnV0dXJlIHZhbHVlICjigrEpPyIsInVuaXQiOiLigrEiLCJwb2ludHMiOjEwfSwKICAgICB7ImlkIjoicTIiLCJ0eXBlIjoibnVtZXJpYyIsImxhYmVsIjoiUHJlc2VudCB2YWx1ZSIsInByb21wdCI6IuKCsTIwMCwwMDAgd2lsbCBiZSByZWNlaXZlZCBpbiA0IHllYXJzLiBUaGUgZGlzY291bnQgcmF0ZSBpcyAxMCUuIFByZXNlbnQgdmFsdWUgKOKCsSk/IiwidW5pdCI6IuKCsSIsInBvaW50cyI6MTB9LAogICAgIHsiaWQiOiJxMyIsInR5cGUiOiJtY3EiLCJsYWJlbCI6IkRpc2NvdW50IHJhdGUiLCJwcm9tcHQiOiJBIGhpZ2hlciBkaXNjb3VudCByYXRlIG1ha2VzIGEgZnV0dXJlIGNhc2ggZmxvdyB3b3J0aOKApiIsIm9wdGlvbnMiOlt7ImlkIjoiYSIsImxhYmVsIjoiTW9yZSB0b2RheSJ9LHsiaWQiOiJiIiwibGFiZWwiOiJMZXNzIHRvZGF5In0seyJpZCI6ImMiLCJsYWJlbCI6IlRoZSBzYW1lIHRvZGF5In0seyJpZCI6ImQiLCJsYWJlbCI6Ik1vcmUgaW4gdGhlIGZ1dHVyZSJ9XSwicG9pbnRzIjoxMH0sCiAgICAgeyJpZCI6InE0IiwidHlwZSI6Im51bWVyaWMiLCJsYWJlbCI6IkFubnVpdHkiLCJwcm9tcHQiOiLigrExMCwwMDAgaXMgcmVjZWl2ZWQgYXQgdGhlIGVuZCBvZiBlYWNoIG9mIHRoZSBuZXh0IDMgeWVhcnMuIERpc2NvdW50IHJhdGUgMTAlLiBQcmVzZW50IHZhbHVlICjigrEpPyIsInVuaXQiOiLigrEiLCJwb2ludHMiOjEwfSwKICAgICB7ImlkIjoicTUiLCJ0eXBlIjoibnVtZXJpYyIsImxhYmVsIjoiUGVycGV0dWl0eSIsInByb21wdCI6IkEgcGVycGV0dWl0eSBwYXlzIOKCsTUsMDAwIGEgeWVhciBmb3JldmVyLiBUaGUgZGlzY291bnQgcmF0ZSBpcyA4JS4gUHJlc2VudCB2YWx1ZSAo4oKxKT8iLCJ1bml0Ijoi4oKxIiwicG9pbnRzIjoxMH0sCiAgICAgeyJpZCI6InE2IiwidHlwZSI6Im1jcSIsImxhYmVsIjoiVG9kYXkgdnMgbGF0ZXIiLCJwcm9tcHQiOiJBdCBhbnkgcG9zaXRpdmUgaW50ZXJlc3QgcmF0ZSwg4oKxMTAwIHRvZGF5IGlzIHdvcnRo4oCmIiwib3B0aW9ucyI6W3siaWQiOiJhIiwibGFiZWwiOiJMZXNzIHRoYW4g4oKxMTAwIGluIGEgeWVhciJ9LHsiaWQiOiJiIiwibGFiZWwiOiJNb3JlIHRoYW4g4oKxMTAwIGluIGEgeWVhciJ9LHsiaWQiOiJjIiwibGFiZWwiOiJFeGFjdGx5IOKCsTEwMCBpbiBhIHllYXIifSx7ImlkIjoiZCIsImxhYmVsIjoiSXQgZGVwZW5kcyBvbiBpbmZsYXRpb24gb25seSJ9XSwicG9pbnRzIjoxMH0sCiAgICAgeyJpZCI6InE3IiwidHlwZSI6Im51bWVyaWMiLCJsYWJlbCI6IlJ1bGUgb2YgNzIiLCJwcm9tcHQiOiJBdCBhIDklIGFubnVhbCByZXR1cm4sIHJvdWdobHkgaG93IG1hbnkgeWVhcnMgZG9lcyBtb25leSB0YWtlIHRvIGRvdWJsZSAocnVsZSBvZiA3Mik/IiwidW5pdCI6InllYXJzIiwicG9pbnRzIjoxMH0sCiAgICAgeyJpZCI6InE4IiwidHlwZSI6Im1jcSIsImxhYmVsIjoiQ29tcG91bmRpbmciLCJwcm9tcHQiOiJBdCB0aGUgc2FtZSBub21pbmFsIHJhdGUsIG1vcmUgZnJlcXVlbnQgY29tcG91bmRpbmcgZ2l2ZXPigKYiLCJvcHRpb25zIjpbeyJpZCI6ImEiLCJsYWJlbCI6IkEgbG93ZXIgZWZmZWN0aXZlIGFubnVhbCByYXRlIn0seyJpZCI6ImIiLCJsYWJlbCI6IkEgaGlnaGVyIGVmZmVjdGl2ZSBhbm51YWwgcmF0ZSJ9LHsiaWQiOiJjIiwibGFiZWwiOiJUaGUgc2FtZSBlZmZlY3RpdmUgYW5udWFsIHJhdGUifSx7ImlkIjoiZCIsImxhYmVsIjoiQSBuZWdhdGl2ZSByYXRlIn1dLCJwb2ludHMiOjEwfSwKICAgICB7ImlkIjoicTkiLCJ0eXBlIjoibnVtZXJpYyIsImxhYmVsIjoiRWZmZWN0aXZlIHJhdGUiLCJwcm9tcHQiOiJBIDEyJSBub21pbmFsIHJhdGUgaXMgY29tcG91bmRlZCBtb250aGx5LiBFZmZlY3RpdmUgYW5udWFsIHJhdGUgKCUsIHR3byBkZWNpbWFscyk/IiwidW5pdCI6IiUiLCJwb2ludHMiOjEwfSwKICAgICB7ImlkIjoicTEwIiwidHlwZSI6Im1jcSIsImxhYmVsIjoiV2h5IGl0IGV4aXN0cyIsInByb21wdCI6IlRoZSB0aW1lIHZhbHVlIG9mIG1vbmV5IGV4aXN0cyBiZWNhdXNl4oCmIiwib3B0aW9ucyI6W3siaWQiOiJhIiwibGFiZWwiOiJNb25leSB0b2RheSBjYW4gYmUgaW52ZXN0ZWQgdG8gZWFybiBhIHJldHVybiwgYW5kIHByaWNlcyBjaGFuZ2Ugb3ZlciB0aW1lIn0seyJpZCI6ImIiLCJsYWJlbCI6IkJhbmtzIHNldCBhcmJpdHJhcnkgcmF0ZXMifSx7ImlkIjoiYyIsImxhYmVsIjoiRnV0dXJlIGNhc2ggaXMgYWx3YXlzIGNlcnRhaW4ifSx7ImlkIjoiZCIsImxhYmVsIjoiVGF4ZXMgYXBwbHkgb25seSB0byBmdXR1cmUgY2FzaCJ9XSwicG9pbnRzIjoxMH1d', 'base64'), 'UTF8')::jsonb,
 convert_from(decode('eyJxMSI6eyJhbnN3ZXIiOjEyNTk3MSwidG9sZXJhbmNlX3BjdCI6MC41fSwicTIiOnsiYW5zd2VyIjoxMzY2MDMsInRvbGVyYW5jZV9wY3QiOjAuNX0sInEzIjp7ImFuc3dlciI6ImIifSwicTQiOnsiYW5zd2VyIjoyNDg2OSwidG9sZXJhbmNlX3BjdCI6MC41fSwicTUiOnsiYW5zd2VyIjo2MjUwMCwidG9sZXJhbmNlX3BjdCI6MC41fSwicTYiOnsiYW5zd2VyIjoiYiJ9LCJxNyI6eyJhbnN3ZXIiOjgsInRvbGVyYW5jZV9wY3QiOjF9LCJxOCI6eyJhbnN3ZXIiOiJiIn0sInE5Ijp7ImFuc3dlciI6MTIuNjgsInRvbGVyYW5jZV9wY3QiOjAuNX0sInExMCI6eyJhbnN3ZXIiOiJhIn19', 'base64'), 'UTF8')::jsonb),
('budgeting-variance-fpa',
 convert_from(decode('W3siaWQiOiJxMSIsInR5cGUiOiJudW1lcmljIiwibGFiZWwiOiJWYXJpYW5jZSIsInByb21wdCI6IlJldmVudWUgYnVkZ2V0IOKCsTUsMDAwazsgYWN0dWFsIOKCsTUsNDAway4gVmFyaWFuY2UgKOKCsWspPyIsInVuaXQiOiLigrFrIiwicG9pbnRzIjoxMH0sCiAgICAgeyJpZCI6InEyIiwidHlwZSI6Im51bWVyaWMiLCJsYWJlbCI6IlZhcmlhbmNlICUiLCJwcm9tcHQiOiJTYW1lIGZpZ3VyZXM6IHZhcmlhbmNlIGFzIGEgJSBvZiBidWRnZXQ/IiwidW5pdCI6IiUiLCJwb2ludHMiOjEwfSwKICAgICB7ImlkIjoicTMiLCJ0eXBlIjoibWNxIiwibGFiZWwiOiJDb3N0IHZhcmlhbmNlIiwicHJvbXB0IjoiQSBjb3N0IGxpbmUgY29tZXMgaW4gMTIlIGFib3ZlIGJ1ZGdldC4gVGhhdCB2YXJpYW5jZSBpc+KApiIsIm9wdGlvbnMiOlt7ImlkIjoiYSIsImxhYmVsIjoiRmF2b3VyYWJsZSJ9LHsiaWQiOiJiIiwibGFiZWwiOiJVbmZhdm91cmFibGUifSx7ImlkIjoiYyIsImxhYmVsIjoiTmV1dHJhbCJ9LHsiaWQiOiJkIiwibGFiZWwiOiJOb3QgYSB2YXJpYW5jZSJ9XSwicG9pbnRzIjoxMH0sCiAgICAgeyJpZCI6InE0IiwidHlwZSI6Im51bWVyaWMiLCJsYWJlbCI6IlZvbHVtZSB2YXJpYW5jZSIsInByb21wdCI6IkJ1ZGdldDogMTAsMDAwIHVuaXRzIGF0IOKCsTUwLiBBY3R1YWw6IDExLDAwMCB1bml0cyBhdCDigrE0OC4gVm9sdW1lIHZhcmlhbmNlIG9uIHJldmVudWUgKOKCsSk/IiwidW5pdCI6IuKCsSIsInBvaW50cyI6MTB9LAogICAgIHsiaWQiOiJxNSIsInR5cGUiOiJudW1lcmljIiwibGFiZWwiOiJQcmljZSB2YXJpYW5jZSIsInByb21wdCI6IlVzaW5nIHRoZSBzYW1lIGZhY3RzLCBieSBob3cgbXVjaCBkaWQgdGhlIGxvd2VyIHByaWNlIHJlZHVjZSByZXZlbnVlICjigrEsIGFzIGEgcG9zaXRpdmUgbnVtYmVyKT8iLCJ1bml0Ijoi4oKxIiwicG9pbnRzIjoxMH0sCiAgICAgeyJpZCI6InE2IiwidHlwZSI6Im51bWVyaWMiLCJsYWJlbCI6IlRvdGFsIHZhcmlhbmNlIiwicHJvbXB0IjoiVXNpbmcgdGhlIHNhbWUgZmFjdHMsIHRvdGFsIHJldmVudWUgdmFyaWFuY2UgKGFjdHVhbCDiiJIgYnVkZ2V0KSAo4oKxKT8iLCJ1bml0Ijoi4oKxIiwicG9pbnRzIjoxMH0sCiAgICAgeyJpZCI6InE3IiwidHlwZSI6Im1jcSIsImxhYmVsIjoiRmxleGlibGUgYnVkZ2V0IiwicHJvbXB0IjoiQSBmbGV4aWJsZSBidWRnZXTigKYiLCJvcHRpb25zIjpbeyJpZCI6ImEiLCJsYWJlbCI6IklzIG5ldmVyIHJldmlzZWQifSx7ImlkIjoiYiIsImxhYmVsIjoiSXMgcmVzdGF0ZWQgYXQgdGhlIGFjdHVhbCBhY3Rpdml0eSBsZXZlbCJ9LHsiaWQiOiJjIiwibGFiZWwiOiJJZ25vcmVzIHZvbHVtZSJ9LHsiaWQiOiJkIiwibGFiZWwiOiJSZXBsYWNlcyB0aGUgYWN0dWFscyJ9XSwicG9pbnRzIjoxMH0sCiAgICAgeyJpZCI6InE4IiwidHlwZSI6Im1jcSIsImxhYmVsIjoiTWF0ZXJpYWxpdHkiLCJwcm9tcHQiOiJXaHkgc2V0IGEgbWF0ZXJpYWxpdHkgdGhyZXNob2xkIGZvciB2YXJpYW5jZSByZXZpZXc/Iiwib3B0aW9ucyI6W3siaWQiOiJhIiwibGFiZWwiOiJTbyBlZmZvcnQgZ29lcyB0byB0aGUgbGFyZ2UgZ2FwcyJ9LHsiaWQiOiJiIiwibGFiZWwiOiJUbyBoaWRlIHNtYWxsIGVycm9ycyBwZXJtYW5lbnRseSJ9LHsiaWQiOiJjIiwibGFiZWwiOiJCZWNhdXNlIHNtYWxsIHZhcmlhbmNlcyBhcmUgYWx3YXlzIHdyb25nIn0seyJpZCI6ImQiLCJsYWJlbCI6IlRvIGF2b2lkIHdyaXRpbmcgY29tbWVudGFyeSJ9XSwicG9pbnRzIjoxMH0sCiAgICAgeyJpZCI6InE5IiwidHlwZSI6Im1jcSIsImxhYmVsIjoiUm9sbGluZyBmb3JlY2FzdCIsInByb21wdCI6IkEgcm9sbGluZyBmb3JlY2FzdCBpc+KApiIsIm9wdGlvbnMiOlt7ImlkIjoiYSIsImxhYmVsIjoiVXBkYXRlZCByZWd1bGFybHkgYW5kIGFsd2F5cyBsb29rcyBhIGZpeGVkIHBlcmlvZCBhaGVhZCJ9LHsiaWQiOiJiIiwibGFiZWwiOiJQcmVwYXJlZCBvbmNlIGEgeWVhciJ9LHsiaWQiOiJjIiwibGFiZWwiOiJUaGUgc2FtZSBhcyB0aGUgYnVkZ2V0In0seyJpZCI6ImQiLCJsYWJlbCI6IkEgaGlzdG9yaWNhbCByZXBvcnQifV0sInBvaW50cyI6MTB9LAogICAgIHsiaWQiOiJxMTAiLCJ0eXBlIjoibnVtZXJpYyIsImxhYmVsIjoiR3Jvc3MgcHJvZml0IHZhcmlhbmNlIiwicHJvbXB0IjoiQnVkZ2V0OiByZXZlbnVlIOKCsTUsMDAwayBhdCBhIDQwJSBncm9zcyBtYXJnaW4uIEFjdHVhbDogcmV2ZW51ZSDigrE1LDQwMGsgYXQgMzglLiBHcm9zcyBwcm9maXQgdmFyaWFuY2UgKOKCsWspPyIsInVuaXQiOiLigrFrIiwicG9pbnRzIjoxMH1d', 'base64'), 'UTF8')::jsonb,
 convert_from(decode('eyJxMSI6eyJhbnN3ZXIiOjQwMCwidG9sZXJhbmNlX3BjdCI6MC41fSwicTIiOnsiYW5zd2VyIjo4LCJ0b2xlcmFuY2VfcGN0IjowLjV9LCJxMyI6eyJhbnN3ZXIiOiJiIn0sInE0Ijp7ImFuc3dlciI6NTAwMDAsInRvbGVyYW5jZV9wY3QiOjAuNX0sInE1Ijp7ImFuc3dlciI6MjIwMDAsInRvbGVyYW5jZV9wY3QiOjAuNX0sInE2Ijp7ImFuc3dlciI6MjgwMDAsInRvbGVyYW5jZV9wY3QiOjAuNX0sInE3Ijp7ImFuc3dlciI6ImIifSwicTgiOnsiYW5zd2VyIjoiYSJ9LCJxOSI6eyJhbnN3ZXIiOiJhIn0sInExMCI6eyJhbnN3ZXIiOjUyLCJ0b2xlcmFuY2VfcGN0IjowLjV9fQ==', 'base64'), 'UTF8')::jsonb),
('capital-budgeting-npv-irr',
 convert_from(decode('W3siaWQiOiJxMSIsInR5cGUiOiJudW1lcmljIiwibGFiZWwiOiJOUFYiLCJwcm9tcHQiOiJBIHByb2plY3QgY29zdHMg4oKxMSwwMDBrIGFuZCByZXR1cm5zIOKCsTQ1MGsgYSB5ZWFyIGZvciAzIHllYXJzLiBSZXF1aXJlZCByZXR1cm4gMTAlLiBOUFYgKOKCsWssIHR3byBkZWNpbWFscyk/IiwidW5pdCI6IuKCsWsiLCJwb2ludHMiOjEwfSwKICAgICB7ImlkIjoicTIiLCJ0eXBlIjoibWNxIiwibGFiZWwiOiJEZWNpc2lvbiBydWxlIiwicHJvbXB0IjoiQWNjZXB0IGEgY29udmVudGlvbmFsIHByb2plY3Qgd2hlbuKApiIsIm9wdGlvbnMiOlt7ImlkIjoiYSIsImxhYmVsIjoiTlBWIGlzIGdyZWF0ZXIgdGhhbiB6ZXJvIn0seyJpZCI6ImIiLCJsYWJlbCI6Ik5QViBpcyBuZWdhdGl2ZSJ9LHsiaWQiOiJjIiwibGFiZWwiOiJQYXliYWNrIGlzIG1vcmUgdGhhbiAxMCB5ZWFycyJ9LHsiaWQiOiJkIiwibGFiZWwiOiJJUlIgaXMgYmVsb3cgdGhlIGNvc3Qgb2YgY2FwaXRhbCJ9XSwicG9pbnRzIjoxMH0sCiAgICAgeyJpZCI6InEzIiwidHlwZSI6Im51bWVyaWMiLCJsYWJlbCI6IlBheWJhY2siLCJwcm9tcHQiOiJBIHByb2plY3QgY29zdHMg4oKxNjAwayBhbmQgcmV0dXJucyDigrEyMDBrIGEgeWVhci4gUGF5YmFjayBwZXJpb2QgKHllYXJzKT8iLCJ1bml0IjoieWVhcnMiLCJwb2ludHMiOjEwfSwKICAgICB7ImlkIjoicTQiLCJ0eXBlIjoibWNxIiwibGFiZWwiOiJJUlIiLCJwcm9tcHQiOiJUaGUgSVJSIGlz4oCmIiwib3B0aW9ucyI6W3siaWQiOiJhIiwibGFiZWwiOiJUaGUgZGlzY291bnQgcmF0ZSBhdCB3aGljaCBOUFYgZXF1YWxzIHplcm8ifSx7ImlkIjoiYiIsImxhYmVsIjoiVGhlIGF2ZXJhZ2UgYW5udWFsIHByb2ZpdCJ9LHsiaWQiOiJjIiwibGFiZWwiOiJUaGUgY29zdCBvZiBkZWJ0In0seyJpZCI6ImQiLCJsYWJlbCI6IlRoZSBwYXliYWNrIHBlcmlvZCBhcyBhIHBlcmNlbnRhZ2UifV0sInBvaW50cyI6MTB9LAogICAgIHsiaWQiOiJxNSIsInR5cGUiOiJtY3EiLCJsYWJlbCI6IklSUiB2cyBjb3N0IG9mIGNhcGl0YWwiLCJwcm9tcHQiOiJJUlIgaXMgMTQlIGFuZCB0aGUgY29zdCBvZiBjYXBpdGFsIGlzIDExJS4gRm9yIGEgY29udmVudGlvbmFsIHByb2plY3QgeW91IHNob3VsZOKApiIsIm9wdGlvbnMiOlt7ImlkIjoiYSIsImxhYmVsIjoiQWNjZXB0In0seyJpZCI6ImIiLCJsYWJlbCI6IlJlamVjdCJ9LHsiaWQiOiJjIiwibGFiZWwiOiJJZ25vcmUgTlBWIn0seyJpZCI6ImQiLCJsYWJlbCI6IldhaXQgZm9yIHBheWJhY2sifV0sInBvaW50cyI6MTB9LAogICAgIHsiaWQiOiJxNiIsInR5cGUiOiJudW1lcmljIiwibGFiZWwiOiJQcm9maXRhYmlsaXR5IGluZGV4IiwicHJvbXB0IjoiUFYgb2YgaW5mbG93cyDigrExLDMyMGs7IGludmVzdG1lbnQg4oKxMSwxMDBrLiBQcm9maXRhYmlsaXR5IGluZGV4PyIsInVuaXQiOiJ4IiwicG9pbnRzIjoxMH0sCiAgICAgeyJpZCI6InE3IiwidHlwZSI6Im1jcSIsImxhYmVsIjoiUGF5YmFjayB3ZWFrbmVzcyIsInByb21wdCI6IkEgd2Vha25lc3Mgb2YgdGhlIHBheWJhY2sgcGVyaW9kIGlzIHRoYXQgaXTigKYiLCJvcHRpb25zIjpbeyJpZCI6ImEiLCJsYWJlbCI6Iklnbm9yZXMgdGhlIHRpbWUgdmFsdWUgb2YgbW9uZXkgYW5kIGNhc2ggZmxvd3MgYWZ0ZXIgcGF5YmFjayJ9LHsiaWQiOiJiIiwibGFiZWwiOiJOZWVkcyBhIGRpc2NvdW50IHJhdGUifSx7ImlkIjoiYyIsImxhYmVsIjoiSXMgdG9vIGNvbXBsZXgifSx7ImlkIjoiZCIsImxhYmVsIjoiQWx3YXlzIHJlamVjdHMgZ29vZCBwcm9qZWN0cyJ9XSwicG9pbnRzIjoxMH0sCiAgICAgeyJpZCI6InE4IiwidHlwZSI6Im51bWVyaWMiLCJsYWJlbCI6Ikx1bXAtc3VtIE5QViIsInByb21wdCI6IkludmVzdCDigrE1MDBrIG5vdyBhbmQgcmVjZWl2ZSDigrE4MDBrIGluIDMgeWVhcnMuIFJlcXVpcmVkIHJldHVybiAxMiUuIE5QViAo4oKxaywgdHdvIGRlY2ltYWxzKT8iLCJ1bml0Ijoi4oKxayIsInBvaW50cyI6MTB9LAogICAgIHsiaWQiOiJxOSIsInR5cGUiOiJtY3EiLCJsYWJlbCI6IkNvbmZsaWN0cyIsInByb21wdCI6IkZvciBtdXR1YWxseSBleGNsdXNpdmUgcHJvamVjdHMgd2hlcmUgTlBWIGFuZCBJUlIgZGlzYWdyZWUsIHByZWZlcuKApiIsIm9wdGlvbnMiOlt7ImlkIjoiYSIsImxhYmVsIjoiSVJSIn0seyJpZCI6ImIiLCJsYWJlbCI6Ik5QViJ9LHsiaWQiOiJjIiwibGFiZWwiOiJQYXliYWNrIn0seyJpZCI6ImQiLCJsYWJlbCI6IkFjY291bnRpbmcgcHJvZml0In1dLCJwb2ludHMiOjEwfSwKICAgICB7ImlkIjoicTEwIiwidHlwZSI6Im51bWVyaWMiLCJsYWJlbCI6IkRpc2NvdW50ZWQgcGF5YmFjayIsInByb21wdCI6IkNvc3Qg4oKxMzAwazsgaW5mbG93cyDigrExNTBrIGEgeWVhcjsgZGlzY291bnQgcmF0ZSAxMCUuIEluIHdoaWNoIHllYXIgKDEsIDIsIDPigKYpIGlzIHRoZSBkaXNjb3VudGVkIHBheWJhY2sgcmVhY2hlZD8iLCJ1bml0IjoieWVhciIsInBvaW50cyI6MTB9XQ==', 'base64'), 'UTF8')::jsonb,
 convert_from(decode('eyJxMSI6eyJhbnN3ZXIiOjExOS4wOCwidG9sZXJhbmNlX3BjdCI6MX0sInEyIjp7ImFuc3dlciI6ImEifSwicTMiOnsiYW5zd2VyIjozLCJ0b2xlcmFuY2VfcGN0IjowLjV9LCJxNCI6eyJhbnN3ZXIiOiJhIn0sInE1Ijp7ImFuc3dlciI6ImEifSwicTYiOnsiYW5zd2VyIjoxLjIsInRvbGVyYW5jZV9wY3QiOjAuNX0sInE3Ijp7ImFuc3dlciI6ImEifSwicTgiOnsiYW5zd2VyIjo2OS40MiwidG9sZXJhbmNlX3BjdCI6MX0sInE5Ijp7ImFuc3dlciI6ImIifSwicTEwIjp7ImFuc3dlciI6MywidG9sZXJhbmNlX3BjdCI6MC41fX0=', 'base64'), 'UTF8')::jsonb),
('working-capital-ccc',
 convert_from(decode('W3siaWQiOiJxMSIsInR5cGUiOiJudW1lcmljIiwibGFiZWwiOiJEU08iLCJwcm9tcHQiOiJBbm51YWwgc2FsZXMg4oKxNywzMDBrOyByZWNlaXZhYmxlcyDigrExLDAwMGsuIERTTyAoZGF5cywgMzY1LWRheSB5ZWFyKT8iLCJ1bml0IjoiZGF5cyIsInBvaW50cyI6MTB9LAogICAgIHsiaWQiOiJxMiIsInR5cGUiOiJudW1lcmljIiwibGFiZWwiOiJESU8iLCJwcm9tcHQiOiJBbm51YWwgQ09HUyDigrE1LDQ3NWs7IGludmVudG9yeSDigrExLDUwMGsuIERJTyAoZGF5cyk/IiwidW5pdCI6ImRheXMiLCJwb2ludHMiOjEwfSwKICAgICB7ImlkIjoicTMiLCJ0eXBlIjoibnVtZXJpYyIsImxhYmVsIjoiRFBPIiwicHJvbXB0IjoiQW5udWFsIENPR1Mg4oKxNSw0NzVrOyBwYXlhYmxlcyDigrE3NTBrLiBEUE8gKGRheXMpPyIsInVuaXQiOiJkYXlzIiwicG9pbnRzIjoxMH0sCiAgICAgeyJpZCI6InE0IiwidHlwZSI6Im51bWVyaWMiLCJsYWJlbCI6IkNDQyIsInByb21wdCI6IlVzaW5nIHRoZSB0aHJlZSByZXN1bHRzIGFib3ZlLCB0aGUgY2FzaCBjb252ZXJzaW9uIGN5Y2xlIChkYXlzKT8iLCJ1bml0IjoiZGF5cyIsInBvaW50cyI6MTB9LAogICAgIHsiaWQiOiJxNSIsInR5cGUiOiJtY3EiLCJsYWJlbCI6IlN1cHBsaWVyIHRlcm1zIiwicHJvbXB0IjoiTmVnb3RpYXRpbmcgbG9uZ2VyIHN1cHBsaWVyIHBheW1lbnQgdGVybXPigKYiLCJvcHRpb25zIjpbeyJpZCI6ImEiLCJsYWJlbCI6Ikxlbmd0aGVucyB0aGUgY2FzaCBjb252ZXJzaW9uIGN5Y2xlIn0seyJpZCI6ImIiLCJsYWJlbCI6IlNob3J0ZW5zIHRoZSBjYXNoIGNvbnZlcnNpb24gY3ljbGUifSx7ImlkIjoiYyIsImxhYmVsIjoiSGFzIG5vIGVmZmVjdCJ9LHsiaWQiOiJkIiwibGFiZWwiOiJSYWlzZXMgRFNPIn1dLCJwb2ludHMiOjEwfSwKICAgICB7ImlkIjoicTYiLCJ0eXBlIjoibWNxIiwibGFiZWwiOiJOZWdhdGl2ZSBDQ0MiLCJwcm9tcHQiOiJBIG5lZ2F0aXZlIGNhc2ggY29udmVyc2lvbiBjeWNsZSBtZWFuc+KApiIsIm9wdGlvbnMiOlt7ImlkIjoiYSIsImxhYmVsIjoiVGhlIGJ1c2luZXNzIGlzIGluc29sdmVudCJ9LHsiaWQiOiJiIiwibGFiZWwiOiJDdXN0b21lcnMgcGF5IGJlZm9yZSBzdXBwbGllcnMgbXVzdCBiZSBwYWlkIn0seyJpZCI6ImMiLCJsYWJlbCI6IkludmVudG9yeSBpcyBuZWdhdGl2ZSJ9LHsiaWQiOiJkIiwibGFiZWwiOiJTYWxlcyBhcmUgZmFsbGluZyJ9XSwicG9pbnRzIjoxMH0sCiAgICAgeyJpZCI6InE3IiwidHlwZSI6Im51bWVyaWMiLCJsYWJlbCI6IkNhc2ggcmVsZWFzZWQiLCJwcm9tcHQiOiJEYWlseSBzYWxlcyBhcmUg4oKxMjAsMDAwLiBDdXR0aW5nIERTTyBieSAxMCBkYXlzIHJlbGVhc2VzIGhvdyBtdWNoIGNhc2ggKOKCsSk/IiwidW5pdCI6IuKCsSIsInBvaW50cyI6MTB9LAogICAgIHsiaWQiOiJxOCIsInR5cGUiOiJudW1lcmljIiwibGFiZWwiOiJOZXQgd29ya2luZyBjYXBpdGFsIiwicHJvbXB0IjoiQ3VycmVudCBhc3NldHMg4oKxMy4wbTsgY3VycmVudCBsaWFiaWxpdGllcyDigrExLjhtLiBOZXQgd29ya2luZyBjYXBpdGFsICjigrFtKT8iLCJ1bml0Ijoi4oKxbSIsInBvaW50cyI6MTB9LAogICAgIHsiaWQiOiJxOSIsInR5cGUiOiJtY3EiLCJsYWJlbCI6Ikdyb3d0aCIsInByb21wdCI6IkEgZmFzdC1ncm93aW5nIGNvbXBhbnkgdXN1YWxseSBuZWVkc+KApiIsIm9wdGlvbnMiOlt7ImlkIjoiYSIsImxhYmVsIjoiTGVzcyB3b3JraW5nIGNhcGl0YWwifSx7ImlkIjoiYiIsImxhYmVsIjoiTW9yZSB3b3JraW5nIGNhcGl0YWwsIGFzIHN0b2NrIGFuZCByZWNlaXZhYmxlcyBhYnNvcmIgY2FzaCJ9LHsiaWQiOiJjIiwibGFiZWwiOiJObyBjaGFuZ2UgaW4gd29ya2luZyBjYXBpdGFsIn0seyJpZCI6ImQiLCJsYWJlbCI6Ik5lZ2F0aXZlIGludmVudG9yeSJ9XSwicG9pbnRzIjoxMH0sCiAgICAgeyJpZCI6InExMCIsInR5cGUiOiJtY3EiLCJsYWJlbCI6Ikxlbmd0aGVuaW5nIHRoZSBjeWNsZSIsInByb21wdCI6IldoaWNoIGFjdGlvbiBsZW5ndGhlbnMgdGhlIGNhc2ggY29udmVyc2lvbiBjeWNsZT8iLCJvcHRpb25zIjpbeyJpZCI6ImEiLCJsYWJlbCI6Ik9mZmVyaW5nIGN1c3RvbWVycyBsb25nZXIgY3JlZGl0IHRlcm1zIn0seyJpZCI6ImIiLCJsYWJlbCI6IkNvbGxlY3Rpbmcgb3ZlcmR1ZSBpbnZvaWNlcyBmYXN0ZXIifSx7ImlkIjoiYyIsImxhYmVsIjoiSG9sZGluZyBsZXNzIHN0b2NrIn0seyJpZCI6ImQiLCJsYWJlbCI6IlBheWluZyBzdXBwbGllcnMgbGF0ZXIifV0sInBvaW50cyI6MTB9XQ==', 'base64'), 'UTF8')::jsonb,
 convert_from(decode('eyJxMSI6eyJhbnN3ZXIiOjUwLCJ0b2xlcmFuY2VfcGN0IjowLjV9LCJxMiI6eyJhbnN3ZXIiOjEwMCwidG9sZXJhbmNlX3BjdCI6MC41fSwicTMiOnsiYW5zd2VyIjo1MCwidG9sZXJhbmNlX3BjdCI6MC41fSwicTQiOnsiYW5zd2VyIjoxMDAsInRvbGVyYW5jZV9wY3QiOjAuNX0sInE1Ijp7ImFuc3dlciI6ImIifSwicTYiOnsiYW5zd2VyIjoiYiJ9LCJxNyI6eyJhbnN3ZXIiOjIwMDAwMCwidG9sZXJhbmNlX3BjdCI6MC41fSwicTgiOnsiYW5zd2VyIjoxLjIsInRvbGVyYW5jZV9wY3QiOjAuNX0sInE5Ijp7ImFuc3dlciI6ImIifSwicTEwIjp7ImFuc3dlciI6ImEifX0=', 'base64'), 'UTF8')::jsonb),
('model-structure',
 convert_from(decode('W3siaWQiOiJxMSIsInR5cGUiOiJtY3EiLCJsYWJlbCI6IkNvbG91ciBjb2RlIiwicHJvbXB0IjoiQnkgbW9kZWxsaW5nIGNvbnZlbnRpb24sIGJsdWUgZm9udCBtYXJrc+KApiIsIm9wdGlvbnMiOlt7ImlkIjoiYSIsImxhYmVsIjoiRm9ybXVsYXMifSx7ImlkIjoiYiIsImxhYmVsIjoiSGFyZC1jb2RlZCBpbnB1dHMifSx7ImlkIjoiYyIsImxhYmVsIjoiTGlua3MgdG8gb3RoZXIgc2hlZXRzIn0seyJpZCI6ImQiLCJsYWJlbCI6IkVycm9ycyJ9XSwicG9pbnRzIjoxMH0sCiAgICAgeyJpZCI6InEyIiwidHlwZSI6Im1jcSIsImxhYmVsIjoiQXNzdW1wdGlvbnMiLCJwcm9tcHQiOiJXaGVyZSBzaG91bGQgYSBtb2RlbCdzIGFzc3VtcHRpb25zIGxpdmU/Iiwib3B0aW9ucyI6W3siaWQiOiJhIiwibGFiZWwiOiJUeXBlZCBpbnNpZGUgZm9ybXVsYXMifSx7ImlkIjoiYiIsImxhYmVsIjoiSW4gb25lIGNsZWFybHkgbGFiZWxsZWQgaW5wdXRzIGFyZWEifSx7ImlkIjoiYyIsImxhYmVsIjoiU2NhdHRlcmVkIGFjcm9zcyB0aGUgc3RhdGVtZW50cyJ9LHsiaWQiOiJkIiwibGFiZWwiOiJJbiBjb21tZW50cyBvbmx5In1dLCJwb2ludHMiOjEwfSwKICAgICB7ImlkIjoicTMiLCJ0eXBlIjoibWNxIiwibGFiZWwiOiJOZXQgaW5jb21lIGxpbmsiLCJwcm9tcHQiOiJOZXQgaW5jb21lIGZsb3dzIHRvIHdoaWNoIGJhbGFuY2Ugc2hlZXQgaXRlbT8iLCJvcHRpb25zIjpbeyJpZCI6ImEiLCJsYWJlbCI6IlJldGFpbmVkIGVhcm5pbmdzIn0seyJpZCI6ImIiLCJsYWJlbCI6IkFjY291bnRzIHBheWFibGUifSx7ImlkIjoiYyIsImxhYmVsIjoiUFAmRSJ9LHsiaWQiOiJkIiwibGFiZWwiOiJJbnZlbnRvcnkifV0sInBvaW50cyI6MTB9LAogICAgIHsiaWQiOiJxNCIsInR5cGUiOiJudW1lcmljIiwibGFiZWwiOiJQUCZFIHJvbGwtZm9yd2FyZCIsInByb21wdCI6Ik9wZW5pbmcgUFAmRSAxLDAwMDsgY2FwZXggMjAwOyBkZXByZWNpYXRpb24gMTUwLiBDbG9zaW5nIFBQJkU/IiwidW5pdCI6IiIsInBvaW50cyI6MTB9LAogICAgIHsiaWQiOiJxNSIsInR5cGUiOiJudW1lcmljIiwibGFiZWwiOiJSZXRhaW5lZCBlYXJuaW5ncyIsInByb21wdCI6Ik9wZW5pbmcgcmV0YWluZWQgZWFybmluZ3MgNTAwOyBuZXQgaW5jb21lIDEyMDsgZGl2aWRlbmRzIDQwLiBDbG9zaW5nIHJldGFpbmVkIGVhcm5pbmdzPyIsInVuaXQiOiIiLCJwb2ludHMiOjEwfSwKICAgICB7ImlkIjoicTYiLCJ0eXBlIjoibWNxIiwibGFiZWwiOiJCYWxhbmNlIGNoZWNrIiwicHJvbXB0IjoiVGhlIGJhbGFuY2UgY2hlY2sgaW4gYSBtb2RlbCB0ZXN0cyB0aGF04oCmIiwib3B0aW9ucyI6W3siaWQiOiJhIiwibGFiZWwiOiJSZXZlbnVlIGVxdWFscyBjb3N0cyJ9LHsiaWQiOiJiIiwibGFiZWwiOiJBc3NldHMgbWludXMgKGxpYWJpbGl0aWVzICsgZXF1aXR5KSBlcXVhbHMgemVybyBpbiBldmVyeSBwZXJpb2QifSx7ImlkIjoiYyIsImxhYmVsIjoiQ2FzaCBpcyBwb3NpdGl2ZSJ9LHsiaWQiOiJkIiwibGFiZWwiOiJHcm93dGggaXMgYmVsb3cgMTAlIn1dLCJwb2ludHMiOjEwfSwKICAgICB7ImlkIjoicTciLCJ0eXBlIjoibnVtZXJpYyIsImxhYmVsIjoiQ0ZPIiwicHJvbXB0IjoiTmV0IGluY29tZSAxMDA7IEQmQSAzMDsgcmVjZWl2YWJsZXMgdXAgMjA7IHBheWFibGVzIHVwIDEwLiBDYXNoIGZsb3cgZnJvbSBvcGVyYXRpb25zPyIsInVuaXQiOiIiLCJwb2ludHMiOjEwfSwKICAgICB7ImlkIjoicTgiLCJ0eXBlIjoibWNxIiwibGFiZWwiOiJSZXZvbHZlciIsInByb21wdCI6IkEgcmV2b2x2ZXIgaW4gYSBtb2RlbOKApiIsIm9wdGlvbnMiOlt7ImlkIjoiYSIsImxhYmVsIjoiUmVwYXlzIGFsbCBkZWJ0IGltbWVkaWF0ZWx5In0seyJpZCI6ImIiLCJsYWJlbCI6IkJvcnJvd3MgYXV0b21hdGljYWxseSB3aGVuIGNhc2ggd291bGQgZ28gbmVnYXRpdmUifSx7ImlkIjoiYyIsImxhYmVsIjoiQ2FsY3VsYXRlcyBkZXByZWNpYXRpb24ifSx7ImlkIjoiZCIsImxhYmVsIjoiUmVwbGFjZXMgdGhlIGJhbGFuY2Ugc2hlZXQifV0sInBvaW50cyI6MTB9LAogICAgIHsiaWQiOiJxOSIsInR5cGUiOiJtY3EiLCJsYWJlbCI6IkhhcmQtY29kZXMiLCJwcm9tcHQiOiJXaHkgaXMgaGFyZC1jb2RpbmcgYSBudW1iZXIgaW5zaWRlIGEgZm9ybXVsYSByaXNreT8iLCJvcHRpb25zIjpbeyJpZCI6ImEiLCJsYWJlbCI6Ikl0IGhpZGVzIGFuIGFzc3VtcHRpb24gYW5kIGlzIGVhc2lseSBtaXNzZWQgd2hlbiBpbnB1dHMgY2hhbmdlIn0seyJpZCI6ImIiLCJsYWJlbCI6Ikl0IG1ha2VzIHRoZSBmaWxlIGxhcmdlciJ9LHsiaWQiOiJjIiwibGFiZWwiOiJJdCBpcyBub3QgYWxsb3dlZCBpbiBFeGNlbCJ9LHsiaWQiOiJkIiwibGFiZWwiOiJJdCBhbHdheXMgY2hhbmdlcyB0aGUgcmVzdWx0In1dLCJwb2ludHMiOjEwfSwKICAgICB7ImlkIjoicTEwIiwidHlwZSI6Im51bWVyaWMiLCJsYWJlbCI6IkNsb3NpbmcgY2FzaCIsInByb21wdCI6Ik9wZW5pbmcgY2FzaCAyNTA7IENGTyAxMjA7IENGSSDiiJIyMDA7IENGRiArNTAuIENsb3NpbmcgY2FzaD8iLCJ1bml0IjoiIiwicG9pbnRzIjoxMH1d', 'base64'), 'UTF8')::jsonb,
 convert_from(decode('eyJxMSI6eyJhbnN3ZXIiOiJiIn0sInEyIjp7ImFuc3dlciI6ImIifSwicTMiOnsiYW5zd2VyIjoiYSJ9LCJxNCI6eyJhbnN3ZXIiOjEwNTAsInRvbGVyYW5jZV9wY3QiOjAuNX0sInE1Ijp7ImFuc3dlciI6NTgwLCJ0b2xlcmFuY2VfcGN0IjowLjV9LCJxNiI6eyJhbnN3ZXIiOiJiIn0sInE3Ijp7ImFuc3dlciI6MTIwLCJ0b2xlcmFuY2VfcGN0IjowLjV9LCJxOCI6eyJhbnN3ZXIiOiJiIn0sInE5Ijp7ImFuc3dlciI6ImEifSwicTEwIjp7ImFuc3dlciI6MjIwLCJ0b2xlcmFuY2VfcGN0IjowLjV9fQ==', 'base64'), 'UTF8')::jsonb),
('revenue-drivers-forecasting',
 convert_from(decode('W3siaWQiOiJxMSIsInR5cGUiOiJudW1lcmljIiwibGFiZWwiOiJQcmljZSDDlyB2b2x1bWUiLCJwcm9tcHQiOiIxLDAwMCB1bml0cyBhcmUgc29sZCBhdCDigrEyNTAuIFJldmVudWUgKOKCsSk/IiwidW5pdCI6IuKCsSIsInBvaW50cyI6MTB9LAogICAgIHsiaWQiOiJxMiIsInR5cGUiOiJudW1lcmljIiwibGFiZWwiOiJDb21iaW5lZCBncm93dGgiLCJwcm9tcHQiOiJVbml0cyBncm93IDEwJSBhbmQgcHJpY2UgZ3Jvd3MgNSUuIFJldmVudWUgZ3Jvd3RoICglLCBvbmUgZGVjaW1hbCk/IiwidW5pdCI6IiUiLCJwb2ludHMiOjEwfSwKICAgICB7ImlkIjoicTMiLCJ0eXBlIjoibWNxIiwibGFiZWwiOiJXaHkgZHJpdmVycyIsInByb21wdCI6IldoeSBmb3JlY2FzdCByZXZlbnVlIGZyb20gZHJpdmVycyByYXRoZXIgdGhhbiBhIHNpbmdsZSBncm93dGggcmF0ZT8iLCJvcHRpb25zIjpbeyJpZCI6ImEiLCJsYWJlbCI6IkVhY2ggYXNzdW1wdGlvbiBpcyBleHBsaWNpdCBhbmQgY2FuIGJlIHRlc3RlZCJ9LHsiaWQiOiJiIiwibGFiZWwiOiJJdCBhbHdheXMgZ2l2ZXMgYSBoaWdoZXIgZm9yZWNhc3QifSx7ImlkIjoiYyIsImxhYmVsIjoiSXQgbmVlZHMgZmV3ZXIgaW5wdXRzIn0seyJpZCI6ImQiLCJsYWJlbCI6Ikl0IGF2b2lkcyBjaGVja2luZyBoaXN0b3J5In1dLCJwb2ludHMiOjEwfSwKICAgICB7ImlkIjoicTQiLCJ0eXBlIjoibnVtZXJpYyIsImxhYmVsIjoiQ3VzdG9tZXJzIiwicHJvbXB0IjoiT3BlbmluZyAxMCwwMDAgY3VzdG9tZXJzOyAyJSBjaHVybiBhIG1vbnRoOyA1MDAgbmV3IGN1c3RvbWVycy4gQ2xvc2luZyBjdXN0b21lcnMgYWZ0ZXIgbW9udGggMT8iLCJ1bml0IjoiIiwicG9pbnRzIjoxMH0sCiAgICAgeyJpZCI6InE1IiwidHlwZSI6Im51bWVyaWMiLCJsYWJlbCI6IlN1YnNjcmlwdGlvbiByZXZlbnVlIiwicHJvbXB0IjoiTW9udGgtMSByZXZlbnVlIHdpdGggMTAsMzAwIGN1c3RvbWVycyBhdCDigrEzMDAgQVJQVSAo4oKxKT8iLCJ1bml0Ijoi4oKxIiwicG9pbnRzIjoxMH0sCiAgICAgeyJpZCI6InE2IiwidHlwZSI6Im1jcSIsImxhYmVsIjoiUmV0YWlsIGdyb3d0aCIsInByb21wdCI6IkEgcmV0YWlsZXIncyByZXZlbnVlIGdyb3d0aCBpcyBiZXN0IGRlY29tcG9zZWQgaW50b+KApiIsIm9wdGlvbnMiOlt7ImlkIjoiYSIsImxhYmVsIjoiU2FtZS1zdG9yZSBncm93dGggcGx1cyBuZXctc3RvcmUgY29udHJpYnV0aW9uIn0seyJpZCI6ImIiLCJsYWJlbCI6IkRlYnQgYW5kIGVxdWl0eSJ9LHsiaWQiOiJjIiwibGFiZWwiOiJHcm9zcyBhbmQgbmV0IG1hcmdpbiJ9LHsiaWQiOiJkIiwibGFiZWwiOiJUYXggYW5kIGludGVyZXN0In1dLCJwb2ludHMiOjEwfSwKICAgICB7ImlkIjoicTciLCJ0eXBlIjoibnVtZXJpYyIsImxhYmVsIjoiTWFya2V0IHNoYXJlIiwicHJvbXB0IjoiQSDigrE0MGJuIG1hcmtldCBncm93cyA2JSBpbiB5ZWFyIDIuIEEgZmlybSBob2xkcyAxMi41JSBzaGFyZSBpbiB5ZWFyIDIuIEl0cyB5ZWFyLTIgcmV2ZW51ZSAo4oKxYm4pPyIsInVuaXQiOiLigrFibiIsInBvaW50cyI6MTB9LAogICAgIHsiaWQiOiJxOCIsInR5cGUiOiJtY3EiLCJsYWJlbCI6IkhvY2tleSBzdGljayIsInByb21wdCI6IkEgaG9ja2V5LXN0aWNrIGZvcmVjYXN0IGlz4oCmIiwib3B0aW9ucyI6W3siaWQiOiJhIiwibGFiZWwiOiJBIHN1ZGRlbiBhY2NlbGVyYXRpb24gaW4gZ3Jvd3RoIHdpdGggbm8gY2xlYXIgZHJpdmVyIOKAlCBhIHJlZCBmbGFnIn0seyJpZCI6ImIiLCJsYWJlbCI6IkEgc3RlYWR5IDUlIGdyb3d0aCBsaW5lIn0seyJpZCI6ImMiLCJsYWJlbCI6IkEgc2Vhc29uYWwgcGF0dGVybiJ9LHsiaWQiOiJkIiwibGFiZWwiOiJBIGNvbnNlcnZhdGl2ZSBjYXNlIn1dLCJwb2ludHMiOjEwfSwKICAgICB7ImlkIjoicTkiLCJ0eXBlIjoibnVtZXJpYyIsImxhYmVsIjoiQ0FHUiIsInByb21wdCI6IlJldmVudWUgZ3Jvd3MgZnJvbSAxLDAwMCB0byAxLDIxMCBvdmVyIDIgeWVhcnMuIENBR1IgKCUpPyIsInVuaXQiOiIlIiwicG9pbnRzIjoxMH0sCiAgICAgeyJpZCI6InExMCIsInR5cGUiOiJtY3EiLCJsYWJlbCI6IlNhbml0eSBjaGVja3MiLCJwcm9tcHQiOiJBIGZvcmVjYXN0IHNob3VsZCBiZSBzYW5pdHktY2hlY2tlZCBhZ2FpbnN04oCmIiwib3B0aW9ucyI6W3siaWQiOiJhIiwibGFiZWwiOiJIaXN0b3J5LCBjYXBhY2l0eSBhbmQgbWFya2V0IHNpemUifSx7ImlkIjoiYiIsImxhYmVsIjoiVGhlIENFTydzIHByZWZlcmVuY2UifSx7ImlkIjoiYyIsImxhYmVsIjoiVGhlIHByaW9yIGZvcmVjYXN0IG9ubHkifSx7ImlkIjoiZCIsImxhYmVsIjoiTm90aGluZyDigJQgaXQgaXMgYW4gb3BpbmlvbiJ9XSwicG9pbnRzIjoxMH1d', 'base64'), 'UTF8')::jsonb,
 convert_from(decode('eyJxMSI6eyJhbnN3ZXIiOjI1MDAwMCwidG9sZXJhbmNlX3BjdCI6MC41fSwicTIiOnsiYW5zd2VyIjoxNS41LCJ0b2xlcmFuY2VfcGN0IjoxfSwicTMiOnsiYW5zd2VyIjoiYSJ9LCJxNCI6eyJhbnN3ZXIiOjEwMzAwLCJ0b2xlcmFuY2VfcGN0IjowLjV9LCJxNSI6eyJhbnN3ZXIiOjMwOTAwMDAsInRvbGVyYW5jZV9wY3QiOjAuNX0sInE2Ijp7ImFuc3dlciI6ImEifSwicTciOnsiYW5zd2VyIjo1LjMsInRvbGVyYW5jZV9wY3QiOjF9LCJxOCI6eyJhbnN3ZXIiOiJhIn0sInE5Ijp7ImFuc3dlciI6MTAsInRvbGVyYW5jZV9wY3QiOjF9LCJxMTAiOnsiYW5zd2VyIjoiYSJ9fQ==', 'base64'), 'UTF8')::jsonb),
('scenarios-sensitivity',
 convert_from(decode('W3siaWQiOiJxMSIsInR5cGUiOiJtY3EiLCJsYWJlbCI6IkRpZmZlcmVuY2UiLCJwcm9tcHQiOiJTZW5zaXRpdml0eSBhbmFseXNpcyBkaWZmZXJzIGZyb20gc2NlbmFyaW8gYW5hbHlzaXMgYmVjYXVzZSBpdOKApiIsIm9wdGlvbnMiOlt7ImlkIjoiYSIsImxhYmVsIjoiQ2hhbmdlcyBvbmUgaW5wdXQgYXQgYSB0aW1lIn0seyJpZCI6ImIiLCJsYWJlbCI6IkNoYW5nZXMgc2V2ZXJhbCBsaW5rZWQgaW5wdXRzIHRvZ2V0aGVyIn0seyJpZCI6ImMiLCJsYWJlbCI6Iklnbm9yZXMgb3V0cHV0cyJ9LHsiaWQiOiJkIiwibGFiZWwiOiJOZWVkcyB0aHJlZSBjYXNlcyJ9XSwicG9pbnRzIjoxMH0sCiAgICAgeyJpZCI6InEyIiwidHlwZSI6Im1jcSIsImxhYmVsIjoiQmFzZSBjYXNlIiwicHJvbXB0IjoiVGhlIGJhc2UgY2FzZSBpc+KApiIsIm9wdGlvbnMiOlt7ImlkIjoiYSIsImxhYmVsIjoiVGhlIG1vc3QgbGlrZWx5IHNldCBvZiBhc3N1bXB0aW9ucyJ9LHsiaWQiOiJiIiwibGFiZWwiOiJUaGUgd29yc3QgY2FzZSJ9LHsiaWQiOiJjIiwibGFiZWwiOiJUaGUgYmVzdCBjYXNlIn0seyJpZCI6ImQiLCJsYWJlbCI6Ikxhc3QgeWVhcidzIGFjdHVhbHMifV0sInBvaW50cyI6MTB9LAogICAgIHsiaWQiOiJxMyIsInR5cGUiOiJudW1lcmljIiwibGFiZWwiOiJFViBhdCA4eCIsInByb21wdCI6IkVCSVREQSDigrEyMDBtIGF0IGFuIDh4IEVWL0VCSVREQSBtdWx0aXBsZS4gRW50ZXJwcmlzZSB2YWx1ZSAo4oKxbSk/IiwidW5pdCI6IuKCsW0iLCJwb2ludHMiOjEwfSwKICAgICB7ImlkIjoicTQiLCJ0eXBlIjoibnVtZXJpYyIsImxhYmVsIjoiRVYgYXQgN3giLCJwcm9tcHQiOiJUaGUgc2FtZSBFQklUREEgYXQgYSA3eCBtdWx0aXBsZS4gRW50ZXJwcmlzZSB2YWx1ZSAo4oKxbSk/IiwidW5pdCI6IuKCsW0iLCJwb2ludHMiOjEwfSwKICAgICB7ImlkIjoicTUiLCJ0eXBlIjoibnVtZXJpYyIsImxhYmVsIjoiVmFsdWUgY2hhbmdlIiwicHJvbXB0IjoiQSAxLXBvaW50IHJpc2UgaW4gV0FDQyBjdXRzIHZhbHVlIGZyb20g4oKxMTAwIHRvIOKCsTg4LiBCeSB3aGF0ICUgZG9lcyB2YWx1ZSBmYWxsPyIsInVuaXQiOiIlIiwicG9pbnRzIjoxMH0sCiAgICAgeyJpZCI6InE2IiwidHlwZSI6Im1jcSIsImxhYmVsIjoiVG9ybmFkbyBjaGFydCIsInByb21wdCI6IkEgdG9ybmFkbyBjaGFydCBzaG93c+KApiIsIm9wdGlvbnMiOlt7ImlkIjoiYSIsImxhYmVsIjoiV2hpY2ggaW5wdXQgbW92ZXMgdGhlIG91dHB1dCB0aGUgbW9zdCJ9LHsiaWQiOiJiIiwibGFiZWwiOiJUaGUgYmFsYW5jZSBzaGVldCBvdmVyIHRpbWUifSx7ImlkIjoiYyIsImxhYmVsIjoiQ2FzaCBieSBtb250aCJ9LHsiaWQiOiJkIiwibGFiZWwiOiJQcm9iYWJpbGl0eSBvZiBkZWZhdWx0In1dLCJwb2ludHMiOjEwfSwKICAgICB7ImlkIjoicTciLCJ0eXBlIjoibnVtZXJpYyIsImxhYmVsIjoiRXhwZWN0ZWQgdmFsdWUiLCJwcm9tcHQiOiJCdWxsIDI1JSBhdCDigrExNDA7IGJhc2UgNTAlIGF0IOKCsTEwMDsgYmVhciAyNSUgYXQg4oKxNjAuIFByb2JhYmlsaXR5LXdlaWdodGVkIHZhbHVlICjigrEpPyIsInVuaXQiOiLigrEiLCJwb2ludHMiOjEwfSwKICAgICB7ImlkIjoicTgiLCJ0eXBlIjoibnVtZXJpYyIsImxhYmVsIjoiRXhwZWN0ZWQgdmFsdWUgMiIsInByb21wdCI6IkJ1bGwgMjAlIGF0IOKCsTE1MDsgYmFzZSA1MCUgYXQg4oKxMTAwOyBiZWFyIDMwJSBhdCDigrE1MC4gUHJvYmFiaWxpdHktd2VpZ2h0ZWQgdmFsdWUgKOKCsSk/IiwidW5pdCI6IuKCsSIsInBvaW50cyI6MTB9LAogICAgIHsiaWQiOiJxOSIsInR5cGUiOiJtY3EiLCJsYWJlbCI6IlNjZW5hcmlvIHN3aXRjaCIsInByb21wdCI6IkEgc2NlbmFyaW8gc3dpdGNoIGluIGEgbW9kZWzigKYiLCJvcHRpb25zIjpbeyJpZCI6ImEiLCJsYWJlbCI6IkNoYW5nZXMgYWxsIGxpbmtlZCBkcml2ZXJzIHRvZ2V0aGVyIHVzaW5nIENIT09TRSBvciBJTkRFWCJ9LHsiaWQiOiJiIiwibGFiZWwiOiJEZWxldGVzIHRoZSBvdGhlciBjYXNlcyJ9LHsiaWQiOiJjIiwibGFiZWwiOiJPbmx5IGNoYW5nZXMgdGhlIHRheCByYXRlIn0seyJpZCI6ImQiLCJsYWJlbCI6IkxvY2tzIHRoZSBiYWxhbmNlIHNoZWV0In1dLCJwb2ludHMiOjEwfSwKICAgICB7ImlkIjoicTEwIiwidHlwZSI6Im1jcSIsImxhYmVsIjoiQmVhciBjYXNlIiwicHJvbXB0IjoiQSBnb29kIGJlYXIgY2FzZSBzaG91bGQgc3RyZXNz4oCmIiwib3B0aW9ucyI6W3siaWQiOiJhIiwibGFiZWwiOiJMaXF1aWRpdHkgYW5kIGNvdmVuYW50cyBhcyB3ZWxsIGFzIGVhcm5pbmdzIn0seyJpZCI6ImIiLCJsYWJlbCI6Ik9ubHkgcmV2ZW51ZSJ9LHsiaWQiOiJjIiwibGFiZWwiOiJPbmx5IHRoZSBzaGFyZSBwcmljZSJ9LHsiaWQiOiJkIiwibGFiZWwiOiJOb3RoaW5nIOKAlCBpdCBpcyBoeXBvdGhldGljYWwifV0sInBvaW50cyI6MTB9XQ==', 'base64'), 'UTF8')::jsonb,
 convert_from(decode('eyJxMSI6eyJhbnN3ZXIiOiJhIn0sInEyIjp7ImFuc3dlciI6ImEifSwicTMiOnsiYW5zd2VyIjoxNjAwLCJ0b2xlcmFuY2VfcGN0IjowLjV9LCJxNCI6eyJhbnN3ZXIiOjE0MDAsInRvbGVyYW5jZV9wY3QiOjAuNX0sInE1Ijp7ImFuc3dlciI6MTIsInRvbGVyYW5jZV9wY3QiOjF9LCJxNiI6eyJhbnN3ZXIiOiJhIn0sInE3Ijp7ImFuc3dlciI6MTAwLCJ0b2xlcmFuY2VfcGN0IjowLjV9LCJxOCI6eyJhbnN3ZXIiOjk1LCJ0b2xlcmFuY2VfcGN0IjowLjV9LCJxOSI6eyJhbnN3ZXIiOiJhIn0sInExMCI6eyJhbnN3ZXIiOiJhIn19', 'base64'), 'UTF8')::jsonb)
), upd as (
  update public.lessons l set check_questions = qs.questions::jsonb
  from qs where l.slug = qs.slug and jsonb_array_length(l.check_questions) = 0
  returning l.id, qs.answers
)
insert into public.lesson_check_keys (lesson_id, answers)
select id, answers::jsonb from upd
on conflict (lesson_id) do nothing;
