-- seed_009_accounting: part 2 of 3. Run the parts in order.
-- ---------------------------------------------------------------------
-- 3. Practice activities
-- ---------------------------------------------------------------------
insert into public.lesson_activities (lesson_id, slug, position, kind, title, instructions, content)
select l.id, v.slug, v.pos, v.kind, v.title, v.instructions, v.content::jsonb
from (values
('accounting-equation-journal', 'debit-or-credit', 1, 'matching', 'Debit or credit?',
 'Each account increases with either a debit or a credit. Sort them.',
 '{"categories":[{"id":"dr","label":"Increases with a debit"},{"id":"cr","label":"Increases with a credit"}],
     "items":[{"id":"i1","label":"Cash"},{"id":"i2","label":"Accounts payable"},{"id":"i3","label":"Rent expense"},{"id":"i4","label":"Service revenue"},{"id":"i5","label":"Equipment"},
              {"id":"i6","label":"Owner''s capital"},{"id":"i7","label":"Supplies"},{"id":"i8","label":"Bank loan"},{"id":"i9","label":"Utilities expense"}]}'),
('accounting-equation-journal', 'print-shop-month', 2, 'worked_example', 'Worked example: a month at Maria''s Print Shop',
 'Follow the transactions and keep the equation balanced. Hints are available but cost points.',
 '{"intro":"Maria''s Print Shop (₱): the owner invests 200,000 cash; buys equipment for 120,000 cash; earns 50,000 of service revenue in cash; pays 15,000 rent in cash.",
     "steps":[{"id":"s1","prompt":"Cash after the owner''s investment (₱)?","unit":"₱"},{"id":"s2","prompt":"Cash after buying the equipment (₱)?","unit":"₱"},
              {"id":"s3","prompt":"Cash after the revenue and the rent (₱)?","unit":"₱"},{"id":"s4","prompt":"Total assets (cash + equipment) (₱)?","unit":"₱"},
              {"id":"s5","prompt":"Owner''s equity (capital + revenue − rent) (₱)?","unit":"₱"}]}'),
('adjusting-entries', 'type-of-adjustment', 1, 'matching', 'Which adjustment is it?',
 'Place each situation under the type of adjusting entry it needs.',
 '{"categories":[{"id":"pe","label":"Prepaid expense"},{"id":"ur","label":"Unearned revenue"},{"id":"ae","label":"Accrued expense"},{"id":"ar","label":"Accrued revenue"}],
     "items":[{"id":"i1","label":"Rent paid for the next 6 months"},{"id":"i2","label":"Customer deposit for future work"},{"id":"i3","label":"Wages owed to staff at month end"},
              {"id":"i4","label":"Interest earned but not yet received"},{"id":"i5","label":"Annual insurance paid upfront"},{"id":"i6","label":"Subscription paid in advance by a customer"},
              {"id":"i7","label":"Electricity used but not yet billed"},{"id":"i8","label":"Consulting done but not yet invoiced"}]}'),
('adjusting-entries', 'adjusting-entry-errors', 2, 'spot_error', 'Spot the errors: adjusting entries',
 'Two of these adjusting entries are wrong. Select them, then check.',
 '{"context":"Year end is 31 December. Amounts in ₱.","columns":["Situation","Adjusting entry"],"select_count":2,
     "rows":[{"id":"r1","cells":["₱12,000 rent paid on 1 Mar for 6 months; adjust at 31 Mar","Dr Rent expense 2,000 / Cr Prepaid rent 2,000"]},
             {"id":"r2","cells":["₱30,000 of wages earned but unpaid at year end","Dr Wages payable 30,000 / Cr Wages expense 30,000"]},
             {"id":"r3","cells":["Customer prepaid ₱36,000 for 12 months on 1 Jul","Dr Unearned revenue 18,000 / Cr Service revenue 18,000"]},
             {"id":"r4","cells":["₱4,000 of interest earned but not yet received","Dr Interest receivable 4,000 / Cr Interest revenue 4,000"]},
             {"id":"r5","cells":["Supplies used during the period: ₱6,500","Dr Supplies 6,500 / Cr Supplies expense 6,500"]},
             {"id":"r6","cells":["₱24,000 insurance paid on 1 Oct for 12 months","Dr Insurance expense 6,000 / Cr Prepaid insurance 6,000"]}]}'),
('inventory-cogs-methods', 'fifo-vs-average', 1, 'worked_example', 'Worked example: FIFO vs weighted average',
 'Cost the same sales two ways. Hints are available but cost points.',
 '{"intro":"A shop has 100 units at ₱20 (opening stock) and buys 100 more units at ₱24. It sells 150 units.",
     "steps":[{"id":"s1","prompt":"Units available for sale?","unit":"units"},{"id":"s2","prompt":"Total cost of goods available (₱)?","unit":"₱"},
              {"id":"s3","prompt":"FIFO cost of goods sold (₱)?","unit":"₱"},{"id":"s4","prompt":"Weighted-average cost per unit (₱)?","unit":"₱"},
              {"id":"s5","prompt":"Weighted-average cost of goods sold (₱)?","unit":"₱"}]}'),
('inventory-cogs-methods', 'method-effects', 2, 'matching', 'Which method does that describe?',
 'Assume prices are rising. Match each statement to the method it describes.',
 '{"categories":[{"id":"fifo","label":"FIFO"},{"id":"wa","label":"Weighted average"}],
     "items":[{"id":"i1","label":"Reports the lowest COGS"},{"id":"i2","label":"Reports the highest ending inventory"},{"id":"i3","label":"Smooths out price changes"},
              {"id":"i4","label":"Uses one average cost per unit"},{"id":"i5","label":"Assumes the oldest units are sold first"},{"id":"i6","label":"Cost available ÷ units available"}]}'),
('depreciation-ppe', 'sl-vs-ddb', 1, 'worked_example', 'Worked example: straight-line vs double-declining',
 'Depreciate the same truck two ways. Hints are available but cost points.',
 '{"intro":"A truck costs ₱800,000 with salvage value ₱80,000 and a 4-year life.",
     "steps":[{"id":"s1","prompt":"Straight-line depreciation per year (₱)?","unit":"₱"},{"id":"s2","prompt":"Straight-line book value at the end of year 2 (₱)?","unit":"₱"},
              {"id":"s3","prompt":"Double-declining year-1 expense (rate 50%) (₱)?","unit":"₱"},{"id":"s4","prompt":"Double-declining year-2 expense (₱)?","unit":"₱"},
              {"id":"s5","prompt":"Double-declining book value at the end of year 2 (₱)?","unit":"₱"}]}'),
('depreciation-ppe', 'fixed-asset-errors', 2, 'spot_error', 'Spot the errors: fixed asset schedule',
 'Two lines in this schedule are wrong. Select them, then check.',
 '{"context":"Equipment cost ₱600,000; salvage value ₱60,000; 6-year life; straight-line.","columns":["Line","Amount (₱)"],"select_count":2,
     "rows":[{"id":"r1","cells":["Annual depreciation","100,000"]},{"id":"r2","cells":["Accumulated depreciation after 3 years","270,000"]},
             {"id":"r3","cells":["Book value after 3 years","330,000"]},{"id":"r4","cells":["Depreciation expense in year 7","90,000"]},
             {"id":"r5","cells":["Book value at the end of the useful life","60,000"]}]}'),
('receivables-bad-debts', 'aging-analysis', 1, 'worked_example', 'Worked example: aging of receivables',
 'Build the required allowance and the year''s expense. Hints are available but cost points.',
 '{"intro":"Aging (₱): current 2,000,000 at 1%; 31–60 days 600,000 at 4%; 61–90 days 300,000 at 10%; over 90 days 100,000 at 40%. The allowance currently has a credit balance of 35,000.",
     "steps":[{"id":"s1","prompt":"Allowance needed for current receivables (₱)?","unit":"₱"},{"id":"s2","prompt":"Allowance needed for 31–60 days (₱)?","unit":"₱"},
              {"id":"s3","prompt":"Allowance needed for 61–90 days (₱)?","unit":"₱"},{"id":"s4","prompt":"Allowance needed for over 90 days (₱)?","unit":"₱"},
              {"id":"s5","prompt":"Total required allowance (₱)?","unit":"₱"},{"id":"s6","prompt":"Bad debt expense for the year (₱)?","unit":"₱"}]}'),
('receivables-bad-debts', 'which-entry', 2, 'matching', 'Adjustment, write-off or recovery?',
 'Match each description to the type of entry.',
 '{"categories":[{"id":"adj","label":"Period-end adjustment"},{"id":"wo","label":"Write-off"},{"id":"rec","label":"Recovery"}],
     "items":[{"id":"i1","label":"Dr Bad debt expense, Cr Allowance"},{"id":"i2","label":"Dr Allowance, Cr Accounts receivable"},{"id":"i3","label":"Reinstate the receivable, then record the cash received"},
              {"id":"i4","label":"Increases expenses in the income statement"},{"id":"i5","label":"Leaves net receivables unchanged"},{"id":"i6","label":"A customer pays an account already written off"},
              {"id":"i7","label":"Recorded once a period from an estimate"},{"id":"i8","label":"Triggered when a specific customer is declared uncollectible"}]}'),
('revenue-recognition', 'timing-of-revenue', 1, 'matching', 'Point in time or over time?',
 'Decide when revenue is recognised for each situation.',
 '{"categories":[{"id":"pit","label":"At a point in time"},{"id":"ot","label":"Over time"}],
     "items":[{"id":"i1","label":"Selling a phone in a store"},{"id":"i2","label":"12-month software support contract"},{"id":"i3","label":"Building a facility on the customer''s land"},
              {"id":"i4","label":"Goods whose control passes on delivery"},{"id":"i5","label":"A monthly gym membership"},{"id":"i6","label":"A perpetual software licence delivered today"}]}'),
('revenue-recognition', 'allocate-price', 2, 'worked_example', 'Worked example: allocate the transaction price',
 'Split a bundle price and time the revenue. Hints are available but cost points.',
 '{"intro":"A bundle of a laptop (standalone price ₱60,000) and a 2-year service plan (standalone price ₱20,000) is sold for ₱72,000. The laptop is delivered now; the service is delivered evenly over 2 years.",
     "steps":[{"id":"s1","prompt":"Total of the standalone prices (₱)?","unit":"₱"},{"id":"s2","prompt":"Price allocated to the laptop (₱)?","unit":"₱"},
              {"id":"s3","prompt":"Price allocated to the service plan (₱)?","unit":"₱"},{"id":"s4","prompt":"Service revenue per year (₱)?","unit":"₱"},
              {"id":"s5","prompt":"Total revenue recognised in year 1 (₱)?","unit":"₱"}]}')
) as v(lesson, slug, pos, kind, title, instructions, content)
join public.lessons l on l.slug = v.lesson
on conflict (lesson_id, slug) do update
  set position = excluded.position, kind = excluded.kind, title = excluded.title,
      instructions = excluded.instructions, content = excluded.content;

insert into public.lesson_activity_keys (activity_id, key)
select a.id, v.key::jsonb
from (values
('accounting-equation-journal', 'debit-or-credit', '{"i1":"dr","i2":"cr","i3":"dr","i4":"cr","i5":"dr","i6":"cr","i7":"dr","i8":"cr","i9":"dr"}'),
('accounting-equation-journal', 'print-shop-month', '{
  "s1":{"answer":200000,"tolerance_pct":0.5,"hint":"Only the owner''s cash investment so far.","explanation":"Cash = 200,000."},
  "s2":{"answer":80000,"tolerance_pct":0.5,"hint":"Buying equipment swaps cash for equipment.","explanation":"200,000 − 120,000 = 80,000."},
  "s3":{"answer":115000,"tolerance_pct":0.5,"hint":"Add the revenue, subtract the rent.","explanation":"80,000 + 50,000 − 15,000 = 115,000."},
  "s4":{"answer":235000,"tolerance_pct":0.5,"hint":"Cash plus equipment (at cost).","explanation":"115,000 + 120,000 = 235,000."},
  "s5":{"answer":235000,"tolerance_pct":0.5,"hint":"There are no liabilities, so equity equals assets.","explanation":"200,000 + 50,000 − 15,000 = 235,000 — equal to total assets, so the equation balances."}}'),
('adjusting-entries', 'type-of-adjustment', '{"i1":"pe","i2":"ur","i3":"ae","i4":"ar","i5":"pe","i6":"ur","i7":"ae","i8":"ar"}'),
('adjusting-entries', 'adjusting-entry-errors', '{"errors":["r2","r5"],"explanations":{"r2":"Accrued wages are Dr Wages expense / Cr Wages payable. The entry shown is reversed.","r5":"Using supplies is Dr Supplies expense / Cr Supplies. The entry shown is reversed."}}'),
('inventory-cogs-methods', 'fifo-vs-average', '{
  "s1":{"answer":200,"tolerance_pct":0.5,"hint":"Opening units plus purchased units.","explanation":"100 + 100 = 200."},
  "s2":{"answer":4400,"tolerance_pct":0.5,"hint":"100 × 20 plus 100 × 24.","explanation":"2,000 + 2,400 = 4,400."},
  "s3":{"answer":3200,"tolerance_pct":0.5,"hint":"The 100 older units at 20, then 50 units at 24.","explanation":"100 × 20 + 50 × 24 = 3,200."},
  "s4":{"answer":22,"tolerance_pct":0.5,"hint":"Total cost ÷ total units.","explanation":"4,400 ÷ 200 = 22."},
  "s5":{"answer":3300,"tolerance_pct":0.5,"hint":"Units sold × average cost.","explanation":"150 × 22 = 3,300. FIFO COGS is lower, so FIFO profit is higher when prices rise."}}'),
('inventory-cogs-methods', 'method-effects', '{"i1":"fifo","i2":"fifo","i3":"wa","i4":"wa","i5":"fifo","i6":"wa"}'),
('depreciation-ppe', 'sl-vs-ddb', '{
  "s1":{"answer":180000,"tolerance_pct":0.5,"hint":"(Cost − salvage) ÷ life.","explanation":"(800,000 − 80,000) ÷ 4 = 180,000."},
  "s2":{"answer":440000,"tolerance_pct":0.5,"hint":"Cost minus two years of depreciation.","explanation":"800,000 − 2 × 180,000 = 440,000."},
  "s3":{"answer":400000,"tolerance_pct":0.5,"hint":"Rate × opening book value (salvage is ignored).","explanation":"50% × 800,000 = 400,000."},
  "s4":{"answer":200000,"tolerance_pct":0.5,"hint":"Rate × the new opening book value of 400,000.","explanation":"50% × 400,000 = 200,000."},
  "s5":{"answer":200000,"tolerance_pct":0.5,"hint":"Cost minus the two years of expense.","explanation":"800,000 − 400,000 − 200,000 = 200,000."}}'),
('depreciation-ppe', 'fixed-asset-errors', '{"errors":["r1","r4"],"explanations":{"r1":"Annual depreciation = (600,000 − 60,000) ÷ 6 = 90,000. The salvage value must be deducted first.","r4":"The asset is fully depreciated to its salvage value after year 6, so depreciation expense in year 7 is zero."}}'),
('receivables-bad-debts', 'aging-analysis', '{
  "s1":{"answer":20000,"tolerance_pct":0.5,"hint":"2,000,000 × 1%.","explanation":"2,000,000 × 1% = 20,000."},
  "s2":{"answer":24000,"tolerance_pct":0.5,"hint":"600,000 × 4%.","explanation":"600,000 × 4% = 24,000."},
  "s3":{"answer":30000,"tolerance_pct":0.5,"hint":"300,000 × 10%.","explanation":"300,000 × 10% = 30,000."},
  "s4":{"answer":40000,"tolerance_pct":0.5,"hint":"100,000 × 40%.","explanation":"100,000 × 40% = 40,000."},
  "s5":{"answer":114000,"tolerance_pct":0.5,"hint":"Add the four buckets.","explanation":"20,000 + 24,000 + 30,000 + 40,000 = 114,000."},
  "s6":{"answer":79000,"tolerance_pct":0.5,"hint":"Required allowance minus the existing credit balance.","explanation":"114,000 − 35,000 = 79,000."}}'),
('receivables-bad-debts', 'which-entry', '{"i1":"adj","i2":"wo","i3":"rec","i4":"adj","i5":"wo","i6":"rec","i7":"adj","i8":"wo"}'),
('revenue-recognition', 'timing-of-revenue', '{"i1":"pit","i2":"ot","i3":"ot","i4":"pit","i5":"ot","i6":"pit"}'),
('revenue-recognition', 'allocate-price', '{
  "s1":{"answer":80000,"tolerance_pct":0.5,"hint":"60,000 + 20,000.","explanation":"60,000 + 20,000 = 80,000."},
  "s2":{"answer":54000,"tolerance_pct":0.5,"hint":"72,000 × 60/80.","explanation":"72,000 × 60 ÷ 80 = 54,000."},
  "s3":{"answer":18000,"tolerance_pct":0.5,"hint":"72,000 × 20/80.","explanation":"72,000 × 20 ÷ 80 = 18,000."},
  "s4":{"answer":9000,"tolerance_pct":0.5,"hint":"Spread the service allocation over 2 years.","explanation":"18,000 ÷ 2 = 9,000."},
  "s5":{"answer":63000,"tolerance_pct":0.5,"hint":"The laptop is recognised now; add one year of service.","explanation":"54,000 + 9,000 = 63,000."}}')
) as v(lesson, slug, key)
join public.lessons l on l.slug = v.lesson
join public.lesson_activities a on a.lesson_id = l.id and a.slug = v.slug
on conflict (activity_id) do update set key = excluded.key, updated_at = now();

-- ---------------------------------------------------------------------
-- 4. Flashcards
-- ---------------------------------------------------------------------
insert into public.flashcards (lesson_id, position, front, back)
select l.id, v.pos, v.front, v.back
from (values
('accounting-equation-journal',1,'The accounting equation','Assets = Liabilities + Equity.'),
('accounting-equation-journal',2,'Accounts that increase with a debit','Assets and expenses.'),
('accounting-equation-journal',3,'Accounts that increase with a credit','Liabilities, equity and revenue.'),
('accounting-equation-journal',4,'Double-entry rule','Every transaction has equal total debits and credits.'),
('accounting-equation-journal',5,'Owner invests cash: entry','Dr Cash / Cr Owner''s capital.'),
('accounting-equation-journal',6,'Buy supplies on credit: entry','Dr Supplies / Cr Accounts payable.'),
('accounting-equation-journal',7,'Pay rent in cash: entry','Dr Rent expense / Cr Cash.'),
('accounting-equation-journal',8,'What does a trial balance prove?','That total debits equal total credits — not that there are no errors.'),
('accounting-equation-journal',9,'What increases equity?','Revenue and owner investment.'),
('accounting-equation-journal',10,'What decreases equity?','Expenses and owner withdrawals.'),
('adjusting-entries',1,'Why make adjusting entries?','To record revenue when earned and expenses when incurred.'),
('adjusting-entries',2,'Prepaid expense','Cash paid first; an asset that becomes an expense as it is used.'),
('adjusting-entries',3,'Unearned revenue','Cash received first; a liability that becomes revenue as work is done.'),
('adjusting-entries',4,'Accrued expense: entry','Dr Expense / Cr Payable (e.g. wages payable).'),
('adjusting-entries',5,'Accrued revenue: entry','Dr Receivable / Cr Revenue.'),
('adjusting-entries',6,'Prepaid used =','Cost × months elapsed ÷ months covered.'),
('adjusting-entries',7,'Accrued interest =','Principal × annual rate × months ÷ 12.'),
('adjusting-entries',8,'Supplies expense =','Opening supplies + purchases − closing count.'),
('adjusting-entries',9,'Deferral vs accrual','Deferral: cash first, work later. Accrual: work first, cash later.'),
('adjusting-entries',10,'Effect of a missed accrued expense','Expenses and liabilities are understated; profit is overstated.'),
('inventory-cogs-methods',1,'COGS formula','Beginning inventory + purchases − ending inventory.'),
('inventory-cogs-methods',2,'FIFO','Oldest costs go to COGS first; ending inventory holds the newest costs.'),
('inventory-cogs-methods',3,'Weighted-average cost per unit','Cost of goods available ÷ units available.'),
('inventory-cogs-methods',4,'LIFO and IFRS/PFRS','Not permitted.'),
('inventory-cogs-methods',5,'Rising prices: FIFO vs average','FIFO gives lower COGS and higher profit.'),
('inventory-cogs-methods',6,'Falling prices: FIFO vs average','FIFO gives higher COGS and lower profit.'),
('inventory-cogs-methods',7,'Inventory valuation rule','Lower of cost and net realisable value.'),
('inventory-cogs-methods',8,'Overstated ending inventory effect','COGS understated, profit overstated.'),
('inventory-cogs-methods',9,'Goods available for sale','Beginning inventory + purchases (split into COGS and ending inventory).'),
('inventory-cogs-methods',10,'Net realisable value','Expected selling price minus costs to complete and sell.'),
('depreciation-ppe',1,'Depreciation is…','Allocation of cost over useful life — not market valuation.'),
('depreciation-ppe',2,'Straight-line','(Cost − Salvage) ÷ Life.'),
('depreciation-ppe',3,'Double-declining rate','2 ÷ useful life, applied to opening book value.'),
('depreciation-ppe',4,'Units of production','(Cost − Salvage) ÷ Total units × Units used.'),
('depreciation-ppe',5,'Book value','Cost − Accumulated depreciation.'),
('depreciation-ppe',6,'Which asset is not depreciated?','Land.'),
('depreciation-ppe',7,'Depreciation on the cash flow statement','Added back — it is a non-cash expense.'),
('depreciation-ppe',8,'Gain or loss on disposal','Sale proceeds − Book value.'),
('depreciation-ppe',9,'Accelerated methods','Higher expense early, lower later; same total over the life.'),
('depreciation-ppe',10,'Floor for depreciation','Never depreciate below salvage value.'),
('receivables-bad-debts',1,'Allowance method','Estimate uncollectible receivables up front to match the cost with the sales.'),
('receivables-bad-debts',2,'Adjusting entry for bad debts','Dr Bad debt expense / Cr Allowance for doubtful accounts.'),
('receivables-bad-debts',3,'Write-off entry','Dr Allowance / Cr Accounts receivable (no profit effect).'),
('receivables-bad-debts',4,'Net realisable value of receivables','Gross receivables − Allowance.'),
('receivables-bad-debts',5,'The allowance is a…','Contra-asset.'),
('receivables-bad-debts',6,'Percentage-of-sales method','Gives the expense directly: credit sales × estimated %.'),
('receivables-bad-debts',7,'Aging method','Required allowance from age buckets; expense = required − existing credit balance.'),
('receivables-bad-debts',8,'DSO =','Receivables ÷ credit sales × days in the period.'),
('receivables-bad-debts',9,'Rising DSO may signal','Slower collections or aggressive revenue recognition.'),
('receivables-bad-debts',10,'PFRS 9 impairment basis','Expected credit losses.'),
('revenue-recognition',1,'Step 1 of the model','Identify the contract with the customer.'),
('revenue-recognition',2,'Step 2','Identify the performance obligations.'),
('revenue-recognition',3,'Step 3','Determine the transaction price.'),
('revenue-recognition',4,'Step 4','Allocate the price by relative standalone selling prices.'),
('revenue-recognition',5,'Step 5','Recognise revenue when (or as) each obligation is satisfied.'),
('revenue-recognition',6,'Over-time examples','Support contracts, memberships, construction for the customer.'),
('revenue-recognition',7,'Point-in-time example','Selling a phone in a store.'),
('revenue-recognition',8,'Cash received before delivery','A contract liability (unearned revenue).'),
('revenue-recognition',9,'Variable consideration rule','Include only to the extent a significant reversal is unlikely.'),
('revenue-recognition',10,'Aggressive-recognition red flag','Revenue far ahead of cash collection; receivables ballooning.')
) as v(lesson, pos, front, back)
join public.lessons l on l.slug = v.lesson
on conflict (lesson_id, position) do update set front = excluded.front, back = excluded.back;
