-- seed_009_accounting: part 1 of 3. Run the parts in order.
-- =====================================================================
-- FINLAB — Content v9: Accounting Fundamentals certification
--   6 lessons (video + 10-question check + 2 practice activities + 10 flashcards),
--   3 case challenges, a timed final exam, the program.
-- Run AFTER seed_008. Safe to re-run.
-- =====================================================================

-- ---------------------------------------------------------------------
-- 1. Lessons
-- ---------------------------------------------------------------------
insert into public.lessons (slug, title, summary, category_id, difficulty, estimated_minutes, sort_order, related_challenge_slugs, video_urls, body) values
('accounting-equation-journal', 'The Accounting Equation & Journal Entries', 'Assets = liabilities + equity, debits and credits, and recording transactions.', 'accounting', 'beginner', 15, 20,
 '{accounting-journal-trial-balance}', '{https://www.youtube.com/watch?v=kK7mU2Udf7M}', '
## Everything starts with one equation
> **Assets = Liabilities + Equity**

Assets are what the business owns, liabilities are what it owes, and equity is the owners'' claim. **Every transaction keeps this equation in balance.**

## Double entry
Each transaction is recorded in at least two accounts, with **total debits = total credits**.

| Account type | Increases with | Normal balance |
|---|---|---|
| Assets (cash, receivables, equipment) | Debit | Debit |
| Expenses (rent, salaries) | Debit | Debit |
| Liabilities (payables, loans) | Credit | Credit |
| Equity (owner''s capital) | Credit | Credit |
| Revenue (fees, sales) | Credit | Credit |

## Examples
- **Owner invests ₱100,000 cash:** Dr Cash 100,000 / Cr Owner''s capital 100,000.
- **Buy supplies ₱5,000 on credit:** Dr Supplies 5,000 / Cr Accounts payable 5,000.
- **Pay rent ₱20,000 in cash:** Dr Rent expense 20,000 / Cr Cash 20,000.

## The trial balance
After posting, list every account''s balance. Total debits must equal total credits. A trial balance that balances does not prove there are no errors, but one that doesn''t balance proves there is one.

> Equity grows with revenue and owner investment, and shrinks with expenses and withdrawals.
'),
('adjusting-entries', 'Accruals, Deferrals & Adjusting Entries', 'Putting revenue and expenses in the right period with adjusting entries.', 'accounting', 'beginner', 15, 21,
 '{accounting-adjusting-entries-case}', '{https://www.youtube.com/watch?v=7AhGA5wJois}', '
## Why adjust?
Accrual accounting records revenue **when earned** and expenses **when incurred**, not when cash moves. Adjusting entries at period end fix the timing.

## Deferrals: cash first, work later
- **Prepaid expense** (asset → expense): rent paid for 6 months starts as *Prepaid rent*; each month move one-sixth to *Rent expense*.
- **Unearned revenue** (liability → revenue): a customer pays in advance; each month move the earned part to *Revenue*.

## Accruals: work first, cash later
- **Accrued expense**: wages earned by staff but unpaid. *Dr Wages expense / Cr Wages payable.*
- **Accrued revenue**: work done but not yet billed. *Dr Accounts receivable / Cr Revenue.*

## Quick formulas
- Prepaid used = cost × months elapsed ÷ months covered.
- Accrued interest = principal × annual rate × months ÷ 12.
- Supplies expense = opening supplies + purchases − closing count.

> Skipping an adjustment misstates profit **and** the balance sheet: an unrecorded accrued expense understates both expenses and liabilities.
'),
('inventory-cogs-methods', 'Inventory & Cost of Goods Sold', 'COGS, FIFO, weighted average, and what each method does to profit.', 'accounting', 'intermediate', 15, 22,
 '{accounting-inventory-depreciation-case}', '{https://www.youtube.com/watch?v=pGrm501rYWg}', '
## The COGS formula
> **COGS = Beginning inventory + Purchases − Ending inventory**

Goods available for sale are split between **COGS** (income statement) and **ending inventory** (balance sheet). The two always add up to the same total — the method decides how.

## FIFO (first in, first out)
The oldest costs are expensed first; ending inventory carries the **most recent** costs.

## Weighted average
Average unit cost = **cost of goods available ÷ units available**. Apply it to units sold and units left.

## LIFO
Latest costs expensed first. **Not permitted under IFRS/PFRS.**

## What happens when prices rise?
- **FIFO:** lower COGS, higher profit, higher ending inventory.
- **Weighted average:** in between.
- When prices fall, the effects reverse.

## Valuation rule
Inventory is reported at the **lower of cost and net realisable value (NRV)**.

> An overstated ending inventory understates COGS and overstates profit — a classic manipulation to watch for.
'),
('depreciation-ppe', 'Depreciation & Fixed Assets', 'Straight-line, double-declining and units of production.', 'accounting', 'intermediate', 15, 23,
 '{accounting-inventory-depreciation-case}', '{https://www.youtube.com/watch?v=yYQRiYixoSY}', '
## What depreciation is
Depreciation **allocates an asset''s cost over its useful life**. It is not a measure of market value and it is **non-cash**.

## Methods
- **Straight-line:** (Cost − Salvage) ÷ Life. Equal expense each year.
- **Double-declining balance:** rate = 2 ÷ life, applied to **opening book value** (salvage ignored until the end). Expense is highest early.
- **Units of production:** (Cost − Salvage) ÷ Total units × Units used.

**Book value** = Cost − Accumulated depreciation. Never depreciate below salvage value. **Land is not depreciated.**

## On the statements
- Income statement: depreciation expense reduces profit.
- Balance sheet: accumulated depreciation reduces the asset''s carrying amount.
- Cash flow: **added back** in operating cash flow because it is non-cash.

## Disposal
Gain or loss = Sale proceeds − Book value.

> Accelerated methods lower profit early and raise it later. Total depreciation over the asset''s life is the same.
'),
('receivables-bad-debts', 'Receivables & Bad Debts', 'The allowance method, aging analysis and what rising DSO tells you.', 'accounting', 'intermediate', 15, 24,
 '{accounting-adjusting-entries-case}', '{https://www.youtube.com/watch?v=5f9XNo7whtY}', '
## Some customers won''t pay
The **allowance method** estimates uncollectible receivables up front, matching the cost with the sales that created it.

- **Adjusting entry:** Dr Bad debt expense / Cr Allowance for doubtful accounts.
- **Write-off of a specific account:** Dr Allowance / Cr Accounts receivable. *Net receivables and profit don''t change.*
- **Net realisable value** = Gross receivables − Allowance. The allowance is a **contra-asset**.

## Two ways to estimate
1. **Percentage of credit sales** → this *is* the expense for the year.
2. **Aging of receivables** → each age bucket gets a loss rate; the total is the **required allowance**. Expense = required allowance − existing credit balance.

## Analyst check
**DSO = Receivables ÷ Credit sales × days in period.** Rising DSO can mean slower collections or aggressive revenue recognition.

> PFRS 9 requires **expected** credit losses, not only incurred ones.
'),
('revenue-recognition', 'Revenue Recognition (PFRS 15)', 'The five-step model: contracts, obligations, price allocation and timing.', 'accounting', 'advanced', 15, 25,
 '{accounting-adjusting-entries-case}', '{https://www.youtube.com/watch?v=E-cBZ_BR7_0}', '
## The five steps
1. **Identify the contract** with the customer.
2. **Identify the performance obligations** (distinct goods or services).
3. **Determine the transaction price.**
4. **Allocate** the price to each obligation by relative standalone selling price (SSP).
5. **Recognise revenue** when (or as) each obligation is satisfied.

## Point in time vs over time
- **Point in time:** control passes at delivery (selling a phone).
- **Over time:** the customer receives benefit as you perform (support contracts, memberships, construction for the customer).

## Allocation example
Bundle price ₱36,000; SSPs: phone ₱30,000 and service ₱10,000. Phone = 36,000 × 30/40 = **₱27,000**; service = **₱9,000**, recognised over the service period.

## Related balance sheet items
Cash received before delivery creates a **contract liability** (unearned revenue). Variable consideration (rebates, bonuses) is included only to the extent a significant reversal is unlikely.

> Red flag for analysts: revenue growth far ahead of cash collection and rising receivables.
')
on conflict (slug) do nothing;

-- ---------------------------------------------------------------------
-- 2. Knowledge checks (10 questions each)
-- ---------------------------------------------------------------------
with qs(slug, questions, answers) as (values
('accounting-equation-journal',
 convert_from(decode('W3siaWQiOiJxMSIsInR5cGUiOiJtY3EiLCJsYWJlbCI6IlRoZSBlcXVhdGlvbiIsInByb21wdCI6IlRoZSBhY2NvdW50aW5nIGVxdWF0aW9uIGlz4oCmIiwib3B0aW9ucyI6W3siaWQiOiJhIiwibGFiZWwiOiJBc3NldHMgPSBMaWFiaWxpdGllcyArIEVxdWl0eSJ9LHsiaWQiOiJiIiwibGFiZWwiOiJBc3NldHMgPSBMaWFiaWxpdGllcyDiiJIgRXF1aXR5In0seyJpZCI6ImMiLCJsYWJlbCI6IkVxdWl0eSA9IEFzc2V0cyArIExpYWJpbGl0aWVzIn0seyJpZCI6ImQiLCJsYWJlbCI6IlJldmVudWUgPSBBc3NldHMg4oiSIEV4cGVuc2VzIn1dLCJwb2ludHMiOjEwfSwKICAgICB7ImlkIjoicTIiLCJ0eXBlIjoibnVtZXJpYyIsImxhYmVsIjoiRXF1aXR5IiwicHJvbXB0IjoiQXNzZXRzIOKCsTkwMGssIGxpYWJpbGl0aWVzIOKCsTM1MGsuIEVxdWl0eSAo4oKxayk/IiwidW5pdCI6IuKCsWsiLCJwb2ludHMiOjEwfSwKICAgICB7ImlkIjoicTMiLCJ0eXBlIjoibWNxIiwibGFiZWwiOiJPd25lciBpbnZlc3RtZW50IiwicHJvbXB0IjoiVGhlIG93bmVyIGludmVzdHMg4oKxMTAwLDAwMCBjYXNoLiBUaGUgZW50cnkgaXPigKYiLCJvcHRpb25zIjpbeyJpZCI6ImEiLCJsYWJlbCI6IkRyIE93bmVyJ3MgY2FwaXRhbCAvIENyIENhc2gifSx7ImlkIjoiYiIsImxhYmVsIjoiRHIgQ2FzaCAvIENyIE93bmVyJ3MgY2FwaXRhbCJ9LHsiaWQiOiJjIiwibGFiZWwiOiJEciBDYXNoIC8gQ3IgUmV2ZW51ZSJ9LHsiaWQiOiJkIiwibGFiZWwiOiJEciBFcXVpcG1lbnQgLyBDciBDYXNoIn1dLCJwb2ludHMiOjEwfSwKICAgICB7ImlkIjoicTQiLCJ0eXBlIjoibWNxIiwibGFiZWwiOiJDcmVkaXRzIiwicHJvbXB0IjoiV2hpY2ggYWNjb3VudCBpbmNyZWFzZXMgd2l0aCBhIGNyZWRpdD8iLCJvcHRpb25zIjpbeyJpZCI6ImEiLCJsYWJlbCI6IkNhc2gifSx7ImlkIjoiYiIsImxhYmVsIjoiUmVudCBleHBlbnNlIn0seyJpZCI6ImMiLCJsYWJlbCI6IlNlcnZpY2UgcmV2ZW51ZSJ9LHsiaWQiOiJkIiwibGFiZWwiOiJFcXVpcG1lbnQifV0sInBvaW50cyI6MTB9LAogICAgIHsiaWQiOiJxNSIsInR5cGUiOiJtY3EiLCJsYWJlbCI6IlN1cHBsaWVzIG9uIGNyZWRpdCIsInByb21wdCI6IkJ1eWluZyBzdXBwbGllcyBvbiBjcmVkaXTigKYiLCJvcHRpb25zIjpbeyJpZCI6ImEiLCJsYWJlbCI6IkluY3JlYXNlcyBhc3NldHMgYW5kIGxpYWJpbGl0aWVzIn0seyJpZCI6ImIiLCJsYWJlbCI6IkluY3JlYXNlcyBhc3NldHMgYW5kIGVxdWl0eSJ9LHsiaWQiOiJjIiwibGFiZWwiOiJEZWNyZWFzZXMgYXNzZXRzIGFuZCBsaWFiaWxpdGllcyJ9LHsiaWQiOiJkIiwibGFiZWwiOiJIYXMgbm8gZWZmZWN0IG9uIHRoZSBlcXVhdGlvbiJ9XSwicG9pbnRzIjoxMH0sCiAgICAgeyJpZCI6InE2IiwidHlwZSI6Im51bWVyaWMiLCJsYWJlbCI6IlRyaWFsIGJhbGFuY2UiLCJwcm9tcHQiOiJEZWJpdHM6IGNhc2gg4oKxMzAwaywgZXF1aXBtZW50IOKCsTUwMGssIHJlbnQg4oKxMTAway4gQ3JlZGl0czogcGF5YWJsZXMg4oKxMjAwaywgY2FwaXRhbCDigrE0NTBrLCBhbmQgcmV2ZW51ZS4gUmV2ZW51ZSAo4oKxaykgc28gdGhlIHRyaWFsIGJhbGFuY2UgYmFsYW5jZXM/IiwidW5pdCI6IuKCsWsiLCJwb2ludHMiOjEwfSwKICAgICB7ImlkIjoicTciLCJ0eXBlIjoibWNxIiwibGFiZWwiOiJQYXlpbmcgcmVudCIsInByb21wdCI6IlBheWluZyB0aGlzIG1vbnRoJ3MgcmVudCBvZiDigrEyMCwwMDAgaW4gY2FzaOKApiIsIm9wdGlvbnMiOlt7ImlkIjoiYSIsImxhYmVsIjoiRHIgQ2FzaCAvIENyIFJlbnQgZXhwZW5zZSJ9LHsiaWQiOiJiIiwibGFiZWwiOiJEciBSZW50IGV4cGVuc2UgLyBDciBDYXNoIn0seyJpZCI6ImMiLCJsYWJlbCI6IkRyIFJlbnQgZXhwZW5zZSAvIENyIEFjY291bnRzIHBheWFibGUifSx7ImlkIjoiZCIsImxhYmVsIjoiRHIgUHJlcGFpZCByZW50IC8gQ3IgUmV2ZW51ZSJ9XSwicG9pbnRzIjoxMH0sCiAgICAgeyJpZCI6InE4IiwidHlwZSI6Im51bWVyaWMiLCJsYWJlbCI6IkVxdWl0eSBjaGFuZ2VzIiwicHJvbXB0IjoiRXF1aXR5IHN0YXJ0cyBhdCDigrEzMDAuIFRoZSBidXNpbmVzcyBlYXJucyDigrE4MCByZXZlbnVlIGluIGNhc2ggYW5kIHBheXMg4oKxMzAgb2YgZXhwZW5zZXMgaW4gY2FzaC4gRW5kaW5nIGVxdWl0eSAo4oKxKT8iLCJ1bml0Ijoi4oKxIiwicG9pbnRzIjoxMH0sCiAgICAgeyJpZCI6InE5IiwidHlwZSI6Im1jcSIsImxhYmVsIjoiTm9ybWFsIGJhbGFuY2UiLCJwcm9tcHQiOiJUaGUgbm9ybWFsIGJhbGFuY2Ugb2YgQWNjb3VudHMgUGF5YWJsZSBpc+KApiIsIm9wdGlvbnMiOlt7ImlkIjoiYSIsImxhYmVsIjoiRGViaXQifSx7ImlkIjoiYiIsImxhYmVsIjoiQ3JlZGl0In0seyJpZCI6ImMiLCJsYWJlbCI6IkVpdGhlciJ9LHsiaWQiOiJkIiwibGFiZWwiOiJaZXJvIn1dLCJwb2ludHMiOjEwfSwKICAgICB7ImlkIjoicTEwIiwidHlwZSI6Im1jcSIsImxhYmVsIjoiRG91YmxlIGVudHJ5IiwicHJvbXB0IjoiRG91YmxlLWVudHJ5IGJvb2trZWVwaW5nIG1lYW5z4oCmIiwib3B0aW9ucyI6W3siaWQiOiJhIiwibGFiZWwiOiJFdmVyeSB0cmFuc2FjdGlvbiBpcyByZWNvcmRlZCB0d2ljZSBpbiB0aGUgc2FtZSBhY2NvdW50In0seyJpZCI6ImIiLCJsYWJlbCI6IkV2ZXJ5IHRyYW5zYWN0aW9uIGhhcyBlcXVhbCB0b3RhbCBkZWJpdHMgYW5kIGNyZWRpdHMifSx7ImlkIjoiYyIsImxhYmVsIjoiRXZlcnkgYWNjb3VudCBoYXMgYSBkZWJpdCBhbmQgYSBjcmVkaXQgYmFsYW5jZSJ9LHsiaWQiOiJkIiwibGFiZWwiOiJUd28gcGVvcGxlIG11c3QgYXBwcm92ZSBlYWNoIGVudHJ5In1dLCJwb2ludHMiOjEwfV0=', 'base64'), 'UTF8')::jsonb,
 convert_from(decode('eyJxMSI6eyJhbnN3ZXIiOiJhIn0sInEyIjp7ImFuc3dlciI6NTUwLCJ0b2xlcmFuY2VfcGN0IjowLjV9LCJxMyI6eyJhbnN3ZXIiOiJiIn0sInE0Ijp7ImFuc3dlciI6ImMifSwicTUiOnsiYW5zd2VyIjoiYSJ9LCJxNiI6eyJhbnN3ZXIiOjI1MCwidG9sZXJhbmNlX3BjdCI6MC41fSwicTciOnsiYW5zd2VyIjoiYiJ9LCJxOCI6eyJhbnN3ZXIiOjM1MCwidG9sZXJhbmNlX3BjdCI6MC41fSwicTkiOnsiYW5zd2VyIjoiYiJ9LCJxMTAiOnsiYW5zd2VyIjoiYiJ9fQ==', 'base64'), 'UTF8')::jsonb),
('adjusting-entries',
 convert_from(decode('W3siaWQiOiJxMSIsInR5cGUiOiJtY3EiLCJsYWJlbCI6IlB1cnBvc2UiLCJwcm9tcHQiOiJBZGp1c3RpbmcgZW50cmllcyBleGlzdCB0b+KApiIsIm9wdGlvbnMiOlt7ImlkIjoiYSIsImxhYmVsIjoiUmVjb3JkIHJldmVudWUgYW5kIGV4cGVuc2VzIGluIHRoZSBwZXJpb2QgdGhleSBhcmUgZWFybmVkIG9yIGluY3VycmVkIn0seyJpZCI6ImIiLCJsYWJlbCI6IkNvcnJlY3QgYmFuayBlcnJvcnMifSx7ImlkIjoiYyIsImxhYmVsIjoiQ2xvc2UgdGhlIGJvb2tzIn0seyJpZCI6ImQiLCJsYWJlbCI6IlJlY29yZCBvd25lciB3aXRoZHJhd2FscyJ9XSwicG9pbnRzIjoxMH0sCiAgICAgeyJpZCI6InEyIiwidHlwZSI6Im51bWVyaWMiLCJsYWJlbCI6IlByZXBhaWQgaW5zdXJhbmNlIiwicHJvbXB0Ijoi4oKxMjQsMDAwIG9mIGluc3VyYW5jZSB3YXMgcGFpZCBvbiAxIEphbiBmb3IgMTIgbW9udGhzLiBJbnN1cmFuY2UgZXhwZW5zZSBmb3IgSmFudWFyeeKAk01hcmNoICjigrEpPyIsInVuaXQiOiLigrEiLCJwb2ludHMiOjEwfSwKICAgICB7ImlkIjoicTMiLCJ0eXBlIjoibWNxIiwibGFiZWwiOiJBY2NydWVkIHdhZ2VzIiwicHJvbXB0IjoiV2FnZXMgYXJlIGVhcm5lZCBidXQgdW5wYWlkIGF0IHBlcmlvZCBlbmQuIFRoZSBhZGp1c3RtZW50IGlz4oCmIiwib3B0aW9ucyI6W3siaWQiOiJhIiwibGFiZWwiOiJEciBXYWdlcyBwYXlhYmxlIC8gQ3IgV2FnZXMgZXhwZW5zZSJ9LHsiaWQiOiJiIiwibGFiZWwiOiJEciBXYWdlcyBleHBlbnNlIC8gQ3IgV2FnZXMgcGF5YWJsZSJ9LHsiaWQiOiJjIiwibGFiZWwiOiJEciBDYXNoIC8gQ3IgV2FnZXMgZXhwZW5zZSJ9LHsiaWQiOiJkIiwibGFiZWwiOiJObyBlbnRyeSB1bnRpbCBwYWlkIn1dLCJwb2ludHMiOjEwfSwKICAgICB7ImlkIjoicTQiLCJ0eXBlIjoibnVtZXJpYyIsImxhYmVsIjoiVW5lYXJuZWQgcmV2ZW51ZSIsInByb21wdCI6IkEgY3VzdG9tZXIgcGF5cyDigrE2MCwwMDAgb24gMSBPY3QgZm9yIDEyIG1vbnRocyBvZiBzZXJ2aWNlLiBSZXZlbnVlIGVhcm5lZCBieSAzMSBEZWMgKOKCsSk/IiwidW5pdCI6IuKCsSIsInBvaW50cyI6MTB9LAogICAgIHsiaWQiOiJxNSIsInR5cGUiOiJtY3EiLCJsYWJlbCI6IkNsYXNzaWZpY2F0aW9uIiwicHJvbXB0IjoiVW5lYXJuZWQgcmV2ZW51ZSBpcyByZXBvcnRlZCBhc+KApiIsIm9wdGlvbnMiOlt7ImlkIjoiYSIsImxhYmVsIjoiQW4gYXNzZXQifSx7ImlkIjoiYiIsImxhYmVsIjoiQSBsaWFiaWxpdHkifSx7ImlkIjoiYyIsImxhYmVsIjoiRXF1aXR5In0seyJpZCI6ImQiLCJsYWJlbCI6IkFuIGV4cGVuc2UifV0sInBvaW50cyI6MTB9LAogICAgIHsiaWQiOiJxNiIsInR5cGUiOiJtY3EiLCJsYWJlbCI6IkFjY3J1ZWQgcmV2ZW51ZSIsInByb21wdCI6IlNlcnZpY2VzIHdlcmUgcGVyZm9ybWVkIGJ1dCBub3QgeWV0IGJpbGxlZC4gVGhlIGFkanVzdG1lbnQgaXPigKYiLCJvcHRpb25zIjpbeyJpZCI6ImEiLCJsYWJlbCI6IkRyIEFjY291bnRzIHJlY2VpdmFibGUgLyBDciBSZXZlbnVlIn0seyJpZCI6ImIiLCJsYWJlbCI6IkRyIFJldmVudWUgLyBDciBBY2NvdW50cyByZWNlaXZhYmxlIn0seyJpZCI6ImMiLCJsYWJlbCI6IkRyIENhc2ggLyBDciBVbmVhcm5lZCByZXZlbnVlIn0seyJpZCI6ImQiLCJsYWJlbCI6IkRyIEV4cGVuc2UgLyBDciBQYXlhYmxlIn1dLCJwb2ludHMiOjEwfSwKICAgICB7ImlkIjoicTciLCJ0eXBlIjoibnVtZXJpYyIsImxhYmVsIjoiU3VwcGxpZXMiLCJwcm9tcHQiOiJPcGVuaW5nIHN1cHBsaWVzIOKCsTgsMDAwLCBwdXJjaGFzZXMg4oKxNSwwMDAsIGNsb3NpbmcgY291bnQg4oKxNiw1MDAuIFN1cHBsaWVzIGV4cGVuc2UgKOKCsSk/IiwidW5pdCI6IuKCsSIsInBvaW50cyI6MTB9LAogICAgIHsiaWQiOiJxOCIsInR5cGUiOiJtY3EiLCJsYWJlbCI6Ik9taXR0ZWQgYWNjcnVhbCIsInByb21wdCI6IkZhaWxpbmcgdG8gcmVjb3JkIGFuIGFjY3J1ZWQgZXhwZW5zZeKApiIsIm9wdGlvbnMiOlt7ImlkIjoiYSIsImxhYmVsIjoiT3ZlcnN0YXRlcyBleHBlbnNlcyBhbmQgbGlhYmlsaXRpZXMifSx7ImlkIjoiYiIsImxhYmVsIjoiVW5kZXJzdGF0ZXMgZXhwZW5zZXMgYW5kIGxpYWJpbGl0aWVzIn0seyJpZCI6ImMiLCJsYWJlbCI6Ik92ZXJzdGF0ZXMgYXNzZXRzIn0seyJpZCI6ImQiLCJsYWJlbCI6IkhhcyBubyBlZmZlY3Qgb24gdGhlIHN0YXRlbWVudHMifV0sInBvaW50cyI6MTB9LAogICAgIHsiaWQiOiJxOSIsInR5cGUiOiJudW1lcmljIiwibGFiZWwiOiJBY2NydWVkIGludGVyZXN0IiwicHJvbXB0IjoiQSDigrE1MDAsMDAwIGxvYW4gYXQgMTIlIGEgeWVhciB3YXMgdGFrZW4gb24gMSBOb3YuIEludGVyZXN0IGFjY3J1ZWQgYnkgMzEgRGVjICjigrEpPyIsInVuaXQiOiLigrEiLCJwb2ludHMiOjEwfSwKICAgICB7ImlkIjoicTEwIiwidHlwZSI6Im1jcSIsImxhYmVsIjoiRGVmZXJyYWwiLCJwcm9tcHQiOiJXaGljaCBpcyBhIGRlZmVycmFsPyIsIm9wdGlvbnMiOlt7ImlkIjoiYSIsImxhYmVsIjoiQWNjcnVlZCB3YWdlcyJ9LHsiaWQiOiJiIiwibGFiZWwiOiJQcmVwYWlkIHJlbnQifSx7ImlkIjoiYyIsImxhYmVsIjoiSW50ZXJlc3QgZWFybmVkIGJ1dCBub3QgcmVjZWl2ZWQifSx7ImlkIjoiZCIsImxhYmVsIjoiVW5iaWxsZWQgY29uc3VsdGluZyB3b3JrIn1dLCJwb2ludHMiOjEwfV0=', 'base64'), 'UTF8')::jsonb,
 convert_from(decode('eyJxMSI6eyJhbnN3ZXIiOiJhIn0sInEyIjp7ImFuc3dlciI6NjAwMCwidG9sZXJhbmNlX3BjdCI6MC41fSwicTMiOnsiYW5zd2VyIjoiYiJ9LCJxNCI6eyJhbnN3ZXIiOjE1MDAwLCJ0b2xlcmFuY2VfcGN0IjowLjV9LCJxNSI6eyJhbnN3ZXIiOiJiIn0sInE2Ijp7ImFuc3dlciI6ImEifSwicTciOnsiYW5zd2VyIjo2NTAwLCJ0b2xlcmFuY2VfcGN0IjowLjV9LCJxOCI6eyJhbnN3ZXIiOiJiIn0sInE5Ijp7ImFuc3dlciI6MTAwMDAsInRvbGVyYW5jZV9wY3QiOjAuNX0sInExMCI6eyJhbnN3ZXIiOiJiIn19', 'base64'), 'UTF8')::jsonb),
('inventory-cogs-methods',
 convert_from(decode('W3siaWQiOiJxMSIsInR5cGUiOiJudW1lcmljIiwibGFiZWwiOiJDT0dTIiwicHJvbXB0IjoiQmVnaW5uaW5nIGludmVudG9yeSDigrEyMDBrLCBwdXJjaGFzZXMg4oKxOTAwaywgZW5kaW5nIGludmVudG9yeSDigrEyNTBrLiBDT0dTICjigrFrKT8iLCJ1bml0Ijoi4oKxayIsInBvaW50cyI6MTB9LAogICAgIHsiaWQiOiJxMiIsInR5cGUiOiJtY3EiLCJsYWJlbCI6IkZJRk8iLCJwcm9tcHQiOiJGSUZPIGFzc3VtZXPigKYiLCJvcHRpb25zIjpbeyJpZCI6ImEiLCJsYWJlbCI6IlRoZSBuZXdlc3QgdW5pdHMgYXJlIHNvbGQgZmlyc3QifSx7ImlkIjoiYiIsImxhYmVsIjoiVGhlIG9sZGVzdCB1bml0cyBhcmUgc29sZCBmaXJzdCJ9LHsiaWQiOiJjIiwibGFiZWwiOiJVbml0cyBhcmUgc29sZCBhdCB0aGUgYXZlcmFnZSBjb3N0IG9mIHB1cmNoYXNlcyBvbmx5In0seyJpZCI6ImQiLCJsYWJlbCI6IkludmVudG9yeSBuZXZlciBjaGFuZ2VzIGluIGNvc3QifV0sInBvaW50cyI6MTB9LAogICAgIHsiaWQiOiJxMyIsInR5cGUiOiJudW1lcmljIiwibGFiZWwiOiJBdmVyYWdlIGNvc3QiLCJwcm9tcHQiOiIxMDAgdW5pdHMgYXQg4oKxMTAgYW5kIDIwMCB1bml0cyBhdCDigrExMyBhcmUgYXZhaWxhYmxlLiBXZWlnaHRlZC1hdmVyYWdlIGNvc3QgcGVyIHVuaXQgKOKCsSk/IiwidW5pdCI6IuKCsSIsInBvaW50cyI6MTB9LAogICAgIHsiaWQiOiJxNCIsInR5cGUiOiJudW1lcmljIiwibGFiZWwiOiJBdmVyYWdlIENPR1MiLCJwcm9tcHQiOiJVc2luZyB0aGF0IGF2ZXJhZ2UgY29zdCwgMTIwIHVuaXRzIGFyZSBzb2xkLiBDT0dTICjigrEpPyIsInVuaXQiOiLigrEiLCJwb2ludHMiOjEwfSwKICAgICB7ImlkIjoicTUiLCJ0eXBlIjoibWNxIiwibGFiZWwiOiJSaXNpbmcgcHJpY2VzIiwicHJvbXB0IjoiV2hlbiBwcmljZXMgYXJlIHJpc2luZywgY29tcGFyZWQgd2l0aCB3ZWlnaHRlZCBhdmVyYWdlLCBGSUZPIGdpdmVz4oCmIiwib3B0aW9ucyI6W3siaWQiOiJhIiwibGFiZWwiOiJIaWdoZXIgQ09HUyBhbmQgbG93ZXIgcHJvZml0In0seyJpZCI6ImIiLCJsYWJlbCI6Ikxvd2VyIENPR1MgYW5kIGhpZ2hlciBwcm9maXQifSx7ImlkIjoiYyIsImxhYmVsIjoiVGhlIHNhbWUgcHJvZml0In0seyJpZCI6ImQiLCJsYWJlbCI6Ikxvd2VyIGVuZGluZyBpbnZlbnRvcnkifV0sInBvaW50cyI6MTB9LAogICAgIHsiaWQiOiJxNiIsInR5cGUiOiJtY3EiLCJsYWJlbCI6IlN0YW5kYXJkcyIsInByb21wdCI6IldoaWNoIG1ldGhvZCBpcyBub3QgcGVybWl0dGVkIHVuZGVyIElGUlMvUEZSUz8iLCJvcHRpb25zIjpbeyJpZCI6ImEiLCJsYWJlbCI6IkZJRk8ifSx7ImlkIjoiYiIsImxhYmVsIjoiV2VpZ2h0ZWQgYXZlcmFnZSJ9LHsiaWQiOiJjIiwibGFiZWwiOiJMSUZPIn0seyJpZCI6ImQiLCJsYWJlbCI6IlNwZWNpZmljIGlkZW50aWZpY2F0aW9uIn1dLCJwb2ludHMiOjEwfSwKICAgICB7ImlkIjoicTciLCJ0eXBlIjoibnVtZXJpYyIsImxhYmVsIjoiRklGTyBDT0dTIiwicHJvbXB0IjoiMTAwIHVuaXRzIGF0IOKCsTEwIHRoZW4gMTAwIHVuaXRzIGF0IOKCsTEyIGFyZSBib3VnaHQuIFNlbGxpbmcgMTUwIHVuaXRzIHVuZGVyIEZJRk8gZ2l2ZXMgQ09HUyBvZiAo4oKxKT8iLCJ1bml0Ijoi4oKxIiwicG9pbnRzIjoxMH0sCiAgICAgeyJpZCI6InE4IiwidHlwZSI6Im51bWVyaWMiLCJsYWJlbCI6IkZJRk8gZW5kaW5nIGludmVudG9yeSIsInByb21wdCI6IlNhbWUgZmFjdHM6IEZJRk8gZW5kaW5nIGludmVudG9yeSBvZiB0aGUgcmVtYWluaW5nIDUwIHVuaXRzICjigrEpPyIsInVuaXQiOiLigrEiLCJwb2ludHMiOjEwfSwKICAgICB7ImlkIjoicTkiLCJ0eXBlIjoibWNxIiwibGFiZWwiOiJWYWx1YXRpb24iLCJwcm9tcHQiOiJJbnZlbnRvcnkgaXMgcmVwb3J0ZWQgYXTigKYiLCJvcHRpb25zIjpbeyJpZCI6ImEiLCJsYWJlbCI6IlNlbGxpbmcgcHJpY2UifSx7ImlkIjoiYiIsImxhYmVsIjoiVGhlIGxvd2VyIG9mIGNvc3QgYW5kIG5ldCByZWFsaXNhYmxlIHZhbHVlIn0seyJpZCI6ImMiLCJsYWJlbCI6IlRoZSBoaWdoZXIgb2YgY29zdCBhbmQgbWFya2V0In0seyJpZCI6ImQiLCJsYWJlbCI6IlJlcGxhY2VtZW50IGNvc3Qgb25seSJ9XSwicG9pbnRzIjoxMH0sCiAgICAgeyJpZCI6InExMCIsInR5cGUiOiJtY3EiLCJsYWJlbCI6Ik92ZXJzdGF0ZWQgaW52ZW50b3J5IiwicHJvbXB0IjoiSWYgZW5kaW5nIGludmVudG9yeSBpcyBvdmVyc3RhdGVk4oCmIiwib3B0aW9ucyI6W3siaWQiOiJhIiwibGFiZWwiOiJDT0dTIGlzIG92ZXJzdGF0ZWQgYW5kIHByb2ZpdCB1bmRlcnN0YXRlZCJ9LHsiaWQiOiJiIiwibGFiZWwiOiJDT0dTIGlzIHVuZGVyc3RhdGVkIGFuZCBwcm9maXQgb3ZlcnN0YXRlZCJ9LHsiaWQiOiJjIiwibGFiZWwiOiJPbmx5IHRoZSBiYWxhbmNlIHNoZWV0IGlzIGFmZmVjdGVkIn0seyJpZCI6ImQiLCJsYWJlbCI6Ik5vdGhpbmcgY2hhbmdlcyJ9XSwicG9pbnRzIjoxMH1d', 'base64'), 'UTF8')::jsonb,
 convert_from(decode('eyJxMSI6eyJhbnN3ZXIiOjg1MCwidG9sZXJhbmNlX3BjdCI6MC41fSwicTIiOnsiYW5zd2VyIjoiYiJ9LCJxMyI6eyJhbnN3ZXIiOjEyLCJ0b2xlcmFuY2VfcGN0IjowLjV9LCJxNCI6eyJhbnN3ZXIiOjE0NDAsInRvbGVyYW5jZV9wY3QiOjAuNX0sInE1Ijp7ImFuc3dlciI6ImIifSwicTYiOnsiYW5zd2VyIjoiYyJ9LCJxNyI6eyJhbnN3ZXIiOjE2MDAsInRvbGVyYW5jZV9wY3QiOjAuNX0sInE4Ijp7ImFuc3dlciI6NjAwLCJ0b2xlcmFuY2VfcGN0IjowLjV9LCJxOSI6eyJhbnN3ZXIiOiJiIn0sInExMCI6eyJhbnN3ZXIiOiJiIn19', 'base64'), 'UTF8')::jsonb),
('depreciation-ppe',
 convert_from(decode('W3siaWQiOiJxMSIsInR5cGUiOiJudW1lcmljIiwibGFiZWwiOiJTdHJhaWdodC1saW5lIiwicHJvbXB0IjoiQSBtYWNoaW5lIGNvc3RzIOKCsTUwMCwwMDAsIHNhbHZhZ2Ug4oKxNTAsMDAwLCBsaWZlIDUgeWVhcnMuIFN0cmFpZ2h0LWxpbmUgZGVwcmVjaWF0aW9uIHBlciB5ZWFyICjigrEpPyIsInVuaXQiOiLigrEiLCJwb2ludHMiOjEwfSwKICAgICB7ImlkIjoicTIiLCJ0eXBlIjoibnVtZXJpYyIsImxhYmVsIjoiQm9vayB2YWx1ZSIsInByb21wdCI6IlNhbWUgbWFjaGluZTogYm9vayB2YWx1ZSBhZnRlciAyIHllYXJzIG9mIHN0cmFpZ2h0LWxpbmUgKOKCsSk/IiwidW5pdCI6IuKCsSIsInBvaW50cyI6MTB9LAogICAgIHsiaWQiOiJxMyIsInR5cGUiOiJudW1lcmljIiwibGFiZWwiOiJEREIgeWVhciAxIiwicHJvbXB0IjoiU2FtZSBtYWNoaW5lIHVuZGVyIGRvdWJsZS1kZWNsaW5pbmcgYmFsYW5jZSAocmF0ZSA0MCUpLiBZZWFyLTEgZGVwcmVjaWF0aW9uICjigrEpPyIsInVuaXQiOiLigrEiLCJwb2ludHMiOjEwfSwKICAgICB7ImlkIjoicTQiLCJ0eXBlIjoibnVtZXJpYyIsImxhYmVsIjoiRERCIHllYXIgMiIsInByb21wdCI6IlllYXItMiBkZXByZWNpYXRpb24gdW5kZXIgZG91YmxlLWRlY2xpbmluZyBiYWxhbmNlICjigrEpPyIsInVuaXQiOiLigrEiLCJwb2ludHMiOjEwfSwKICAgICB7ImlkIjoicTUiLCJ0eXBlIjoibWNxIiwibGFiZWwiOiJNZWFuaW5nIiwicHJvbXB0IjoiRGVwcmVjaWF0aW9uIGlz4oCmIiwib3B0aW9ucyI6W3siaWQiOiJhIiwibGFiZWwiOiJBIHdheSB0byB0cmFjayB0aGUgYXNzZXQncyBtYXJrZXQgdmFsdWUifSx7ImlkIjoiYiIsImxhYmVsIjoiVGhlIGFsbG9jYXRpb24gb2YgY29zdCBvdmVyIHRoZSBhc3NldCdzIHVzZWZ1bCBsaWZlIn0seyJpZCI6ImMiLCJsYWJlbCI6IkEgY2FzaCBwYXltZW50IHRvIGEgcmVzZXJ2ZSBmdW5kIn0seyJpZCI6ImQiLCJsYWJlbCI6IkEgdGF4IHBheW1lbnQifV0sInBvaW50cyI6MTB9LAogICAgIHsiaWQiOiJxNiIsInR5cGUiOiJtY3EiLCJsYWJlbCI6IkNhc2ggZmxvdyIsInByb21wdCI6Ik9uIHRoZSBjYXNoIGZsb3cgc3RhdGVtZW50LCBkZXByZWNpYXRpb24gaXPigKYiLCJvcHRpb25zIjpbeyJpZCI6ImEiLCJsYWJlbCI6IlN1YnRyYWN0ZWQgYXMgYSBjYXNoIG91dGZsb3cifSx7ImlkIjoiYiIsImxhYmVsIjoiQWRkZWQgYmFjayB0byBuZXQgaW5jb21lIGFzIGEgbm9uLWNhc2ggZXhwZW5zZSJ9LHsiaWQiOiJjIiwibGFiZWwiOiJTaG93biB1bmRlciBmaW5hbmNpbmcifSx7ImlkIjoiZCIsImxhYmVsIjoiSWdub3JlZCJ9XSwicG9pbnRzIjoxMH0sCiAgICAgeyJpZCI6InE3IiwidHlwZSI6Im1jcSIsImxhYmVsIjoiTm90IGRlcHJlY2lhdGVkIiwicHJvbXB0IjoiV2hpY2ggYXNzZXQgaXMgbm90IGRlcHJlY2lhdGVkPyIsIm9wdGlvbnMiOlt7ImlkIjoiYSIsImxhYmVsIjoiRGVsaXZlcnkgdmFuIn0seyJpZCI6ImIiLCJsYWJlbCI6Ik9mZmljZSBjb21wdXRlcnMifSx7ImlkIjoiYyIsImxhYmVsIjoiTGFuZCJ9LHsiaWQiOiJkIiwibGFiZWwiOiJGYWN0b3J5IG1hY2hpbmVyeSJ9XSwicG9pbnRzIjoxMH0sCiAgICAgeyJpZCI6InE4IiwidHlwZSI6Im51bWVyaWMiLCJsYWJlbCI6IkRpc3Bvc2FsIiwicHJvbXB0IjoiQW4gYXNzZXQgd2l0aCBib29rIHZhbHVlIOKCsTEwMCwwMDAgaXMgc29sZCBmb3Ig4oKxMTMwLDAwMC4gR2FpbiBvbiBkaXNwb3NhbCAo4oKxKT8iLCJ1bml0Ijoi4oKxIiwicG9pbnRzIjoxMH0sCiAgICAgeyJpZCI6InE5IiwidHlwZSI6Im1jcSIsImxhYmVsIjoiQWNjZWxlcmF0ZWQiLCJwcm9tcHQiOiJBbiBhY2NlbGVyYXRlZCBtZXRob2QgZ2l2ZXPigKYiLCJvcHRpb25zIjpbeyJpZCI6ImEiLCJsYWJlbCI6Ikxvd2VyIGV4cGVuc2UgZWFybHkgYW5kIGhpZ2hlciBsYXRlciJ9LHsiaWQiOiJiIiwibGFiZWwiOiJIaWdoZXIgZXhwZW5zZSBlYXJseSBhbmQgbG93ZXIgbGF0ZXIifSx7ImlkIjoiYyIsImxhYmVsIjoiVGhlIHNhbWUgZXhwZW5zZSBldmVyeSB5ZWFyIn0seyJpZCI6ImQiLCJsYWJlbCI6IkEgaGlnaGVyIHRvdGFsIGV4cGVuc2Ugb3ZlciB0aGUgbGlmZSJ9XSwicG9pbnRzIjoxMH0sCiAgICAgeyJpZCI6InExMCIsInR5cGUiOiJudW1lcmljIiwibGFiZWwiOiJVbml0cyBvZiBwcm9kdWN0aW9uIiwicHJvbXB0IjoiQ29zdCDigrEzMDAsMDAwLCBzYWx2YWdlIOKCsTMwLDAwMCwgdG90YWwgY2FwYWNpdHkgOTAsMDAwIHVuaXRzOyAxMiwwMDAgdW5pdHMgd2VyZSB1c2VkIHRoaXMgeWVhci4gRGVwcmVjaWF0aW9uICjigrEpPyIsInVuaXQiOiLigrEiLCJwb2ludHMiOjEwfV0=', 'base64'), 'UTF8')::jsonb,
 convert_from(decode('eyJxMSI6eyJhbnN3ZXIiOjkwMDAwLCJ0b2xlcmFuY2VfcGN0IjowLjV9LCJxMiI6eyJhbnN3ZXIiOjMyMDAwMCwidG9sZXJhbmNlX3BjdCI6MC41fSwicTMiOnsiYW5zd2VyIjoyMDAwMDAsInRvbGVyYW5jZV9wY3QiOjAuNX0sInE0Ijp7ImFuc3dlciI6MTIwMDAwLCJ0b2xlcmFuY2VfcGN0IjowLjV9LCJxNSI6eyJhbnN3ZXIiOiJiIn0sInE2Ijp7ImFuc3dlciI6ImIifSwicTciOnsiYW5zd2VyIjoiYyJ9LCJxOCI6eyJhbnN3ZXIiOjMwMDAwLCJ0b2xlcmFuY2VfcGN0IjowLjV9LCJxOSI6eyJhbnN3ZXIiOiJiIn0sInExMCI6eyJhbnN3ZXIiOjM2MDAwLCJ0b2xlcmFuY2VfcGN0IjowLjV9fQ==', 'base64'), 'UTF8')::jsonb),
('receivables-bad-debts',
 convert_from(decode('W3siaWQiOiJxMSIsInR5cGUiOiJtY3EiLCJsYWJlbCI6IkFsbG93YW5jZSBtZXRob2QiLCJwcm9tcHQiOiJUaGUgYWxsb3dhbmNlIG1ldGhvZCByZWNvcmRzIGJhZCBkZWJ0c+KApiIsIm9wdGlvbnMiOlt7ImlkIjoiYSIsImxhYmVsIjoiT25seSB3aGVuIGFuIGludm9pY2UgaXMgd3JpdHRlbiBvZmYifSx7ImlkIjoiYiIsImxhYmVsIjoiQnkgZXN0aW1hdGUsIGluIHRoZSBwZXJpb2Qgb2YgdGhlIHJlbGF0ZWQgc2FsZXMifSx7ImlkIjoiYyIsImxhYmVsIjoiV2hlbiBjYXNoIGlzIGNvbGxlY3RlZCJ9LHsiaWQiOiJkIiwibGFiZWwiOiJOZXZlciDigJQgaXQgaXMgYSB0YXggY29uY2VwdCJ9XSwicG9pbnRzIjoxMH0sCiAgICAgeyJpZCI6InEyIiwidHlwZSI6Im51bWVyaWMiLCJsYWJlbCI6IlBlcmNlbnRhZ2Ugb2Ygc2FsZXMiLCJwcm9tcHQiOiJDcmVkaXQgc2FsZXMg4oKxNCwwMDAsMDAwIGFuZCBiYWQgZGVidHMgZXN0aW1hdGVkIGF0IDIlLiBCYWQgZGVidCBleHBlbnNlICjigrEpPyIsInVuaXQiOiLigrEiLCJwb2ludHMiOjEwfSwKICAgICB7ImlkIjoicTMiLCJ0eXBlIjoibnVtZXJpYyIsImxhYmVsIjoiQWdpbmcgZXhwZW5zZSIsInByb21wdCI6IlJlcXVpcmVkIGFsbG93YW5jZSAoYWdpbmcpIOKCsTE1MCwwMDA7IGV4aXN0aW5nIGFsbG93YW5jZSBoYXMgYSDigrE0MCwwMDAgY3JlZGl0IGJhbGFuY2UuIEJhZCBkZWJ0IGV4cGVuc2UgKOKCsSk/IiwidW5pdCI6IuKCsSIsInBvaW50cyI6MTB9LAogICAgIHsiaWQiOiJxNCIsInR5cGUiOiJudW1lcmljIiwibGFiZWwiOiJOZXQgcmVjZWl2YWJsZXMiLCJwcm9tcHQiOiJHcm9zcyByZWNlaXZhYmxlcyDigrEyLDAwMCwwMDAsIGFsbG93YW5jZSDigrExMjAsMDAwLiBOZXQgcmVhbGlzYWJsZSB2YWx1ZSAo4oKxKT8iLCJ1bml0Ijoi4oKxIiwicG9pbnRzIjoxMH0sCiAgICAgeyJpZCI6InE1IiwidHlwZSI6Im1jcSIsImxhYmVsIjoiV3JpdGUtb2ZmIiwicHJvbXB0IjoiV3JpdGluZyBvZmYgYSBzcGVjaWZpYyB1bmNvbGxlY3RpYmxlIGFjY291bnQgKGFsbG93YW5jZSBtZXRob2Qp4oCmIiwib3B0aW9ucyI6W3siaWQiOiJhIiwibGFiZWwiOiJSZWR1Y2VzIHByb2ZpdCBhZ2FpbiJ9LHsiaWQiOiJiIiwibGFiZWwiOiJJcyBEciBBbGxvd2FuY2UgLyBDciBSZWNlaXZhYmxlLCB3aXRoIG5vIGVmZmVjdCBvbiBuZXQgcmVjZWl2YWJsZXMgb3IgcHJvZml0In0seyJpZCI6ImMiLCJsYWJlbCI6IkluY3JlYXNlcyB0aGUgYWxsb3dhbmNlIn0seyJpZCI6ImQiLCJsYWJlbCI6IklzIERyIEJhZCBkZWJ0IGV4cGVuc2UgLyBDciBSZWNlaXZhYmxlIn1dLCJwb2ludHMiOjEwfSwKICAgICB7ImlkIjoicTYiLCJ0eXBlIjoibWNxIiwibGFiZWwiOiJBY2NvdW50IHR5cGUiLCJwcm9tcHQiOiJUaGUgYWxsb3dhbmNlIGZvciBkb3VidGZ1bCBhY2NvdW50cyBpc+KApiIsIm9wdGlvbnMiOlt7ImlkIjoiYSIsImxhYmVsIjoiQSBsaWFiaWxpdHkifSx7ImlkIjoiYiIsImxhYmVsIjoiQW4gZXhwZW5zZSJ9LHsiaWQiOiJjIiwibGFiZWwiOiJBIGNvbnRyYS1hc3NldCJ9LHsiaWQiOiJkIiwibGFiZWwiOiJFcXVpdHkifV0sInBvaW50cyI6MTB9LAogICAgIHsiaWQiOiJxNyIsInR5cGUiOiJudW1lcmljIiwibGFiZWwiOiJEU08iLCJwcm9tcHQiOiJBbm51YWwgY3JlZGl0IHNhbGVzIOKCsTMsNjUwLDAwMCBhbmQgcmVjZWl2YWJsZXMg4oKxNTAwLDAwMC4gRFNPIChkYXlzLCAzNjUtZGF5IHllYXIpPyIsInVuaXQiOiJkYXlzIiwicG9pbnRzIjoxMH0sCiAgICAgeyJpZCI6InE4IiwidHlwZSI6Im1jcSIsImxhYmVsIjoiUmlzaW5nIERTTyIsInByb21wdCI6IlJpc2luZyBEU08gbWF5IHNpZ25hbOKApiIsIm9wdGlvbnMiOlt7ImlkIjoiYSIsImxhYmVsIjoiRmFzdGVyIGNvbGxlY3Rpb25zIn0seyJpZCI6ImIiLCJsYWJlbCI6IlNsb3dlciBjb2xsZWN0aW9ucyBvciBhZ2dyZXNzaXZlIHJldmVudWUgcmVjb2duaXRpb24ifSx7ImlkIjoiYyIsImxhYmVsIjoiTG93ZXIgc2FsZXMifSx7ImlkIjoiZCIsImxhYmVsIjoiSGlnaGVyIGNhc2ggYmFsYW5jZXMifV0sInBvaW50cyI6MTB9LAogICAgIHsiaWQiOiJxOSIsInR5cGUiOiJudW1lcmljIiwibGFiZWwiOiJBZ2luZyIsInByb21wdCI6IjDigJMzMCBkYXlzIOKCsTEsMDAwLDAwMCBhdCAxJTsgMzHigJM2MCBkYXlzIOKCsTQwMCwwMDAgYXQgNSU7IG92ZXIgNjAgZGF5cyDigrEyMDAsMDAwIGF0IDIwJS4gUmVxdWlyZWQgYWxsb3dhbmNlICjigrEpPyIsInVuaXQiOiLigrEiLCJwb2ludHMiOjEwfSwKICAgICB7ImlkIjoicTEwIiwidHlwZSI6Im1jcSIsImxhYmVsIjoiUEZSUyA5IiwicHJvbXB0IjoiVW5kZXIgUEZSUyA5LCBjcmVkaXQgbG9zc2VzIG9uIHJlY2VpdmFibGVzIGFyZSBiYXNlZCBvbuKApiIsIm9wdGlvbnMiOlt7ImlkIjoiYSIsImxhYmVsIjoiTG9zc2VzIGFscmVhZHkgaW5jdXJyZWQgb25seSJ9LHsiaWQiOiJiIiwibGFiZWwiOiJFeHBlY3RlZCBjcmVkaXQgbG9zc2VzIn0seyJpZCI6ImMiLCJsYWJlbCI6IlRoZSB0YXggYXV0aG9yaXR5J3MgcmF0ZXMifSx7ImlkIjoiZCIsImxhYmVsIjoiQ2FzaCBjb2xsZWN0ZWQifV0sInBvaW50cyI6MTB9XQ==', 'base64'), 'UTF8')::jsonb,
 convert_from(decode('eyJxMSI6eyJhbnN3ZXIiOiJiIn0sInEyIjp7ImFuc3dlciI6ODAwMDAsInRvbGVyYW5jZV9wY3QiOjAuNX0sInEzIjp7ImFuc3dlciI6MTEwMDAwLCJ0b2xlcmFuY2VfcGN0IjowLjV9LCJxNCI6eyJhbnN3ZXIiOjE4ODAwMDAsInRvbGVyYW5jZV9wY3QiOjAuNX0sInE1Ijp7ImFuc3dlciI6ImIifSwicTYiOnsiYW5zd2VyIjoiYyJ9LCJxNyI6eyJhbnN3ZXIiOjUwLCJ0b2xlcmFuY2VfcGN0IjowLjV9LCJxOCI6eyJhbnN3ZXIiOiJiIn0sInE5Ijp7ImFuc3dlciI6NzAwMDAsInRvbGVyYW5jZV9wY3QiOjAuNX0sInExMCI6eyJhbnN3ZXIiOiJiIn19', 'base64'), 'UTF8')::jsonb),
('revenue-recognition',
 convert_from(decode('W3siaWQiOiJxMSIsInR5cGUiOiJtY3EiLCJsYWJlbCI6IkZpdmUgc3RlcHMiLCJwcm9tcHQiOiJXaGljaCBpcyB0aGUgY29ycmVjdCBvcmRlciBvZiB0aGUgZml2ZS1zdGVwIG1vZGVsPyIsIm9wdGlvbnMiOlt7ImlkIjoiYSIsImxhYmVsIjoiQ29udHJhY3Qg4oaSIHBlcmZvcm1hbmNlIG9ibGlnYXRpb25zIOKGkiBwcmljZSDihpIgYWxsb2NhdGUg4oaSIHJlY29nbmlzZSJ9LHsiaWQiOiJiIiwibGFiZWwiOiJQcmljZSDihpIgY29udHJhY3Qg4oaSIHJlY29nbmlzZSDihpIgYWxsb2NhdGUg4oaSIG9ibGlnYXRpb25zIn0seyJpZCI6ImMiLCJsYWJlbCI6IlJlY29nbmlzZSDihpIgY29udHJhY3Qg4oaSIHByaWNlIOKGkiBvYmxpZ2F0aW9ucyDihpIgYWxsb2NhdGUifSx7ImlkIjoiZCIsImxhYmVsIjoiT2JsaWdhdGlvbnMg4oaSIHJlY29nbmlzZSDihpIgY29udHJhY3Qg4oaSIGFsbG9jYXRlIOKGkiBwcmljZSJ9XSwicG9pbnRzIjoxMH0sCiAgICAgeyJpZCI6InEyIiwidHlwZSI6Im1jcSIsImxhYmVsIjoiVGltaW5nIiwicHJvbXB0IjoiUmV2ZW51ZSBpcyByZWNvZ25pc2VkIHdoZW7igKYiLCJvcHRpb25zIjpbeyJpZCI6ImEiLCJsYWJlbCI6IkNhc2ggaXMgcmVjZWl2ZWQifSx7ImlkIjoiYiIsImxhYmVsIjoiVGhlIGNvbnRyYWN0IGlzIHNpZ25lZCJ9LHsiaWQiOiJjIiwibGFiZWwiOiJBIHBlcmZvcm1hbmNlIG9ibGlnYXRpb24gaXMgc2F0aXNmaWVkIn0seyJpZCI6ImQiLCJsYWJlbCI6IlRoZSBpbnZvaWNlIGlzIHBhaWQifV0sInBvaW50cyI6MTB9LAogICAgIHsiaWQiOiJxMyIsInR5cGUiOiJudW1lcmljIiwibGFiZWwiOiJBbGxvY2F0aW9uOiBwaG9uZSIsInByb21wdCI6IkEgYnVuZGxlIHNlbGxzIGZvciDigrEzNiwwMDAuIFN0YW5kYWxvbmUgcHJpY2VzOiBwaG9uZSDigrEzMCwwMDAsIHNlcnZpY2UgcGxhbiDigrExMCwwMDAuIFJldmVudWUgYWxsb2NhdGVkIHRvIHRoZSBwaG9uZSAo4oKxKT8iLCJ1bml0Ijoi4oKxIiwicG9pbnRzIjoxMH0sCiAgICAgeyJpZCI6InE0IiwidHlwZSI6Im51bWVyaWMiLCJsYWJlbCI6IkFsbG9jYXRpb246IHNlcnZpY2UiLCJwcm9tcHQiOiJSZXZlbnVlIGFsbG9jYXRlZCB0byB0aGUgc2VydmljZSBwbGFuICjigrEpPyIsInVuaXQiOiLigrEiLCJwb2ludHMiOjEwfSwKICAgICB7ImlkIjoicTUiLCJ0eXBlIjoibWNxIiwibGFiZWwiOiJPdmVyIHRpbWUiLCJwcm9tcHQiOiJBIHNvZnR3YXJlIGxpY2VuY2UgaXMgZGVsaXZlcmVkIHRvZGF5IHdpdGggMTIgbW9udGhzIG9mIHN1cHBvcnQuIFRoZSBzdXBwb3J0IHJldmVudWUgaXMgcmVjb2duaXNlZOKApiIsIm9wdGlvbnMiOlt7ImlkIjoiYSIsImxhYmVsIjoiRW50aXJlbHkgdG9kYXkifSx7ImlkIjoiYiIsImxhYmVsIjoiT3ZlciB0aGUgMTIgbW9udGhzIn0seyJpZCI6ImMiLCJsYWJlbCI6IkF0IHRoZSBlbmQgb2YgdGhlIDEyIG1vbnRocyJ9LHsiaWQiOiJkIiwibGFiZWwiOiJPbmx5IHdoZW4gcmVuZXdlZCJ9XSwicG9pbnRzIjoxMH0sCiAgICAgeyJpZCI6InE2IiwidHlwZSI6Im51bWVyaWMiLCJsYWJlbCI6IlN0cmFpZ2h0LWxpbmUgcmV2ZW51ZSIsInByb21wdCI6IkEg4oKxMSwyMDAsMDAwIGNvbnRyYWN0IGNvdmVycyAyNCBtb250aHMgb2Ygc2VydmljZSwgcmVjb2duaXNlZCBldmVubHkuIFJldmVudWUgaW4gdGhlIGZpcnN0IDkgbW9udGhzICjigrEpPyIsInVuaXQiOiLigrEiLCJwb2ludHMiOjEwfSwKICAgICB7ImlkIjoicTciLCJ0eXBlIjoibWNxIiwibGFiZWwiOiJQcmVwYXltZW50IiwicHJvbXB0IjoiQ2FzaCByZWNlaXZlZCBiZWZvcmUgZGVsaXZlcnkgaXMgcmVwb3J0ZWQgYXPigKYiLCJvcHRpb25zIjpbeyJpZCI6ImEiLCJsYWJlbCI6IlJldmVudWUifSx7ImlkIjoiYiIsImxhYmVsIjoiQSBjb250cmFjdCBsaWFiaWxpdHkgKHVuZWFybmVkIHJldmVudWUpIn0seyJpZCI6ImMiLCJsYWJlbCI6IkEgcmVjZWl2YWJsZSJ9LHsiaWQiOiJkIiwibGFiZWwiOiJFcXVpdHkifV0sInBvaW50cyI6MTB9LAogICAgIHsiaWQiOiJxOCIsInR5cGUiOiJtY3EiLCJsYWJlbCI6IlZhcmlhYmxlIGNvbnNpZGVyYXRpb24iLCJwcm9tcHQiOiJWb2x1bWUgcmViYXRlcyAodmFyaWFibGUgY29uc2lkZXJhdGlvbikgYXJl4oCmIiwib3B0aW9ucyI6W3siaWQiOiJhIiwibGFiZWwiOiJJZ25vcmVkIHVudGlsIHBhaWQifSx7ImlkIjoiYiIsImxhYmVsIjoiRXN0aW1hdGVkIGFuZCBpbmNsdWRlZCBvbmx5IHRvIHRoZSBleHRlbnQgYSBzaWduaWZpY2FudCByZXZlcnNhbCBpcyB1bmxpa2VseSJ9LHsiaWQiOiJjIiwibGFiZWwiOiJBbHdheXMgaW5jbHVkZWQgYXQgdGhlIG1heGltdW0ifSx7ImlkIjoiZCIsImxhYmVsIjoiUmVjb3JkZWQgYXMgYW4gZXhwZW5zZSB3aGVuIHBhaWQifV0sInBvaW50cyI6MTB9LAogICAgIHsiaWQiOiJxOSIsInR5cGUiOiJudW1lcmljIiwibGFiZWwiOiJQZXJjZW50YWdlIG9mIGNvbXBsZXRpb24iLCJwcm9tcHQiOiJBIGNvbnN0cnVjdGlvbiBjb250cmFjdCBvZiDigrExMG0gaXMgNDAlIGNvbXBsZXRlIChjb3N0LXRvLWNvc3QpLiBSZXZlbnVlIHRvIGRhdGUgKOKCsW0pPyIsInVuaXQiOiLigrFtIiwicG9pbnRzIjoxMH0sCiAgICAgeyJpZCI6InExMCIsInR5cGUiOiJtY3EiLCJsYWJlbCI6IlJlZCBmbGFnIiwicHJvbXB0IjoiV2hpY2ggcGF0dGVybiBtb3N0IHN1Z2dlc3RzIGFnZ3Jlc3NpdmUgcmV2ZW51ZSByZWNvZ25pdGlvbj8iLCJvcHRpb25zIjpbeyJpZCI6ImEiLCJsYWJlbCI6IlJldmVudWUgYW5kIGNhc2ggY29sbGVjdGlvbnMgZ3Jvd2luZyB0b2dldGhlciJ9LHsiaWQiOiJiIiwibGFiZWwiOiJSZXZlbnVlIGdyb3dpbmcgZmFyIGZhc3RlciB0aGFuIGNhc2gsIHdpdGggcmVjZWl2YWJsZXMgYmFsbG9vbmluZyJ9LHsiaWQiOiJjIiwibGFiZWwiOiJTdGFibGUgZGVmZXJyZWQgcmV2ZW51ZSJ9LHsiaWQiOiJkIiwibGFiZWwiOiJGYWxsaW5nIHJlY2VpdmFibGUgZGF5cyJ9XSwicG9pbnRzIjoxMH1d', 'base64'), 'UTF8')::jsonb,
 convert_from(decode('eyJxMSI6eyJhbnN3ZXIiOiJhIn0sInEyIjp7ImFuc3dlciI6ImMifSwicTMiOnsiYW5zd2VyIjoyNzAwMCwidG9sZXJhbmNlX3BjdCI6MC41fSwicTQiOnsiYW5zd2VyIjo5MDAwLCJ0b2xlcmFuY2VfcGN0IjowLjV9LCJxNSI6eyJhbnN3ZXIiOiJiIn0sInE2Ijp7ImFuc3dlciI6NDUwMDAwLCJ0b2xlcmFuY2VfcGN0IjowLjV9LCJxNyI6eyJhbnN3ZXIiOiJiIn0sInE4Ijp7ImFuc3dlciI6ImIifSwicTkiOnsiYW5zd2VyIjo0LCJ0b2xlcmFuY2VfcGN0IjowLjV9LCJxMTAiOnsiYW5zd2VyIjoiYiJ9fQ==', 'base64'), 'UTF8')::jsonb)
), upd as (
  update public.lessons l set check_questions = qs.questions::jsonb
  from qs where l.slug = qs.slug and jsonb_array_length(l.check_questions) = 0
  returning l.id, qs.answers
)
insert into public.lesson_check_keys (lesson_id, answers)
select id, answers::jsonb from upd
on conflict (lesson_id) do nothing;
