-- seed_010_corpfin_modeling: part 2 of 3. Run the parts in order.
-- ---------------------------------------------------------------------
-- 3. Practice activities
-- ---------------------------------------------------------------------
insert into public.lesson_activities (lesson_id, slug, position, kind, title, instructions, content)
select l.id, v.slug, v.pos, v.kind, v.title, v.instructions, v.content::jsonb
from (values
('time-value-of-money', 'which-formula', 1, 'matching', 'Which formula is it?',
 'Match each description to the concept it describes.',
 '{"categories":[{"id":"pv","label":"Present value"},{"id":"fv","label":"Future value"},{"id":"an","label":"Annuity / perpetuity"}],
     "items":[{"id":"i1","label":"Cash flow ÷ (1 + r)ⁿ"},{"id":"i2","label":"PV × (1 + r)ⁿ"},{"id":"i3","label":"Compounds a lump sum forward"},{"id":"i4","label":"Discounts a future amount back to today"},
              {"id":"i5","label":"A level payment each period for n periods"},{"id":"i6","label":"A level payment forever: C ÷ r"},{"id":"i7","label":"What is this future cash worth today?"},{"id":"i8","label":"What will today''s savings grow to?"}]}'),
('time-value-of-money', 'scholarship-pv', 2, 'worked_example', 'Worked example: the value of a scholarship',
 'Discount each payment, then add them. Hints are available but cost points.',
 '{"intro":"A scholarship pays ₱30,000 at the end of each of the next 3 years. The discount rate is 10%.",
     "steps":[{"id":"s1","prompt":"Present value of the year-1 payment (₱)?","unit":"₱"},{"id":"s2","prompt":"Present value of the year-2 payment (₱)?","unit":"₱"},
              {"id":"s3","prompt":"Present value of the year-3 payment (₱)?","unit":"₱"},{"id":"s4","prompt":"Total present value (₱)?","unit":"₱"},
              {"id":"s5","prompt":"How much less than the ₱90,000 of total payments is that present value (₱)?","unit":"₱"}]}'),
('budgeting-variance-fpa', 'favourable-or-not', 1, 'matching', 'Favourable or unfavourable?',
 'Classify each variance against budget.',
 '{"categories":[{"id":"fav","label":"Favourable"},{"id":"unf","label":"Unfavourable"}],
     "items":[{"id":"i1","label":"Revenue above budget"},{"id":"i2","label":"Revenue below budget"},{"id":"i3","label":"Costs above budget"},{"id":"i4","label":"Costs below budget"},{"id":"i5","label":"Operating profit above budget"},{"id":"i6","label":"Operating profit below budget"}]}'),
('budgeting-variance-fpa', 'price-volume', 2, 'worked_example', 'Worked example: price and volume variances',
 'Split a revenue variance into its drivers. Enter negative numbers where revenue fell short.',
 '{"intro":"Budget: 2,000 units at ₱150. Actual: 1,800 units at ₱160.",
     "steps":[{"id":"s1","prompt":"Budget revenue (₱)?","unit":"₱"},{"id":"s2","prompt":"Actual revenue (₱)?","unit":"₱"},
              {"id":"s3","prompt":"Total revenue variance (₱, negative if below budget)?","unit":"₱"},
              {"id":"s4","prompt":"Volume variance = (actual − budget units) × budget price (₱, negative if unfavourable)?","unit":"₱"},
              {"id":"s5","prompt":"Price variance = (actual − budget price) × actual units (₱, negative if unfavourable)?","unit":"₱"}]}'),
('capital-budgeting-npv-irr', 'store-expansion-npv', 1, 'worked_example', 'Worked example: NPV of a store expansion',
 'Discount each year, add up, and decide. Enter negative numbers where the NPV is below zero.',
 '{"intro":"A store expansion costs ₱2,000,000 and returns ₱700,000, ₱800,000 and ₱900,000 in years 1 to 3. The required return is 10%.",
     "steps":[{"id":"s1","prompt":"Present value of year 1 (₱)?","unit":"₱"},{"id":"s2","prompt":"Present value of year 2 (₱)?","unit":"₱"},
              {"id":"s3","prompt":"Present value of year 3 (₱)?","unit":"₱"},{"id":"s4","prompt":"Total present value of the inflows (₱)?","unit":"₱"},
              {"id":"s5","prompt":"NPV (₱, negative if below zero)?","unit":"₱"}]}'),
('capital-budgeting-npv-irr', 'capital-review-errors', 2, 'spot_error', 'Spot the errors: a capital budget review',
 'Two conclusions in this review are wrong. Select them, then check.',
 '{"context":"Project: cost ₱1,000k; required return 10%; inflows of ₱500k a year for 3 years.","columns":["Measure","Result"],"select_count":2,
     "rows":[{"id":"r1","cells":["Payback","2 years"]},{"id":"r2","cells":["PV of inflows","₱1,243k"]},{"id":"r3","cells":["NPV","+₱243k"]},
             {"id":"r4","cells":["IRR","Below 10%"]},{"id":"r5","cells":["Profitability index","0.76"]},{"id":"r6","cells":["Decision","Accept"]}]}'),
('working-capital-ccc', 'which-lever', 1, 'matching', 'Which lever does it pull?',
 'Match each action to the part of the cash conversion cycle it improves.',
 '{"categories":[{"id":"dso","label":"Collect faster (DSO)"},{"id":"dio","label":"Hold less stock (DIO)"},{"id":"dpo","label":"Pay later (DPO)"}],
     "items":[{"id":"i1","label":"Offer early-payment discounts"},{"id":"i2","label":"Tighten credit approval"},{"id":"i3","label":"Use just-in-time ordering"},{"id":"i4","label":"Clear slow-moving stock"},
              {"id":"i5","label":"Negotiate 60-day supplier terms"},{"id":"i6","label":"Chase overdue invoices"},{"id":"i7","label":"Improve demand forecasting to cut safety stock"},{"id":"i8","label":"Pay on the due date rather than early"}]}'),
('working-capital-ccc', 'compute-ccc', 2, 'worked_example', 'Worked example: the cash conversion cycle',
 'Compute the three day measures and the cycle. Hints are available but cost points.',
 '{"intro":"Annual sales ₱14,600k; COGS ₱10,950k; receivables ₱1,600k; inventory ₱2,250k; payables ₱1,350k (365-day year).",
     "steps":[{"id":"s1","prompt":"DSO (days)?","unit":"days"},{"id":"s2","prompt":"DIO (days)?","unit":"days"},{"id":"s3","prompt":"DPO (days)?","unit":"days"},
              {"id":"s4","prompt":"Cash conversion cycle (days)?","unit":"days"},{"id":"s5","prompt":"Cash released if DSO falls by 10 days (₱k)?","unit":"₱k"}]}'),
('model-structure', 'where-does-it-live', 1, 'matching', 'Where does it live in the model?',
 'Sort each item into the part of a well-structured model it belongs to.',
 '{"categories":[{"id":"inp","label":"Inputs"},{"id":"calc","label":"Calculations"},{"id":"out","label":"Outputs"}],
     "items":[{"id":"i1","label":"Revenue growth assumption"},{"id":"i2","label":"Tax rate"},{"id":"i3","label":"Depreciation schedule"},{"id":"i4","label":"Debt schedule"},
              {"id":"i5","label":"Balance check"},{"id":"i6","label":"DCF value per share"},{"id":"i7","label":"Sensitivity table"},{"id":"i8","label":"Working-capital days"},{"id":"i9","label":"Summary chart of margins"}]}'),
('model-structure', 'roll-the-balance-sheet', 2, 'worked_example', 'Worked example: roll the balance sheet forward',
 'Move one year forward and check that it balances. Hints are available but cost points.',
 '{"intro":"Year 0: PP&E 800, cash 150, receivables 100, payables 80, debt 300, equity 670. Year 1: net income 90; dividends 30; capex 120; depreciation 100; receivables 120; payables 95; debt unchanged.",
     "steps":[{"id":"s1","prompt":"Closing PP&E?","unit":""},{"id":"s2","prompt":"Closing equity?","unit":""},{"id":"s3","prompt":"Cash flow from operations?","unit":""},
              {"id":"s4","prompt":"Closing cash?","unit":""},{"id":"s5","prompt":"Total assets (PP&E + cash + receivables)?","unit":""}]}'),
('revenue-drivers-forecasting', 'subscription-forecast', 1, 'worked_example', 'Worked example: a subscription forecast',
 'Build two months of customers and revenue. Hints are available but cost points.',
 '{"intro":"Opening customers 5,000; churn 4% of opening customers each month; 400 new customers each month; ARPU ₱500 a month on closing customers.",
     "steps":[{"id":"s1","prompt":"Customers at the end of month 1?","unit":""},{"id":"s2","prompt":"Customers at the end of month 2?","unit":""},
              {"id":"s3","prompt":"Month-2 revenue (₱)?","unit":"₱"},{"id":"s4","prompt":"Customers lost to churn in month 2?","unit":""},{"id":"s5","prompt":"Net customer additions in month 2?","unit":""}]}'),
('revenue-drivers-forecasting', 'unrealistic-assumptions', 2, 'spot_error', 'Spot the unrealistic assumptions',
 'Two assumptions in this forecast have no support. Select them, then check.',
 '{"context":"A consumer brand: current revenue ₱1.0bn growing 8% a year; the industry grows 5%.","columns":["Assumption","Value"],"select_count":2,
     "rows":[{"id":"r1","cells":["Year 1 revenue growth","8%"]},{"id":"r2","cells":["Year 2 revenue growth","9%"]},{"id":"r3","cells":["Year 3 revenue growth","35%, with no new products or markets"]},
             {"id":"r4","cells":["Gross margin","42%, rising to 43%"]},{"id":"r5","cells":["Year 5 market share","Doubles from 6% to 12% with no new products"]},{"id":"r6","cells":["Capex","3% of revenue"]}]}'),
('scenarios-sensitivity', 'sens-or-scenario', 1, 'matching', 'Sensitivity or scenario?',
 'Decide which tool each description belongs to.',
 '{"categories":[{"id":"sens","label":"Sensitivity analysis"},{"id":"scen","label":"Scenario analysis"}],
     "items":[{"id":"i1","label":"Change only WACC and watch the value"},{"id":"i2","label":"Bull, base and bear cases"},{"id":"i3","label":"Two-way table of WACC against terminal growth"},
              {"id":"i4","label":"A recession story: lower sales, margin squeeze, delayed capex"},{"id":"i5","label":"Tornado chart"},{"id":"i6","label":"Probability-weighted value across cases"}]}'),
('scenarios-sensitivity', 'probability-weighted', 2, 'worked_example', 'Worked example: probability-weighted value',
 'Weight the three cases and compare with the market price. Hints are available but cost points.',
 '{"intro":"A stock''s bull, base and bear values are ₱180, ₱120 and ₱60, with probabilities of 25%, 50% and 25%. The share price is ₱100.",
     "steps":[{"id":"s1","prompt":"Bull contribution (probability × value) (₱)?","unit":"₱"},{"id":"s2","prompt":"Base contribution (₱)?","unit":"₱"},
              {"id":"s3","prompt":"Bear contribution (₱)?","unit":"₱"},{"id":"s4","prompt":"Probability-weighted value (₱)?","unit":"₱"},{"id":"s5","prompt":"Upside versus the ₱100 price (%)?","unit":"%"}]}')
) as v(lesson, slug, pos, kind, title, instructions, content)
join public.lessons l on l.slug = v.lesson
on conflict (lesson_id, slug) do update
  set position = excluded.position, kind = excluded.kind, title = excluded.title,
      instructions = excluded.instructions, content = excluded.content;

insert into public.lesson_activity_keys (activity_id, key)
select a.id, v.key::jsonb
from (values
('time-value-of-money', 'which-formula', '{"i1":"pv","i2":"fv","i3":"fv","i4":"pv","i5":"an","i6":"an","i7":"pv","i8":"fv"}'),
('time-value-of-money', 'scholarship-pv', '{
  "s1":{"answer":27272.73,"tolerance_pct":0.5,"hint":"30,000 ÷ 1.10.","explanation":"30,000 ÷ 1.1 = 27,272.73."},
  "s2":{"answer":24793.39,"tolerance_pct":0.5,"hint":"30,000 ÷ 1.10².","explanation":"30,000 ÷ 1.21 = 24,793.39."},
  "s3":{"answer":22539.44,"tolerance_pct":0.5,"hint":"30,000 ÷ 1.10³.","explanation":"30,000 ÷ 1.331 = 22,539.44."},
  "s4":{"answer":74605.56,"tolerance_pct":0.5,"hint":"Add the three present values.","explanation":"27,272.73 + 24,793.39 + 22,539.44 = 74,605.56."},
  "s5":{"answer":15394.44,"tolerance_pct":1,"hint":"90,000 minus the present value.","explanation":"90,000 − 74,605.56 = 15,394.44 — the cost of waiting for the money."}}'),
('budgeting-variance-fpa', 'favourable-or-not', '{"i1":"fav","i2":"unf","i3":"unf","i4":"fav","i5":"fav","i6":"unf"}'),
('budgeting-variance-fpa', 'price-volume', '{
  "s1":{"answer":300000,"tolerance_pct":0.5,"hint":"2,000 × 150.","explanation":"2,000 × 150 = 300,000."},
  "s2":{"answer":288000,"tolerance_pct":0.5,"hint":"1,800 × 160.","explanation":"1,800 × 160 = 288,000."},
  "s3":{"answer":-12000,"tolerance_pct":0.5,"hint":"Actual minus budget.","explanation":"288,000 − 300,000 = −12,000 (unfavourable)."},
  "s4":{"answer":-30000,"tolerance_pct":0.5,"hint":"(1,800 − 2,000) × 150.","explanation":"−200 × 150 = −30,000."},
  "s5":{"answer":18000,"tolerance_pct":0.5,"hint":"(160 − 150) × 1,800.","explanation":"10 × 1,800 = +18,000. Volume −30,000 plus price +18,000 equals the −12,000 total."}}'),
('capital-budgeting-npv-irr', 'store-expansion-npv', '{
  "s1":{"answer":636363.64,"tolerance_pct":0.5,"hint":"700,000 ÷ 1.10.","explanation":"700,000 ÷ 1.1 = 636,363.64."},
  "s2":{"answer":661157.02,"tolerance_pct":0.5,"hint":"800,000 ÷ 1.10².","explanation":"800,000 ÷ 1.21 = 661,157.02."},
  "s3":{"answer":676183.82,"tolerance_pct":0.5,"hint":"900,000 ÷ 1.10³.","explanation":"900,000 ÷ 1.331 = 676,183.82."},
  "s4":{"answer":1973704.48,"tolerance_pct":0.5,"hint":"Add the three present values.","explanation":"636,363.64 + 661,157.02 + 676,183.82 = 1,973,704.48."},
  "s5":{"answer":-26295.52,"tolerance_pct":1,"hint":"PV of inflows minus the 2,000,000 investment.","explanation":"1,973,704.48 − 2,000,000 = −26,295.52. NPV is negative, so reject: the project earns slightly less than 10%."}}'),
('capital-budgeting-npv-irr', 'capital-review-errors', '{"errors":["r4","r5"],"explanations":{"r4":"NPV is positive at 10%, so the IRR must be above 10%.","r5":"Profitability index = PV of inflows ÷ investment = 1,243 ÷ 1,000 = 1.24, not 0.76."}}'),
('working-capital-ccc', 'which-lever', '{"i1":"dso","i2":"dso","i3":"dio","i4":"dio","i5":"dpo","i6":"dso","i7":"dio","i8":"dpo"}'),
('working-capital-ccc', 'compute-ccc', '{
  "s1":{"answer":40,"tolerance_pct":0.5,"hint":"Receivables ÷ sales × 365.","explanation":"1,600 ÷ 14,600 × 365 = 40 days."},
  "s2":{"answer":75,"tolerance_pct":0.5,"hint":"Inventory ÷ COGS × 365.","explanation":"2,250 ÷ 10,950 × 365 = 75 days."},
  "s3":{"answer":45,"tolerance_pct":0.5,"hint":"Payables ÷ COGS × 365.","explanation":"1,350 ÷ 10,950 × 365 = 45 days."},
  "s4":{"answer":70,"tolerance_pct":0.5,"hint":"DIO + DSO − DPO.","explanation":"75 + 40 − 45 = 70 days."},
  "s5":{"answer":400,"tolerance_pct":0.5,"hint":"Daily sales × 10 days.","explanation":"Daily sales = 14,600 ÷ 365 = 40; × 10 days = ₱400k."}}'),
('model-structure', 'where-does-it-live', '{"i1":"inp","i2":"inp","i3":"calc","i4":"calc","i5":"calc","i6":"out","i7":"out","i8":"inp","i9":"out"}'),
('model-structure', 'roll-the-balance-sheet', '{
  "s1":{"answer":820,"tolerance_pct":0.5,"hint":"Opening + capex − depreciation.","explanation":"800 + 120 − 100 = 820."},
  "s2":{"answer":730,"tolerance_pct":0.5,"hint":"Opening equity + net income − dividends.","explanation":"670 + 90 − 30 = 730."},
  "s3":{"answer":185,"tolerance_pct":0.5,"hint":"Net income + D&A − increase in receivables + increase in payables.","explanation":"90 + 100 − 20 + 15 = 185."},
  "s4":{"answer":185,"tolerance_pct":0.5,"hint":"Opening cash + CFO + CFI + CFF. CFI = −120; CFF = −30 dividends.","explanation":"150 + 185 − 120 − 30 = 185."},
  "s5":{"answer":1125,"tolerance_pct":0.5,"hint":"820 + cash + 120.","explanation":"820 + 185 + 120 = 1,125 = payables 95 + debt 300 + equity 730. It balances."}}'),
('revenue-drivers-forecasting', 'subscription-forecast', '{
  "s1":{"answer":5200,"tolerance_pct":0.5,"hint":"Opening × (1 − churn) + new.","explanation":"5,000 × 0.96 + 400 = 5,200."},
  "s2":{"answer":5392,"tolerance_pct":0.5,"hint":"5,200 × 0.96 + 400.","explanation":"5,200 × 0.96 + 400 = 5,392."},
  "s3":{"answer":2696000,"tolerance_pct":0.5,"hint":"Closing customers × ARPU.","explanation":"5,392 × 500 = 2,696,000."},
  "s4":{"answer":208,"tolerance_pct":0.5,"hint":"4% of the 5,200 opening customers.","explanation":"5,200 × 4% = 208."},
  "s5":{"answer":192,"tolerance_pct":0.5,"hint":"Closing minus opening.","explanation":"5,392 − 5,200 = 192 (400 new − 208 churned)."}}'),
('revenue-drivers-forecasting', 'unrealistic-assumptions', '{"errors":["r3","r5"],"explanations":{"r3":"35% growth in a 5% industry with no new products or markets is a hockey stick with no driver behind it.","r5":"Doubling market share with no new products has no support — it needs a driver such as new channels, pricing or products."}}'),
('scenarios-sensitivity', 'sens-or-scenario', '{"i1":"sens","i2":"scen","i3":"sens","i4":"scen","i5":"sens","i6":"scen"}'),
('scenarios-sensitivity', 'probability-weighted', '{
  "s1":{"answer":45,"tolerance_pct":0.5,"hint":"25% × 180.","explanation":"0.25 × 180 = 45."},
  "s2":{"answer":60,"tolerance_pct":0.5,"hint":"50% × 120.","explanation":"0.50 × 120 = 60."},
  "s3":{"answer":15,"tolerance_pct":0.5,"hint":"25% × 60.","explanation":"0.25 × 60 = 15."},
  "s4":{"answer":120,"tolerance_pct":0.5,"hint":"Add the three contributions.","explanation":"45 + 60 + 15 = 120."},
  "s5":{"answer":20,"tolerance_pct":1,"hint":"(120 − 100) ÷ 100.","explanation":"(120 − 100) ÷ 100 = 20% upside."}}')
) as v(lesson, slug, key)
join public.lessons l on l.slug = v.lesson
join public.lesson_activities a on a.lesson_id = l.id and a.slug = v.slug
on conflict (activity_id) do update set key = excluded.key, updated_at = now();

-- ---------------------------------------------------------------------
-- 4. Flashcards
-- ---------------------------------------------------------------------
insert into public.flashcards (lesson_id, position, front, back)
select l.id, v.pos, v.front, v.back
from (values
('time-value-of-money',1,'Future value','PV × (1 + r)ⁿ.'),
('time-value-of-money',2,'Present value','FV ÷ (1 + r)ⁿ.'),
('time-value-of-money',3,'Annuity present value','C × [1 − (1 + r)⁻ⁿ] ÷ r.'),
('time-value-of-money',4,'Perpetuity present value','C ÷ r.'),
('time-value-of-money',5,'Rule of 72','Years to double ≈ 72 ÷ rate (%).'),
('time-value-of-money',6,'Effective annual rate','(1 + nominal ÷ m)ᵐ − 1.'),
('time-value-of-money',7,'Higher discount rate means…','A lower present value.'),
('time-value-of-money',8,'More frequent compounding means…','A higher effective annual rate for the same nominal rate.'),
('time-value-of-money',9,'Why does money have a time value?','It can be invested to earn a return, and prices change over time.'),
('time-value-of-money',10,'First step when comparing cash flows at different dates','Move them all to a common date.'),
('budgeting-variance-fpa',1,'Variance =','Actual − Budget.'),
('budgeting-variance-fpa',2,'Variance % =','Variance ÷ Budget.'),
('budgeting-variance-fpa',3,'A cost above budget is…','Unfavourable.'),
('budgeting-variance-fpa',4,'Volume variance =','(Actual units − Budget units) × Budget price.'),
('budgeting-variance-fpa',5,'Price variance =','(Actual price − Budget price) × Actual units.'),
('budgeting-variance-fpa',6,'Flexible budget','The budget restated at the actual activity level.'),
('budgeting-variance-fpa',7,'Rolling forecast','Updated regularly, always looking a fixed period ahead.'),
('budgeting-variance-fpa',8,'Why use materiality thresholds?','So effort goes to the large variances.'),
('budgeting-variance-fpa',9,'What should variance commentary state?','The cause, whether it is one-off or recurring, and the action.'),
('budgeting-variance-fpa',10,'What does FP&A do?','Budget, track actuals, explain variances and update the forecast.'),
('capital-budgeting-npv-irr',1,'NPV','PV of future cash flows − initial investment. Accept if > 0.'),
('capital-budgeting-npv-irr',2,'IRR','The discount rate at which NPV = 0.'),
('capital-budgeting-npv-irr',3,'IRR decision rule','Accept if IRR > required return.'),
('capital-budgeting-npv-irr',4,'Profitability index','PV of inflows ÷ investment. Accept if > 1.'),
('capital-budgeting-npv-irr',5,'Payback period','Years to recover the initial investment.'),
('capital-budgeting-npv-irr',6,'Payback weaknesses','Ignores the time value of money and cash flows after payback.'),
('capital-budgeting-npv-irr',7,'Discounted payback','Payback using discounted cash flows.'),
('capital-budgeting-npv-irr',8,'When NPV and IRR disagree','Follow NPV.'),
('capital-budgeting-npv-irr',9,'A project earning exactly the cost of capital has…','An NPV of zero.'),
('capital-budgeting-npv-irr',10,'Discount rate for project cash flows','The cost of capital (WACC), adjusted for project risk.'),
('working-capital-ccc',1,'Net working capital','Current assets − Current liabilities.'),
('working-capital-ccc',2,'DSO','Receivables ÷ Sales × 365.'),
('working-capital-ccc',3,'DIO','Inventory ÷ COGS × 365.'),
('working-capital-ccc',4,'DPO','Payables ÷ COGS × 365.'),
('working-capital-ccc',5,'Cash conversion cycle','DIO + DSO − DPO.'),
('working-capital-ccc',6,'Negative CCC means…','Customers pay before suppliers are paid; suppliers fund the business.'),
('working-capital-ccc',7,'How to shorten the CCC','Collect faster, hold less stock, pay suppliers later.'),
('working-capital-ccc',8,'Cash released by cutting DSO','Daily sales × days reduced.'),
('working-capital-ccc',9,'Why growth consumes cash','Stock and receivables must be funded before the cash arrives.'),
('working-capital-ccc',10,'Action that lengthens the CCC','Offering customers longer credit terms.'),
('model-structure',1,'Model structure','Inputs → calculations → outputs.'),
('model-structure',2,'Blue font convention','Hard-coded inputs.'),
('model-structure',3,'Net income flows to…','Retained earnings (less dividends).'),
('model-structure',4,'PP&E roll-forward','Closing = opening + capex − depreciation.'),
('model-structure',5,'Retained earnings roll-forward','Closing = opening + net income − dividends.'),
('model-structure',6,'CFO (indirect)','Net income + D&A − increase in receivables + increase in payables.'),
('model-structure',7,'Closing cash','Opening cash + CFO + CFI + CFF.'),
('model-structure',8,'Balance check','Assets − (liabilities + equity) = 0 every period.'),
('model-structure',9,'Revolver','Borrows automatically when cash would go negative.'),
('model-structure',10,'Why avoid hard-codes in formulas?','They hide assumptions and are missed when inputs change.'),
('revenue-drivers-forecasting',1,'Price × volume growth','(1 + volume growth)(1 + price growth) − 1.'),
('revenue-drivers-forecasting',2,'Subscription customers','Opening × (1 − churn) + new customers.'),
('revenue-drivers-forecasting',3,'Subscription revenue','Customers × ARPU.'),
('revenue-drivers-forecasting',4,'Retail growth drivers','Same-store sales growth plus new stores.'),
('revenue-drivers-forecasting',5,'Market-share build','Market size × share.'),
('revenue-drivers-forecasting',6,'CAGR','(End ÷ Start)^(1/years) − 1.'),
('revenue-drivers-forecasting',7,'Hockey stick','Sudden growth acceleration with no driver — a red flag.'),
('revenue-drivers-forecasting',8,'Three sanity checks','History, capacity and market size.'),
('revenue-drivers-forecasting',9,'Why forecast by drivers?','Each assumption is explicit and testable.'),
('revenue-drivers-forecasting',10,'Best practice','Forecast revenue two ways and check they agree.'),
('scenarios-sensitivity',1,'Sensitivity analysis','Change one input at a time (or two in a data table).'),
('scenarios-sensitivity',2,'Scenario analysis','Change several linked inputs together: bull, base, bear.'),
('scenarios-sensitivity',3,'Base case','The most likely set of assumptions.'),
('scenarios-sensitivity',4,'Tornado chart','Ranks inputs by how much they move the output.'),
('scenarios-sensitivity',5,'Scenario switch','A 1/2/3 selector (CHOOSE/INDEX) that flips all drivers together.'),
('scenarios-sensitivity',6,'Probability-weighted value','Σ (probability × value).'),
('scenarios-sensitivity',7,'Keep scenarios consistent','Growth, margins, working capital and capex must move together.'),
('scenarios-sensitivity',8,'A good bear case stresses','Liquidity and covenants, not only earnings.'),
('scenarios-sensitivity',9,'EV from a multiple','EBITDA × EV/EBITDA multiple.'),
('scenarios-sensitivity',10,'Sensitivities vs scenarios','Sensitivities show which assumption matters; scenarios show what could happen.')
) as v(lesson, pos, front, back)
join public.lessons l on l.slug = v.lesson
on conflict (lesson_id, position) do update set front = excluded.front, back = excluded.back;
