-- seed_011_personal_interview: part 1 of 3. Run the parts in order.
-- =====================================================================
-- FINLAB — Content v11: Personal Finance Essentials (track) and
--   Finance Interview Prep (certification)
--   7 lessons (video + 10-question check + 2 practice activities + 10 flashcards),
--   3 challenges, 1 timed final exam, 2 programs, 2 new categories.
-- Run AFTER seed_010. Safe to re-run.
-- =====================================================================

insert into public.challenge_categories (id, name, description, icon, sort_order) values
 ('personal_finance', 'Personal Finance', 'Budgeting, saving, compounding and investing basics.', 'trending-up', 9),
 ('career_prep', 'Interview Prep', 'Technical questions for finance internships and analyst roles.', 'target', 10)
on conflict (id) do nothing;

-- ---------------------------------------------------------------------
-- 1. Lessons
-- ---------------------------------------------------------------------
insert into public.lessons (slug, title, summary, category_id, difficulty, estimated_minutes, sort_order, related_challenge_slugs, video_urls, body) values
('budgeting-503020', 'Budgeting with the 50/30/20 Rule', 'Take-home pay, needs, wants and paying yourself first.', 'personal_finance', 'beginner', 12, 40,
 '{personal-finance-plan}', '{https://www.youtube.com/watch?v=XLD0f5Nzr3c}', '
## Start with take-home pay
Your budget runs on **take-home pay** — what lands in your account after tax and mandatory contributions (SSS, PhilHealth, Pag-IBIG).

## The 50/30/20 rule
- **50% needs:** rent, groceries, utilities, transport to work, minimum debt payments.
- **30% wants:** dining out, streaming, hobbies, travel, shopping.
- **20% savings and debt repayment:** emergency fund, investments, extra debt payments.

On ₱30,000 take-home: needs ₱15,000, wants ₱9,000, savings ₱6,000.

## Make it work
- **Pay yourself first:** move savings out the day you are paid, before spending.
- **Track** spending for a month to see where money really goes.
- If needs are above 50%, trim wants or raise income — adjust the split (for example 60/20/20) rather than abandon the habit.

> A budget is not a punishment: it is a decision about what your money should do before it disappears.
'),
('compound-interest-saving', 'Compound Interest & Saving Early', 'Simple vs compound interest, the rule of 72 and why starting early matters.', 'personal_finance', 'beginner', 12, 41,
 '{personal-finance-plan}', '{https://www.youtube.com/watch?v=JWhkxNLOGFk}', '
## Simple vs compound
- **Simple interest** is paid only on the original amount: ₱50,000 at 6% for 3 years earns 50,000 × 6% × 3 = **₱9,000**.
- **Compound interest** is paid on the amount **plus past interest**: 50,000 × 1.06³ = **₱59,551**.

Compounding makes growth accelerate: each year''s interest is bigger than the last.

## The rule of 72
Years to double ≈ **72 ÷ rate (%)**. At 8%, money doubles in about 9 years; at 6%, about 12 years.

## Why starting early wins
Time gives compounding more rounds to work with. Saving the same amount ten years earlier can leave you with far more, because the early pesos have decades to grow.

## Beat inflation
**Real return ≈ nominal return − inflation.** A savings account paying 1% while prices rise 4% **loses** purchasing power.

> The two levers you control are how much you save and how long you let it compound.
'),
('investing-basics-funds', 'Investing Basics: Stocks, Bonds & Funds', 'Ownership vs lending, mutual funds and ETFs, risk, diversification and fees.', 'personal_finance', 'beginner', 15, 42,
 '{personal-finance-plan}', '{https://www.youtube.com/watch?v=qIw-yFC-HNU}', '
## The building blocks
- **Stocks:** a share of ownership. You may earn from price growth and dividends — and you can lose money.
- **Bonds:** a loan to a government or company. It pays **interest (coupon)** and returns the **face value** at maturity.
- **Mutual funds** and **ETFs:** pooled baskets of many securities, giving instant diversification. ETFs trade on an exchange during the day; mutual funds are priced once a day.

## Risk and return
Higher potential return comes with **higher risk**. Stocks fluctuate more than bonds, but have historically earned more over long periods.

## Practical rules
- **Diversify:** spread money so no single investment can sink you.
- **Match risk to time horizon:** money needed within 2 years belongs in low-risk assets; long-term money can take more stock risk.
- **Watch fees:** a 1.5% expense ratio on ₱200,000 costs ₱3,000 a year — and it compounds against you.
- **Peso-cost averaging:** invest a fixed amount regularly instead of timing the market.

> Educational content, not investment advice. Understand what you buy and never invest money you cannot afford to lose.
'),
('emergency-fund-inflation', 'Emergency Funds & Inflation', 'How much to hold, where to keep it, and what inflation does to cash.', 'personal_finance', 'beginner', 12, 43,
 '{personal-finance-plan}', '{https://www.youtube.com/watch?v=xAJgl6ml4YQ}', '
## What it is
An **emergency fund** is cash set aside for job loss, medical bills or urgent repairs — so a surprise doesn''t become debt.

## How much?
Typically **3–6 months of essential expenses** (not income). Freelancers and single-income households need more; salaried workers with stable jobs can aim lower.

## Where to keep it
Somewhere **safe and accessible**: a savings account or money-market fund. Not in volatile investments you might have to sell at a loss.

## Inflation
Inflation raises prices over time, so cash loses purchasing power. At 4% inflation, ₱100,000 buys about ₱96,154 worth of today''s goods a year from now. **Real return ≈ interest rate − inflation.**

## Order of priorities
1. Build a starter emergency fund.
2. Pay off **high-interest debt** (credit cards charging 3% a month beat any investment).
3. Then invest for the long term.

> Revisit the target each year: as prices rise, a fixed peso amount covers less.
'),
('interview-three-statements', 'Interview: The Three Statements', 'How the statements link and how to walk through a depreciation question.', 'career_prep', 'intermediate', 15, 44,
 '{interview-mock-technical}', '{https://www.youtube.com/watch?v=89D59hk_NIo}', '
## The question you will be asked
*"Walk me through the three financial statements and how they link."*

**A strong answer:** the income statement shows profit over a period; **net income** flows to the **cash flow statement** (start of operating cash flow) and to **retained earnings** on the balance sheet. The cash flow statement adjusts for non-cash items and working capital and ends in the **change in cash**, which updates the balance sheet''s cash.

## The classic: "Depreciation goes up by ₱20. Walk me through it." (tax rate 25%)
1. **Income statement:** EBIT falls by 20; tax falls by 5; **net income falls by 15**.
2. **Cash flow statement:** start at −15, **add back** 20 of non-cash depreciation → **cash from operations rises by 5** (the tax shield).
3. **Balance sheet:** cash **+5**, PP&E **−20** → assets **−15**; retained earnings **−15**. It balances.

## Other patterns
- Increase in receivables → lowers operating cash flow.
- Buying equipment with cash → assets unchanged in total (cash down, PP&E up).
- Borrowing to buy inventory → assets and liabilities both rise.

> Interviewers care that you can explain the **why**, not only recite the steps.
'),
('interview-dcf-walkthrough', 'Interview: Walk Me Through a DCF', 'A 60-second DCF answer, unlevered free cash flow, terminal value and the equity bridge.', 'career_prep', 'intermediate', 15, 45,
 '{interview-mock-technical}', '{https://www.youtube.com/watch?v=3T_P0ym1DFs}', '
## The 60-second answer
*"A DCF values a company at the present value of its future cash flows. I project **unlevered free cash flow** for 5–10 years, calculate a **terminal value**, discount everything at the **WACC** to get **enterprise value**, then subtract **net debt** to reach **equity value** and divide by diluted shares."*

## The pieces
- **UFCF** = EBIT × (1 − tax) + D&A − capex − increase in NWC.
- **Terminal value (Gordon growth)** = FCF × (1 + g) ÷ (WACC − g). Or use an exit multiple.
- **Discounting:** PV = Cash flow ÷ (1 + WACC)ⁿ. Discount the terminal value too.
- **Equity bridge:** Equity value = EV − net debt (and preferred, minorities).

## Follow-ups to expect
- Terminal value is often **60–80% of EV** — so the answer is sensitive to assumptions.
- Cross-check the two terminal methods; show a **WACC × growth** sensitivity.
- Use **unlevered** cash flows with **WACC**; mixing levered cash flows with WACC is a classic error.
- A higher WACC lowers value.

> Practise saying it out loud with a simple numerical example.
'),
('interview-ev-equity', 'Interview: Enterprise Value vs Equity Value', 'The bridge, why cash is subtracted and which multiple pairs with which value.', 'career_prep', 'intermediate', 15, 46,
 '{interview-mock-technical}', '{https://www.youtube.com/watch?v=nhcx4efjRl8}', '
## Two different values
- **Equity value** = share price × diluted shares. It belongs to shareholders.
- **Enterprise value (EV)** = equity value + debt + preferred stock + minority interest − cash. It is the value of the operating business to **all** capital providers.

## Why subtract cash?
Cash is not part of the operating business, and if you bought the company the cash would offset part of the price you pay.

## Pairing multiples
- **EV** pairs with metrics available to all capital providers: **EV/EBITDA**, EV/Revenue.
- **Equity value** pairs with metrics available to shareholders: **P/E** (equity value ÷ net income).
- **EV/EBITDA** compares companies with different debt levels better, because it is capital-structure neutral.

## Going from a multiple to a price
Implied EV = EBITDA × multiple → subtract net debt (and preferred, minorities) → implied equity value → ÷ diluted shares = implied share price.

> Memorising the formula isn''t enough: be ready to explain why each item is added or subtracted.
')
on conflict (slug) do nothing;

-- ---------------------------------------------------------------------
-- 2. Knowledge checks
-- ---------------------------------------------------------------------
with qs(slug, questions, answers) as (values
('budgeting-503020',
 convert_from(decode('W3siaWQiOiJxMSIsInR5cGUiOiJudW1lcmljIiwibGFiZWwiOiJOZWVkcyIsInByb21wdCI6IlRha2UtaG9tZSBwYXkgaXMg4oKxMzAsMDAwLiBUaGUgNTAlIG5lZWRzIGJ1ZGdldCAo4oKxKT8iLCJ1bml0Ijoi4oKxIiwicG9pbnRzIjoxMH0sCiAgICAgeyJpZCI6InEyIiwidHlwZSI6Im51bWVyaWMiLCJsYWJlbCI6IldhbnRzIiwicHJvbXB0IjoiT24gdGhlIHNhbWUgcGF5LCB0aGUgMzAlIHdhbnRzIGJ1ZGdldCAo4oKxKT8iLCJ1bml0Ijoi4oKxIiwicG9pbnRzIjoxMH0sCiAgICAgeyJpZCI6InEzIiwidHlwZSI6Im51bWVyaWMiLCJsYWJlbCI6IlNhdmluZ3MiLCJwcm9tcHQiOiJPbiB0aGUgc2FtZSBwYXksIHRoZSAyMCUgc2F2aW5ncyB0YXJnZXQgKOKCsSk/IiwidW5pdCI6IuKCsSIsInBvaW50cyI6MTB9LAogICAgIHsiaWQiOiJxNCIsInR5cGUiOiJtY3EiLCJsYWJlbCI6IkEgbmVlZCIsInByb21wdCI6IldoaWNoIGlzIGEgbmVlZD8iLCJvcHRpb25zIjpbeyJpZCI6ImEiLCJsYWJlbCI6IlN0cmVhbWluZyBzdWJzY3JpcHRpb24ifSx7ImlkIjoiYiIsImxhYmVsIjoiUmVudCJ9LHsiaWQiOiJjIiwibGFiZWwiOiJDb25jZXJ0IHRpY2tldHMifSx7ImlkIjoiZCIsImxhYmVsIjoiRGluaW5nIG91dCJ9XSwicG9pbnRzIjoxMH0sCiAgICAgeyJpZCI6InE1IiwidHlwZSI6Im1jcSIsImxhYmVsIjoiQSB3YW50IiwicHJvbXB0IjoiV2hpY2ggaXMgYSB3YW50PyIsIm9wdGlvbnMiOlt7ImlkIjoiYSIsImxhYmVsIjoiRWxlY3RyaWNpdHkifSx7ImlkIjoiYiIsImxhYmVsIjoiR3JvY2VyaWVzIn0seyJpZCI6ImMiLCJsYWJlbCI6IkRpbmluZyBvdXQifSx7ImlkIjoiZCIsImxhYmVsIjoiTWluaW11bSBsb2FuIHBheW1lbnQifV0sInBvaW50cyI6MTB9LAogICAgIHsiaWQiOiJxNiIsInR5cGUiOiJudW1lcmljIiwibGFiZWwiOiJOZWVkcyBzaGFyZSIsInByb21wdCI6IlRha2UtaG9tZSDigrE0MCwwMDAuIFJlbnQg4oKxMTIsMDAwLCBmb29kIOKCsTYsMDAwLCB0cmFuc3BvcnQg4oKxMywwMDAsIHV0aWxpdGllcyDigrEyLDAwMC4gTmVlZHMgYXMgYSAlIG9mIHRha2UtaG9tZT8iLCJ1bml0IjoiJSIsInBvaW50cyI6MTB9LAogICAgIHsiaWQiOiJxNyIsInR5cGUiOiJtY3EiLCJsYWJlbCI6IlBheSB5b3Vyc2VsZiBmaXJzdCIsInByb21wdCI6IidQYXkgeW91cnNlbGYgZmlyc3QnIG1lYW5z4oCmIiwib3B0aW9ucyI6W3siaWQiOiJhIiwibGFiZWwiOiJTcGVuZCBvbiB3YW50cyBiZWZvcmUgYmlsbHMifSx7ImlkIjoiYiIsImxhYmVsIjoiTW92ZSBzYXZpbmdzIG91dCB3aGVuIHlvdSBhcmUgcGFpZCwgYmVmb3JlIHNwZW5kaW5nIn0seyJpZCI6ImMiLCJsYWJlbCI6IlBheSB5b3VyIGRlYnRzIGxhc3QifSx7ImlkIjoiZCIsImxhYmVsIjoiU2F2ZSB3aGF0ZXZlciBpcyBsZWZ0IGF0IG1vbnRoIGVuZCJ9XSwicG9pbnRzIjoxMH0sCiAgICAgeyJpZCI6InE4IiwidHlwZSI6Im1jcSIsImxhYmVsIjoiTmVlZHMgYWJvdmUgNTAlIiwicHJvbXB0IjoiSWYgbmVlZHMgdGFrZSBtb3JlIHRoYW4gNTAlIG9mIHlvdXIgcGF5LCBhIHNlbnNpYmxlIHJlc3BvbnNlIGlzIHRv4oCmIiwib3B0aW9ucyI6W3siaWQiOiJhIiwibGFiZWwiOiJTdG9wIGJ1ZGdldGluZyJ9LHsiaWQiOiJiIiwibGFiZWwiOiJUcmltIHdhbnRzIG9yIHJhaXNlIGluY29tZSwgYW5kIGFkanVzdCB0aGUgc3BsaXQifSx7ImlkIjoiYyIsImxhYmVsIjoiQm9ycm93IHRvIGNvdmVyIHdhbnRzIn0seyJpZCI6ImQiLCJsYWJlbCI6IkNhbmNlbCBhbGwgc2F2aW5ncyBmb3JldmVyIn1dLCJwb2ludHMiOjEwfSwKICAgICB7ImlkIjoicTkiLCJ0eXBlIjoibnVtZXJpYyIsImxhYmVsIjoiU2F2aW5nIGEgeWVhciIsInByb21wdCI6IllvdSBzYXZlIOKCsTUsMDAwIGEgbW9udGggZm9yIDEyIG1vbnRocyAoaWdub3JlIGludGVyZXN0KS4gVG90YWwgc2F2ZWQgKOKCsSk/IiwidW5pdCI6IuKCsSIsInBvaW50cyI6MTB9LAogICAgIHsiaWQiOiJxMTAiLCJ0eXBlIjoibWNxIiwibGFiZWwiOiJUYWtlLWhvbWUgcGF5IiwicHJvbXB0IjoiVGFrZS1ob21lIHBheSBpc+KApiIsIm9wdGlvbnMiOlt7ImlkIjoiYSIsImxhYmVsIjoiWW91ciBwYXkgYmVmb3JlIHRheCJ9LHsiaWQiOiJiIiwibGFiZWwiOiJZb3VyIHBheSBhZnRlciB0YXggYW5kIG1hbmRhdG9yeSBjb250cmlidXRpb25zIn0seyJpZCI6ImMiLCJsYWJlbCI6IllvdXIgYm9udXMgb25seSJ9LHsiaWQiOiJkIiwibGFiZWwiOiJZb3VyIHNhdmluZ3MifV0sInBvaW50cyI6MTB9XQ==', 'base64'), 'UTF8')::jsonb,
 convert_from(decode('eyJxMSI6eyJhbnN3ZXIiOjE1MDAwLCJ0b2xlcmFuY2VfcGN0IjowLjV9LCJxMiI6eyJhbnN3ZXIiOjkwMDAsInRvbGVyYW5jZV9wY3QiOjAuNX0sInEzIjp7ImFuc3dlciI6NjAwMCwidG9sZXJhbmNlX3BjdCI6MC41fSwicTQiOnsiYW5zd2VyIjoiYiJ9LCJxNSI6eyJhbnN3ZXIiOiJjIn0sInE2Ijp7ImFuc3dlciI6NTcuNSwidG9sZXJhbmNlX3BjdCI6MC41fSwicTciOnsiYW5zd2VyIjoiYiJ9LCJxOCI6eyJhbnN3ZXIiOiJiIn0sInE5Ijp7ImFuc3dlciI6NjAwMDAsInRvbGVyYW5jZV9wY3QiOjAuNX0sInExMCI6eyJhbnN3ZXIiOiJiIn19', 'base64'), 'UTF8')::jsonb),
('compound-interest-saving',
 convert_from(decode('W3siaWQiOiJxMSIsInR5cGUiOiJudW1lcmljIiwibGFiZWwiOiJTaW1wbGUgaW50ZXJlc3QiLCJwcm9tcHQiOiLigrE1MCwwMDAgZWFybnMgNiUgc2ltcGxlIGludGVyZXN0IGZvciAzIHllYXJzLiBUb3RhbCBpbnRlcmVzdCAo4oKxKT8iLCJ1bml0Ijoi4oKxIiwicG9pbnRzIjoxMH0sCiAgICAgeyJpZCI6InEyIiwidHlwZSI6Im51bWVyaWMiLCJsYWJlbCI6IkNvbXBvdW5kIHZhbHVlIiwicHJvbXB0Ijoi4oKxNTAsMDAwIGF0IDYlIGNvbXBvdW5kZWQgYW5udWFsbHkgZm9yIDMgeWVhcnMgZ3Jvd3MgdG8gKOKCsSk/IiwidW5pdCI6IuKCsSIsInBvaW50cyI6MTB9LAogICAgIHsiaWQiOiJxMyIsInR5cGUiOiJudW1lcmljIiwibGFiZWwiOiJSdWxlIG9mIDcyIiwicHJvbXB0IjoiQXQgNiUgYSB5ZWFyLCBhYm91dCBob3cgbWFueSB5ZWFycyBkb2VzIG1vbmV5IHRha2UgdG8gZG91YmxlPyIsInVuaXQiOiJ5ZWFycyIsInBvaW50cyI6MTB9LAogICAgIHsiaWQiOiJxNCIsInR5cGUiOiJtY3EiLCJsYWJlbCI6IkNvbXBvdW5kaW5nIiwicHJvbXB0IjoiQ29tcG91bmQgaW50ZXJlc3QgbWVhbnMgaW50ZXJlc3QgaXMgZWFybmVkIG9u4oCmIiwib3B0aW9ucyI6W3siaWQiOiJhIiwibGFiZWwiOiJUaGUgb3JpZ2luYWwgYW1vdW50IG9ubHkifSx7ImlkIjoiYiIsImxhYmVsIjoiVGhlIG9yaWdpbmFsIGFtb3VudCBwbHVzIHByZXZpb3VzbHkgZWFybmVkIGludGVyZXN0In0seyJpZCI6ImMiLCJsYWJlbCI6IkluZmxhdGlvbiJ9LHsiaWQiOiJkIiwibGFiZWwiOiJUYXhlcyJ9XSwicG9pbnRzIjoxMH0sCiAgICAgeyJpZCI6InE1IiwidHlwZSI6Im51bWVyaWMiLCJsYWJlbCI6IkRvdWJsaW5nIiwicHJvbXB0IjoiVXNpbmcgdGhlIHJ1bGUgb2YgNzIsIOKCsTEwLDAwMCBhdCA4JSBmb3IgOSB5ZWFycyBncm93cyB0byByb3VnaGx5ICjigrEpPyIsInVuaXQiOiLigrEiLCJwb2ludHMiOjEwfSwKICAgICB7ImlkIjoicTYiLCJ0eXBlIjoibWNxIiwibGFiZWwiOiJTdGFydGluZyBlYXJseSIsInByb21wdCI6IlN0YXJ0aW5nIHRvIHNhdmUgZWFybGllciBoZWxwcyBiZWNhdXNl4oCmIiwib3B0aW9ucyI6W3siaWQiOiJhIiwibGFiZWwiOiJNb25leSBoYXMgbW9yZSB0aW1lIHRvIGNvbXBvdW5kIn0seyJpZCI6ImIiLCJsYWJlbCI6IkludGVyZXN0IHJhdGVzIGFyZSBoaWdoZXIgd2hlbiB5b3UgYXJlIHlvdW5nIn0seyJpZCI6ImMiLCJsYWJlbCI6IkJhbmtzIHBheSBib251c2VzIn0seyJpZCI6ImQiLCJsYWJlbCI6IlRheGVzIGRpc2FwcGVhciJ9XSwicG9pbnRzIjoxMH0sCiAgICAgeyJpZCI6InE3IiwidHlwZSI6Im51bWVyaWMiLCJsYWJlbCI6IkNvbnRyaWJ1dGlvbnMiLCJwcm9tcHQiOiJZb3UgZGVwb3NpdCDigrEyLDAwMCBldmVyeSBtb250aCBmb3IgYSB5ZWFyLiBUb3RhbCBjb250cmlidXRlZCAo4oKxKT8iLCJ1bml0Ijoi4oKxIiwicG9pbnRzIjoxMH0sCiAgICAgeyJpZCI6InE4IiwidHlwZSI6Im51bWVyaWMiLCJsYWJlbCI6IlJlYWwgcmV0dXJuIiwicHJvbXB0IjoiTm9taW5hbCByZXR1cm4gNyUsIGluZmxhdGlvbiAzJS4gQXBwcm94aW1hdGUgcmVhbCByZXR1cm4gKCUpPyIsInVuaXQiOiIlIiwicG9pbnRzIjoxMH0sCiAgICAgeyJpZCI6InE5IiwidHlwZSI6Im1jcSIsImxhYmVsIjoiSW5mbGF0aW9uIiwicHJvbXB0IjoiQSBzYXZpbmdzIGFjY291bnQgcGF5cyAxJSB3aGlsZSBpbmZsYXRpb24gaXMgNCUuIFlvdXIgcHVyY2hhc2luZyBwb3dlcuKApiIsIm9wdGlvbnMiOlt7ImlkIjoiYSIsImxhYmVsIjoiR3Jvd3MifSx7ImlkIjoiYiIsImxhYmVsIjoiRmFsbHMifSx7ImlkIjoiYyIsImxhYmVsIjoiU3RheXMgdGhlIHNhbWUifSx7ImlkIjoiZCIsImxhYmVsIjoiRG91YmxlcyJ9XSwicG9pbnRzIjoxMH0sCiAgICAgeyJpZCI6InExMCIsInR5cGUiOiJudW1lcmljIiwibGFiZWwiOiJUd28geWVhcnMiLCJwcm9tcHQiOiLigrEyMCwwMDAgYXQgMTAlIGNvbXBvdW5kZWQgYW5udWFsbHkgZm9yIDIgeWVhcnMgZ3Jvd3MgdG8gKOKCsSk/IiwidW5pdCI6IuKCsSIsInBvaW50cyI6MTB9XQ==', 'base64'), 'UTF8')::jsonb,
 convert_from(decode('eyJxMSI6eyJhbnN3ZXIiOjkwMDAsInRvbGVyYW5jZV9wY3QiOjAuNX0sInEyIjp7ImFuc3dlciI6NTk1NTEsInRvbGVyYW5jZV9wY3QiOjAuNX0sInEzIjp7ImFuc3dlciI6MTIsInRvbGVyYW5jZV9wY3QiOjF9LCJxNCI6eyJhbnN3ZXIiOiJiIn0sInE1Ijp7ImFuc3dlciI6MjAwMDAsInRvbGVyYW5jZV9wY3QiOjF9LCJxNiI6eyJhbnN3ZXIiOiJhIn0sInE3Ijp7ImFuc3dlciI6MjQwMDAsInRvbGVyYW5jZV9wY3QiOjAuNX0sInE4Ijp7ImFuc3dlciI6NCwidG9sZXJhbmNlX3BjdCI6NX0sInE5Ijp7ImFuc3dlciI6ImIifSwicTEwIjp7ImFuc3dlciI6MjQyMDAsInRvbGVyYW5jZV9wY3QiOjAuNX19', 'base64'), 'UTF8')::jsonb),
('investing-basics-funds',
 convert_from(decode('W3siaWQiOiJxMSIsInR5cGUiOiJtY3EiLCJsYWJlbCI6IlN0b2NrcyBhbmQgYm9uZHMiLCJwcm9tcHQiOiJTdG9ja3MgYW5kIGJvbmRzIGRpZmZlciBiZWNhdXNl4oCmIiwib3B0aW9ucyI6W3siaWQiOiJhIiwibGFiZWwiOiJTdG9ja2hvbGRlcnMgb3duIHBhcnQgb2YgdGhlIGNvbXBhbnk7IGJvbmRob2xkZXJzIGxlbmQgdG8gaXQifSx7ImlkIjoiYiIsImxhYmVsIjoiQm9uZHMgYXJlIGFsd2F5cyByaXNraWVyIn0seyJpZCI6ImMiLCJsYWJlbCI6IlN0b2NrcyBhbHdheXMgcGF5IGludGVyZXN0In0seyJpZCI6ImQiLCJsYWJlbCI6IlRoZXkgYXJlIHRoZSBzYW1lIn1dLCJwb2ludHMiOjEwfSwKICAgICB7ImlkIjoicTIiLCJ0eXBlIjoibWNxIiwibGFiZWwiOiJGdW5kcyIsInByb21wdCI6IkEgbXV0dWFsIGZ1bmQgb3IgRVRG4oCmIiwib3B0aW9ucyI6W3siaWQiOiJhIiwibGFiZWwiOiJIb2xkcyBhIGJhc2tldCBvZiBtYW55IHNlY3VyaXRpZXMifSx7ImlkIjoiYiIsImxhYmVsIjoiSXMgYSBzaW5nbGUgc3RvY2sifSx7ImlkIjoiYyIsImxhYmVsIjoiSXMgYSBzYXZpbmdzIGFjY291bnQifSx7ImlkIjoiZCIsImxhYmVsIjoiR3VhcmFudGVlcyByZXR1cm5zIn1dLCJwb2ludHMiOjEwfSwKICAgICB7ImlkIjoicTMiLCJ0eXBlIjoibWNxIiwibGFiZWwiOiJFVEYgdnMgbXV0dWFsIGZ1bmQiLCJwcm9tcHQiOiJBIGtleSBkaWZmZXJlbmNlIGlzIHRoYXQgRVRGc+KApiIsIm9wdGlvbnMiOlt7ImlkIjoiYSIsImxhYmVsIjoiVHJhZGUgb24gYW4gZXhjaGFuZ2UgdGhyb3VnaG91dCB0aGUgZGF5In0seyJpZCI6ImIiLCJsYWJlbCI6IkNhbiBvbmx5IGJlIGJvdWdodCBvbmNlIGEgeWVhciJ9LHsiaWQiOiJjIiwibGFiZWwiOiJIb2xkIG9ubHkgYm9uZHMifSx7ImlkIjoiZCIsImxhYmVsIjoiSGF2ZSBubyBmZWVzIn1dLCJwb2ludHMiOjEwfSwKICAgICB7ImlkIjoicTQiLCJ0eXBlIjoibnVtZXJpYyIsImxhYmVsIjoiQ291cG9uIiwicHJvbXB0IjoiQSBib25kIGhhcyBhIGZhY2UgdmFsdWUgb2Yg4oKxMTAwLDAwMCBhbmQgYSA2JSBhbm51YWwgY291cG9uLiBBbm51YWwgaW50ZXJlc3QgKOKCsSk/IiwidW5pdCI6IuKCsSIsInBvaW50cyI6MTB9LAogICAgIHsiaWQiOiJxNSIsInR5cGUiOiJtY3EiLCJsYWJlbCI6IlJpc2sgYW5kIHJldHVybiIsInByb21wdCI6IkhpZ2hlciBwb3RlbnRpYWwgcmV0dXJucyBnZW5lcmFsbHkgY29tZSB3aXRo4oCmIiwib3B0aW9ucyI6W3siaWQiOiJhIiwibGFiZWwiOiJIaWdoZXIgcmlzayJ9LHsiaWQiOiJiIiwibGFiZWwiOiJMb3dlciByaXNrIn0seyJpZCI6ImMiLCJsYWJlbCI6Ik5vIHJpc2sifSx7ImlkIjoiZCIsImxhYmVsIjoiR3VhcmFudGVlZCBnYWlucyJ9XSwicG9pbnRzIjoxMH0sCiAgICAgeyJpZCI6InE2IiwidHlwZSI6Im51bWVyaWMiLCJsYWJlbCI6IkZlZXMiLCJwcm9tcHQiOiJBIGZ1bmQgY2hhcmdlcyBhIDEuNSUgZXhwZW5zZSByYXRpbyBvbiDigrEyMDAsMDAwLiBBbm51YWwgZmVlICjigrEpPyIsInVuaXQiOiLigrEiLCJwb2ludHMiOjEwfSwKICAgICB7ImlkIjoicTciLCJ0eXBlIjoibWNxIiwibGFiZWwiOiJEaXZlcnNpZmljYXRpb24iLCJwcm9tcHQiOiJEaXZlcnNpZmljYXRpb24gbWVhbnPigKYiLCJvcHRpb25zIjpbeyJpZCI6ImEiLCJsYWJlbCI6IlB1dHRpbmcgZXZlcnl0aGluZyBpbiBvbmUgc3RvY2sifSx7ImlkIjoiYiIsImxhYmVsIjoiU3ByZWFkaW5nIG1vbmV5IHNvIG5vIHNpbmdsZSBpbnZlc3RtZW50IGNhbiBzaW5rIHlvdSJ9LHsiaWQiOiJjIiwibGFiZWwiOiJUcmFkaW5nIGRhaWx5In0seyJpZCI6ImQiLCJsYWJlbCI6IkF2b2lkaW5nIGFsbCByaXNrIn1dLCJwb2ludHMiOjEwfSwKICAgICB7ImlkIjoicTgiLCJ0eXBlIjoibWNxIiwibGFiZWwiOiJUaW1lIGhvcml6b24iLCJwcm9tcHQiOiJNb25leSB5b3UgbmVlZCB3aXRoaW4gMiB5ZWFycyBzaG91bGQgdXN1YWxseSBiZSBpbuKApiIsIm9wdGlvbnMiOlt7ImlkIjoiYSIsImxhYmVsIjoiVm9sYXRpbGUgc3RvY2tzIn0seyJpZCI6ImIiLCJsYWJlbCI6Ikxvdy1yaXNrLCBhY2Nlc3NpYmxlIGFzc2V0cyJ9LHsiaWQiOiJjIiwibGFiZWwiOiJBIHNpbmdsZSBzcGVjdWxhdGl2ZSBhc3NldCJ9LHsiaWQiOiJkIiwibGFiZWwiOiJXaGF0ZXZlciBpcyB0cmVuZGluZyJ9XSwicG9pbnRzIjoxMH0sCiAgICAgeyJpZCI6InE5IiwidHlwZSI6Im51bWVyaWMiLCJsYWJlbCI6IkRpdmlkZW5kIHlpZWxkIiwicHJvbXB0IjoiQSBzdG9jayBwYXlzIOKCsTMgYSB5ZWFyIGluIGRpdmlkZW5kcyBhbmQgdHJhZGVzIGF0IOKCsTYwLiBEaXZpZGVuZCB5aWVsZCAoJSk/IiwidW5pdCI6IiUiLCJwb2ludHMiOjEwfSwKICAgICB7ImlkIjoicTEwIiwidHlwZSI6Im1jcSIsImxhYmVsIjoiQ29zdCBhdmVyYWdpbmciLCJwcm9tcHQiOiJQZXNvLWNvc3QgYXZlcmFnaW5nIG1lYW5z4oCmIiwib3B0aW9ucyI6W3siaWQiOiJhIiwibGFiZWwiOiJJbnZlc3RpbmcgYSBmaXhlZCBhbW91bnQgYXQgcmVndWxhciBpbnRlcnZhbHMifSx7ImlkIjoiYiIsImxhYmVsIjoiSW52ZXN0aW5nIGV2ZXJ5dGhpbmcgYXQgdGhlIG1hcmtldCBsb3cifSx7ImlkIjoiYyIsImxhYmVsIjoiU2VsbGluZyB3aGVuIHByaWNlcyBmYWxsIn0seyJpZCI6ImQiLCJsYWJlbCI6IkF2b2lkaW5nIGludmVzdGluZyJ9XSwicG9pbnRzIjoxMH1d', 'base64'), 'UTF8')::jsonb,
 convert_from(decode('eyJxMSI6eyJhbnN3ZXIiOiJhIn0sInEyIjp7ImFuc3dlciI6ImEifSwicTMiOnsiYW5zd2VyIjoiYSJ9LCJxNCI6eyJhbnN3ZXIiOjYwMDAsInRvbGVyYW5jZV9wY3QiOjAuNX0sInE1Ijp7ImFuc3dlciI6ImEifSwicTYiOnsiYW5zd2VyIjozMDAwLCJ0b2xlcmFuY2VfcGN0IjowLjV9LCJxNyI6eyJhbnN3ZXIiOiJiIn0sInE4Ijp7ImFuc3dlciI6ImIifSwicTkiOnsiYW5zd2VyIjo1LCJ0b2xlcmFuY2VfcGN0IjowLjV9LCJxMTAiOnsiYW5zd2VyIjoiYSJ9fQ==', 'base64'), 'UTF8')::jsonb),
('emergency-fund-inflation',
 convert_from(decode('W3siaWQiOiJxMSIsInR5cGUiOiJudW1lcmljIiwibGFiZWwiOiJTaXggbW9udGhzIiwicHJvbXB0IjoiRXNzZW50aWFsIGV4cGVuc2VzIGFyZSDigrEyNSwwMDAgYSBtb250aC4gQSA2LW1vbnRoIGVtZXJnZW5jeSBmdW5kICjigrEpPyIsInVuaXQiOiLigrEiLCJwb2ludHMiOjEwfSwKICAgICB7ImlkIjoicTIiLCJ0eXBlIjoibnVtZXJpYyIsImxhYmVsIjoiVGhyZWUgbW9udGhzIiwicHJvbXB0IjoiQSAzLW1vbnRoIGVtZXJnZW5jeSBmdW5kIG9uIHRoZSBzYW1lIGV4cGVuc2VzICjigrEpPyIsInVuaXQiOiLigrEiLCJwb2ludHMiOjEwfSwKICAgICB7ImlkIjoicTMiLCJ0eXBlIjoibWNxIiwibGFiZWwiOiJXaGVyZSB0byBrZWVwIGl0IiwicHJvbXB0IjoiQW4gZW1lcmdlbmN5IGZ1bmQgaXMgYmVzdCBrZXB0IGlu4oCmIiwib3B0aW9ucyI6W3siaWQiOiJhIiwibGFiZWwiOiJBIHZvbGF0aWxlIHN0b2NrIn0seyJpZCI6ImIiLCJsYWJlbCI6IkEgc2FmZSwgYWNjZXNzaWJsZSBhY2NvdW50IHN1Y2ggYXMgc2F2aW5ncyBvciBhIG1vbmV5LW1hcmtldCBmdW5kIn0seyJpZCI6ImMiLCJsYWJlbCI6IkNyeXB0b2N1cnJlbmN5In0seyJpZCI6ImQiLCJsYWJlbCI6IkEgbG9uZyBsb2NrLWluIGludmVzdG1lbnQifV0sInBvaW50cyI6MTB9LAogICAgIHsiaWQiOiJxNCIsInR5cGUiOiJtY3EiLCJsYWJlbCI6IkluZmxhdGlvbiIsInByb21wdCI6IkluZmxhdGlvbuKApiIsIm9wdGlvbnMiOlt7ImlkIjoiYSIsImxhYmVsIjoiUmFpc2VzIHRoZSBwdXJjaGFzaW5nIHBvd2VyIG9mIGNhc2gifSx7ImlkIjoiYiIsImxhYmVsIjoiRXJvZGVzIHRoZSBwdXJjaGFzaW5nIHBvd2VyIG9mIGNhc2gifSx7ImlkIjoiYyIsImxhYmVsIjoiSGFzIG5vIGVmZmVjdCBvbiBzYXZpbmdzIn0seyJpZCI6ImQiLCJsYWJlbCI6Ik9ubHkgYWZmZWN0cyBzdG9ja3MifV0sInBvaW50cyI6MTB9LAogICAgIHsiaWQiOiJxNSIsInR5cGUiOiJudW1lcmljIiwibGFiZWwiOiJQdXJjaGFzaW5nIHBvd2VyIiwicHJvbXB0Ijoi4oKxMTAwLDAwMCBpbiBjYXNoIGFuZCA0JSBpbmZsYXRpb246IGl0cyBwdXJjaGFzaW5nIHBvd2VyIGEgeWVhciBmcm9tIG5vdywgaW4gdG9kYXkncyBwZXNvcywgaXMgYWJvdXQgKOKCsSk/IiwidW5pdCI6IuKCsSIsInBvaW50cyI6MTB9LAogICAgIHsiaWQiOiJxNiIsInR5cGUiOiJtY3EiLCJsYWJlbCI6IlByaW9yaXRpZXMiLCJwcm9tcHQiOiJCZWZvcmUgaW52ZXN0aW5nIGFnZ3Jlc3NpdmVseSB5b3Ugc2hvdWxkIGZpcnN04oCmIiwib3B0aW9ucyI6W3siaWQiOiJhIiwibGFiZWwiOiJCdWlsZCBhIHN0YXJ0ZXIgZW1lcmdlbmN5IGZ1bmQifSx7ImlkIjoiYiIsImxhYmVsIjoiQnV5IHRoZSBuZXdlc3QgcGhvbmUifSx7ImlkIjoiYyIsImxhYmVsIjoiQm9ycm93IHRvIGludmVzdCJ9LHsiaWQiOiJkIiwibGFiZWwiOiJTdG9wIHNhdmluZyJ9XSwicG9pbnRzIjoxMH0sCiAgICAgeyJpZCI6InE3IiwidHlwZSI6Im51bWVyaWMiLCJsYWJlbCI6IlRpbWUgdG8gZ29hbCIsInByb21wdCI6IllvdSBzYXZlIOKCsTMsMDAwIGEgbW9udGggdG93YXJkIGEg4oKxOTAsMDAwIHRhcmdldCAoaWdub3JlIGludGVyZXN0KS4gTW9udGhzIG5lZWRlZD8iLCJ1bml0IjoibW9udGhzIiwicG9pbnRzIjoxMH0sCiAgICAgeyJpZCI6InE4IiwidHlwZSI6Im1jcSIsImxhYmVsIjoiQmlnZ2VyIGZ1bmQiLCJwcm9tcHQiOiJXaG8gdHlwaWNhbGx5IG5lZWRzIGEgYmlnZ2VyIGVtZXJnZW5jeSBmdW5kPyIsIm9wdGlvbnMiOlt7ImlkIjoiYSIsImxhYmVsIjoiQSBmcmVlbGFuY2VyIHdpdGggaXJyZWd1bGFyIGluY29tZSJ9LHsiaWQiOiJiIiwibGFiZWwiOiJTb21lb25lIHdpdGggYSB2ZXJ5IHN0YWJsZSBzYWxhcnkgYW5kIG5vIGRlcGVuZGFudHMifSx7ImlkIjoiYyIsImxhYmVsIjoiTm8gb25lIn0seyJpZCI6ImQiLCJsYWJlbCI6Ik9ubHkgcmV0aXJlZXMifV0sInBvaW50cyI6MTB9LAogICAgIHsiaWQiOiJxOSIsInR5cGUiOiJudW1lcmljIiwibGFiZWwiOiJSZWFsIHJldHVybiIsInByb21wdCI6IkEgc2F2aW5ncyBhY2NvdW50IHBheXMgMiUgd2hpbGUgaW5mbGF0aW9uIGlzIDQlLiBSZWFsIHJldHVybiAoJSwgbmVnYXRpdmUgaWYgeW91IGxvc2UpPyIsInVuaXQiOiIlIiwicG9pbnRzIjoxMH0sCiAgICAgeyJpZCI6InExMCIsInR5cGUiOiJtY3EiLCJsYWJlbCI6IkhpZ2gtaW50ZXJlc3QgZGVidCIsInByb21wdCI6IkEgY3JlZGl0IGNhcmQgY2hhcmdpbmcgMyUgYSBtb250aCBzaG91bGQgZ2VuZXJhbGx5IGJl4oCmIiwib3B0aW9ucyI6W3siaWQiOiJhIiwibGFiZWwiOiJQYWlkIG9mZiBiZWZvcmUgaW52ZXN0aW5nIGZvciBtb2Rlc3QgcmV0dXJucyJ9LHsiaWQiOiJiIiwibGFiZWwiOiJJZ25vcmVkIn0seyJpZCI6ImMiLCJsYWJlbCI6IkluY3JlYXNlZCJ9LHsiaWQiOiJkIiwibGFiZWwiOiJSZWZpbmFuY2VkIGludG8gYSBsb25nZXIgY2FyZCJ9XSwicG9pbnRzIjoxMH1d', 'base64'), 'UTF8')::jsonb,
 convert_from(decode('eyJxMSI6eyJhbnN3ZXIiOjE1MDAwMCwidG9sZXJhbmNlX3BjdCI6MC41fSwicTIiOnsiYW5zd2VyIjo3NTAwMCwidG9sZXJhbmNlX3BjdCI6MC41fSwicTMiOnsiYW5zd2VyIjoiYiJ9LCJxNCI6eyJhbnN3ZXIiOiJiIn0sInE1Ijp7ImFuc3dlciI6OTYxNTQsInRvbGVyYW5jZV9wY3QiOjAuNX0sInE2Ijp7ImFuc3dlciI6ImEifSwicTciOnsiYW5zd2VyIjozMCwidG9sZXJhbmNlX3BjdCI6MC41fSwicTgiOnsiYW5zd2VyIjoiYSJ9LCJxOSI6eyJhbnN3ZXIiOi0yLCJ0b2xlcmFuY2VfcGN0IjowLjV9LCJxMTAiOnsiYW5zd2VyIjoiYSJ9fQ==', 'base64'), 'UTF8')::jsonb),
('interview-three-statements',
 convert_from(decode('W3siaWQiOiJxMSIsInR5cGUiOiJudW1lcmljIiwibGFiZWwiOiJOZXQgaW5jb21lIiwicHJvbXB0IjoiRGVwcmVjaWF0aW9uIHJpc2VzIGJ5IOKCsTEwIGFuZCB0aGUgdGF4IHJhdGUgaXMgMjUlLiBOZXQgaW5jb21lIGZhbGxzIGJ5ICjigrEpPyIsInVuaXQiOiLigrEiLCJwb2ludHMiOjEwfSwKICAgICB7ImlkIjoicTIiLCJ0eXBlIjoibnVtZXJpYyIsImxhYmVsIjoiQ2FzaCIsInByb21wdCI6IlNhbWUgZmFjdHM6IGNhc2ggZnJvbSBvcGVyYXRpb25zIGNoYW5nZXMgYnkgKOKCsSwgcG9zaXRpdmUgaWYgaXQgcmlzZXMpPyIsInVuaXQiOiLigrEiLCJwb2ludHMiOjEwfSwKICAgICB7ImlkIjoicTMiLCJ0eXBlIjoibnVtZXJpYyIsImxhYmVsIjoiUFAmRSIsInByb21wdCI6IlNhbWUgZmFjdHM6IFBQJkUgZmFsbHMgYnkgKOKCsSk/IiwidW5pdCI6IuKCsSIsInBvaW50cyI6MTB9LAogICAgIHsiaWQiOiJxNCIsInR5cGUiOiJtY3EiLCJsYWJlbCI6IlN0YXJ0aW5nIHBvaW50IiwicHJvbXB0IjoiTmV0IGluY29tZSBpcyB0aGUgc3RhcnRpbmcgbGluZSBvZiB3aGljaCBzdGF0ZW1lbnQgKGluZGlyZWN0IG1ldGhvZCk/Iiwib3B0aW9ucyI6W3siaWQiOiJhIiwibGFiZWwiOiJUaGUgYmFsYW5jZSBzaGVldCJ9LHsiaWQiOiJiIiwibGFiZWwiOiJUaGUgY2FzaCBmbG93IHN0YXRlbWVudCJ9LHsiaWQiOiJjIiwibGFiZWwiOiJUaGUgc3RhdGVtZW50IG9mIGVxdWl0eSBvbmx5In0seyJpZCI6ImQiLCJsYWJlbCI6Ik5vbmUgb2YgdGhlbSJ9XSwicG9pbnRzIjoxMH0sCiAgICAgeyJpZCI6InE1IiwidHlwZSI6Im1jcSIsImxhYmVsIjoiUmVjZWl2YWJsZXMiLCJwcm9tcHQiOiJBbiBpbmNyZWFzZSBpbiBhY2NvdW50cyByZWNlaXZhYmxl4oCmIiwib3B0aW9ucyI6W3siaWQiOiJhIiwibGFiZWwiOiJSYWlzZXMgb3BlcmF0aW5nIGNhc2ggZmxvdyJ9LHsiaWQiOiJiIiwibGFiZWwiOiJMb3dlcnMgb3BlcmF0aW5nIGNhc2ggZmxvdyJ9LHsiaWQiOiJjIiwibGFiZWwiOiJIYXMgbm8gY2FzaCBlZmZlY3QifSx7ImlkIjoiZCIsImxhYmVsIjoiSXMgYSBmaW5hbmNpbmcgaXRlbSJ9XSwicG9pbnRzIjoxMH0sCiAgICAgeyJpZCI6InE2IiwidHlwZSI6Im51bWVyaWMiLCJsYWJlbCI6IkJ1eWluZyBlcXVpcG1lbnQiLCJwcm9tcHQiOiJBIGNvbXBhbnkgYnV5cyDigrExMDAgb2YgZXF1aXBtZW50IHdpdGggY2FzaC4gVGhlIGNoYW5nZSBpbiB0b3RhbCBhc3NldHMgKOKCsSk/IiwidW5pdCI6IuKCsSIsInBvaW50cyI6MTB9LAogICAgIHsiaWQiOiJxNyIsInR5cGUiOiJtY3EiLCJsYWJlbCI6IkJvcnJvd2luZyIsInByb21wdCI6IkEgY29tcGFueSBib3Jyb3dzIOKCsTEwMCBhbmQgdXNlcyBpdCB0byBidXkgaW52ZW50b3J5LiBXaGljaCBpcyBjb3JyZWN0PyIsIm9wdGlvbnMiOlt7ImlkIjoiYSIsImxhYmVsIjoiQXNzZXRzIGFuZCBsaWFiaWxpdGllcyBib3RoIHJpc2UgYnkg4oKxMTAwIn0seyJpZCI6ImIiLCJsYWJlbCI6Ik9ubHkgYXNzZXRzIHJpc2UifSx7ImlkIjoiYyIsImxhYmVsIjoiRXF1aXR5IHJpc2VzIGJ5IOKCsTEwMCJ9LHsiaWQiOiJkIiwibGFiZWwiOiJOb3RoaW5nIGNoYW5nZXMifV0sInBvaW50cyI6MTB9LAogICAgIHsiaWQiOiJxOCIsInR5cGUiOiJtY3EiLCJsYWJlbCI6IkxpbmtpbmciLCJwcm9tcHQiOiJXaGljaCBzdGF0ZW1lbnQgY29ubmVjdHMgcHJvZml0IHRvIHRoZSBjaGFuZ2UgaW4gY2FzaCBvbiB0aGUgYmFsYW5jZSBzaGVldD8iLCJvcHRpb25zIjpbeyJpZCI6ImEiLCJsYWJlbCI6IlRoZSBjYXNoIGZsb3cgc3RhdGVtZW50In0seyJpZCI6ImIiLCJsYWJlbCI6IlRoZSBpbmNvbWUgc3RhdGVtZW50IGFsb25lIn0seyJpZCI6ImMiLCJsYWJlbCI6IlRoZSBub3RlcyB0byB0aGUgYWNjb3VudHMifSx7ImlkIjoiZCIsImxhYmVsIjoiVGhlIHRheCByZXR1cm4ifV0sInBvaW50cyI6MTB9LAogICAgIHsiaWQiOiJxOSIsInR5cGUiOiJudW1lcmljIiwibGFiZWwiOiJXcml0ZS1kb3duIiwicHJvbXB0IjoiQSDigrEyMCBpbnZlbnRvcnkgd3JpdGUtZG93biB3aXRoIGEgMjUlIHRheCByYXRlIHJlZHVjZXMgbmV0IGluY29tZSBieSAo4oKxKT8iLCJ1bml0Ijoi4oKxIiwicG9pbnRzIjoxMH0sCiAgICAgeyJpZCI6InExMCIsInR5cGUiOiJtY3EiLCJsYWJlbCI6IlJldGFpbmVkIGVhcm5pbmdzIiwicHJvbXB0IjoiUmV0YWluZWQgZWFybmluZ3MgY2hhbmdlIGJ54oCmIiwib3B0aW9ucyI6W3siaWQiOiJhIiwibGFiZWwiOiJOZXQgaW5jb21lIG1pbnVzIGRpdmlkZW5kcyJ9LHsiaWQiOiJiIiwibGFiZWwiOiJSZXZlbnVlIG1pbnVzIGNvc3RzIG9mIGdvb2RzIHNvbGQifSx7ImlkIjoiYyIsImxhYmVsIjoiQ2FzaCBmbG93IGZyb20gb3BlcmF0aW9ucyJ9LHsiaWQiOiJkIiwibGFiZWwiOiJUb3RhbCBhc3NldHMifV0sInBvaW50cyI6MTB9XQ==', 'base64'), 'UTF8')::jsonb,
 convert_from(decode('eyJxMSI6eyJhbnN3ZXIiOjcuNSwidG9sZXJhbmNlX3BjdCI6MC41fSwicTIiOnsiYW5zd2VyIjoyLjUsInRvbGVyYW5jZV9wY3QiOjAuNX0sInEzIjp7ImFuc3dlciI6MTAsInRvbGVyYW5jZV9wY3QiOjAuNX0sInE0Ijp7ImFuc3dlciI6ImIifSwicTUiOnsiYW5zd2VyIjoiYiJ9LCJxNiI6eyJhbnN3ZXIiOjAsInRvbGVyYW5jZV9hYnMiOjAuMDF9LCJxNyI6eyJhbnN3ZXIiOiJhIn0sInE4Ijp7ImFuc3dlciI6ImEifSwicTkiOnsiYW5zd2VyIjoxNSwidG9sZXJhbmNlX3BjdCI6MC41fSwicTEwIjp7ImFuc3dlciI6ImEifX0=', 'base64'), 'UTF8')::jsonb),
('interview-dcf-walkthrough',
 convert_from(decode('W3siaWQiOiJxMSIsInR5cGUiOiJudW1lcmljIiwibGFiZWwiOiJVRkNGIiwicHJvbXB0IjoiRUJJVCDigrEyMDA7IHRheCAyNSU7IEQmQSDigrE1MDsgY2FwZXgg4oKxNzA7IGluY3JlYXNlIGluIE5XQyDigrExMC4gVW5sZXZlcmVkIGZyZWUgY2FzaCBmbG93ICjigrEpPyIsInVuaXQiOiLigrEiLCJwb2ludHMiOjEwfSwKICAgICB7ImlkIjoicTIiLCJ0eXBlIjoibnVtZXJpYyIsImxhYmVsIjoiVGVybWluYWwgdmFsdWUiLCJwcm9tcHQiOiJGaW5hbC15ZWFyIEZDRiDigrExMjA7IGdyb3d0aCAzJTsgV0FDQyA5JS4gVGVybWluYWwgdmFsdWUgYnkgR29yZG9uIGdyb3d0aCAo4oKxKT8iLCJ1bml0Ijoi4oKxIiwicG9pbnRzIjoxMH0sCiAgICAgeyJpZCI6InEzIiwidHlwZSI6Im51bWVyaWMiLCJsYWJlbCI6IlBWIG9mIFRWIiwicHJvbXB0IjoiVGhhdCB0ZXJtaW5hbCB2YWx1ZSBpcyBhdCB0aGUgZW5kIG9mIHllYXIgNS4gSXRzIHByZXNlbnQgdmFsdWUgYXQgOSUgKOKCsSwgb25lIGRlY2ltYWwpPyIsInVuaXQiOiLigrEiLCJwb2ludHMiOjEwfSwKICAgICB7ImlkIjoicTQiLCJ0eXBlIjoibWNxIiwibGFiZWwiOiJEaXNjb3VudCByYXRlIiwicHJvbXB0IjoiVW5sZXZlcmVkIGZyZWUgY2FzaCBmbG93cyBhcmUgZGlzY291bnRlZCBhdCB0aGXigKYiLCJvcHRpb25zIjpbeyJpZCI6ImEiLCJsYWJlbCI6IkNvc3Qgb2YgZXF1aXR5In0seyJpZCI6ImIiLCJsYWJlbCI6IldBQ0MifSx7ImlkIjoiYyIsImxhYmVsIjoiUmlzay1mcmVlIHJhdGUifSx7ImlkIjoiZCIsImxhYmVsIjoiSW5mbGF0aW9uIHJhdGUifV0sInBvaW50cyI6MTB9LAogICAgIHsiaWQiOiJxNSIsInR5cGUiOiJtY3EiLCJsYWJlbCI6IkVxdWl0eSBicmlkZ2UiLCJwcm9tcHQiOiJUbyBnbyBmcm9tIGVudGVycHJpc2UgdmFsdWUgdG8gZXF1aXR5IHZhbHVlIHlvdeKApiIsIm9wdGlvbnMiOlt7ImlkIjoiYSIsImxhYmVsIjoiQWRkIG5ldCBkZWJ0In0seyJpZCI6ImIiLCJsYWJlbCI6IlN1YnRyYWN0IG5ldCBkZWJ0In0seyJpZCI6ImMiLCJsYWJlbCI6Ik11bHRpcGx5IGJ5IHRoZSB0YXggcmF0ZSJ9LHsiaWQiOiJkIiwibGFiZWwiOiJBZGQgdGhlIHRlcm1pbmFsIHZhbHVlIGFnYWluIn1dLCJwb2ludHMiOjEwfSwKICAgICB7ImlkIjoicTYiLCJ0eXBlIjoibnVtZXJpYyIsImxhYmVsIjoiUHJpY2UgcGVyIHNoYXJlIiwicHJvbXB0IjoiRVYg4oKxMSw1MDA7IG5ldCBkZWJ0IOKCsTQwMDsgNTAgc2hhcmVzLiBJbXBsaWVkIHZhbHVlIHBlciBzaGFyZSAo4oKxKT8iLCJ1bml0Ijoi4oKxIiwicG9pbnRzIjoxMH0sCiAgICAgeyJpZCI6InE3IiwidHlwZSI6Im1jcSIsImxhYmVsIjoiVGVybWluYWwgdmFsdWUgc2hhcmUiLCJwcm9tcHQiOiJUZXJtaW5hbCB2YWx1ZSBpcyBvZnRlbiBhIGxhcmdlIHNoYXJlIG9mIEVWIGJlY2F1c2XigKYiLCJvcHRpb25zIjpbeyJpZCI6ImEiLCJsYWJlbCI6Ik1vc3QgdmFsdWUgYXJpc2VzIGJleW9uZCB0aGUgZXhwbGljaXQgZm9yZWNhc3QgcGVyaW9kIn0seyJpZCI6ImIiLCJsYWJlbCI6Ikl0IGlzIGFsd2F5cyB3cm9uZyJ9LHsiaWQiOiJjIiwibGFiZWwiOiJJdCBpZ25vcmVzIGdyb3d0aCJ9LHsiaWQiOiJkIiwibGFiZWwiOiJGb3JlY2FzdHMgYXJlIHRvbyBsb25nIn1dLCJwb2ludHMiOjEwfSwKICAgICB7ImlkIjoicTgiLCJ0eXBlIjoibWNxIiwibGFiZWwiOiJDb25zaXN0ZW5jeSIsInByb21wdCI6IkRpc2NvdW50aW5nIGxldmVyZWQgZnJlZSBjYXNoIGZsb3dzIGF0IFdBQ0MgaXPigKYiLCJvcHRpb25zIjpbeyJpZCI6ImEiLCJsYWJlbCI6IlRoZSBzdGFuZGFyZCBtZXRob2QifSx7ImlkIjoiYiIsImxhYmVsIjoiQW4gaW5jb25zaXN0ZW5jeSB0aGF0IG1ha2VzIHRoZSB2YWx1YXRpb24gd3JvbmcifSx7ImlkIjoiYyIsImxhYmVsIjoiUmVxdWlyZWQgYnkgSUZSUyJ9LHsiaWQiOiJkIiwibGFiZWwiOiJPbmx5IHdyb25nIGZvciBiYW5rcyJ9XSwicG9pbnRzIjoxMH0sCiAgICAgeyJpZCI6InE5IiwidHlwZSI6Im1jcSIsImxhYmVsIjoiV0FDQyBjaGFuZ2UiLCJwcm9tcHQiOiJJZiBXQUNDIHJpc2VzLCBEQ0YgdmFsdWXigKYiLCJvcHRpb25zIjpbeyJpZCI6ImEiLCJsYWJlbCI6IlJpc2VzIn0seyJpZCI6ImIiLCJsYWJlbCI6IkZhbGxzIn0seyJpZCI6ImMiLCJsYWJlbCI6IlN0YXlzIHRoZSBzYW1lIn0seyJpZCI6ImQiLCJsYWJlbCI6IkJlY29tZXMgbmVnYXRpdmUifV0sInBvaW50cyI6MTB9LAogICAgIHsiaWQiOiJxMTAiLCJ0eXBlIjoibnVtZXJpYyIsImxhYmVsIjoiUHJlc2VudCB2YWx1ZSIsInByb21wdCI6IkZyZWUgY2FzaCBmbG93IGluIHllYXIgMyBpcyDigrExMzAgYW5kIFdBQ0MgaXMgMTAlLiBJdHMgcHJlc2VudCB2YWx1ZSAo4oKxLCB0d28gZGVjaW1hbHMpPyIsInVuaXQiOiLigrEiLCJwb2ludHMiOjEwfV0=', 'base64'), 'UTF8')::jsonb,
 convert_from(decode('eyJxMSI6eyJhbnN3ZXIiOjEyMCwidG9sZXJhbmNlX3BjdCI6MC41fSwicTIiOnsiYW5zd2VyIjoyMDYwLCJ0b2xlcmFuY2VfcGN0IjowLjV9LCJxMyI6eyJhbnN3ZXIiOjEzMzguOSwidG9sZXJhbmNlX3BjdCI6MC41fSwicTQiOnsiYW5zd2VyIjoiYiJ9LCJxNSI6eyJhbnN3ZXIiOiJiIn0sInE2Ijp7ImFuc3dlciI6MjIsInRvbGVyYW5jZV9wY3QiOjAuNX0sInE3Ijp7ImFuc3dlciI6ImEifSwicTgiOnsiYW5zd2VyIjoiYiJ9LCJxOSI6eyJhbnN3ZXIiOiJiIn0sInExMCI6eyJhbnN3ZXIiOjk3LjY3LCJ0b2xlcmFuY2VfcGN0IjowLjV9fQ==', 'base64'), 'UTF8')::jsonb),
('interview-ev-equity',
 convert_from(decode('W3siaWQiOiJxMSIsInR5cGUiOiJudW1lcmljIiwibGFiZWwiOiJFcXVpdHkgdmFsdWUiLCJwcm9tcHQiOiJTaGFyZSBwcmljZSDigrE1MDsgZGlsdXRlZCBzaGFyZXMgMjAgbWlsbGlvbi4gRXF1aXR5IHZhbHVlICjigrFtKT8iLCJ1bml0Ijoi4oKxbSIsInBvaW50cyI6MTB9LAogICAgIHsiaWQiOiJxMiIsInR5cGUiOiJudW1lcmljIiwibGFiZWwiOiJFbnRlcnByaXNlIHZhbHVlIiwicHJvbXB0IjoiRXF1aXR5IHZhbHVlIOKCsTEsMDAwbTsgZGVidCDigrE0MDBtOyBjYXNoIOKCsTE1MG0gKG5vIHByZWZlcnJlZCBvciBtaW5vcml0aWVzKS4gRW50ZXJwcmlzZSB2YWx1ZSAo4oKxbSk/IiwidW5pdCI6IuKCsW0iLCJwb2ludHMiOjEwfSwKICAgICB7ImlkIjoicTMiLCJ0eXBlIjoibWNxIiwibGFiZWwiOiJXaHkgc3VidHJhY3QgY2FzaCIsInByb21wdCI6IkNhc2ggaXMgc3VidHJhY3RlZCB0byBnZXQgZW50ZXJwcmlzZSB2YWx1ZSBiZWNhdXNl4oCmIiwib3B0aW9ucyI6W3siaWQiOiJhIiwibGFiZWwiOiJJdCBpcyBub3QgcGFydCBvZiB0aGUgb3BlcmF0aW5nIGJ1c2luZXNzIGFuZCBvZmZzZXRzIHRoZSBwcmljZSBhIGJ1eWVyIHBheXMifSx7ImlkIjoiYiIsImxhYmVsIjoiQ2FzaCBpcyBhIGxpYWJpbGl0eSJ9LHsiaWQiOiJjIiwibGFiZWwiOiJDYXNoIGlzIHRheGVkIn0seyJpZCI6ImQiLCJsYWJlbCI6Ikl0IGlzIGFsd2F5cyB6ZXJvIn1dLCJwb2ludHMiOjEwfSwKICAgICB7ImlkIjoicTQiLCJ0eXBlIjoibWNxIiwibGFiZWwiOiJQYWlyaW5nIiwicHJvbXB0IjoiV2hpY2ggcGFpcmluZyBpcyBjb3JyZWN0PyIsIm9wdGlvbnMiOlt7ImlkIjoiYSIsImxhYmVsIjoiRVYgd2l0aCBFQklUREE7IGVxdWl0eSB2YWx1ZSB3aXRoIG5ldCBpbmNvbWUifSx7ImlkIjoiYiIsImxhYmVsIjoiRVYgd2l0aCBuZXQgaW5jb21lOyBlcXVpdHkgdmFsdWUgd2l0aCBFQklUREEifSx7ImlkIjoiYyIsImxhYmVsIjoiRXF1aXR5IHZhbHVlIHdpdGggcmV2ZW51ZSBvbmx5In0seyJpZCI6ImQiLCJsYWJlbCI6IkVWIHdpdGggZGl2aWRlbmRzIn1dLCJwb2ludHMiOjEwfSwKICAgICB7ImlkIjoicTUiLCJ0eXBlIjoibnVtZXJpYyIsImxhYmVsIjoiRVYvRUJJVERBIiwicHJvbXB0IjoiRVYg4oKxMSwyNTBtOyBFQklUREEg4oKxMjUwbS4gRVYvRUJJVERBICh4KT8iLCJ1bml0IjoieCIsInBvaW50cyI6MTB9LAogICAgIHsiaWQiOiJxNiIsInR5cGUiOiJudW1lcmljIiwibGFiZWwiOiJQL0UiLCJwcm9tcHQiOiJFcXVpdHkgdmFsdWUg4oKxMSwwMDBtOyBuZXQgaW5jb21lIOKCsTgwbS4gUC9FICh4KT8iLCJ1bml0IjoieCIsInBvaW50cyI6MTB9LAogICAgIHsiaWQiOiJxNyIsInR5cGUiOiJtY3EiLCJsYWJlbCI6IkNhcGl0YWwgc3RydWN0dXJlIiwicHJvbXB0IjoiRm9yIGNvbXBhbmllcyB3aXRoIGRpZmZlcmVudCBkZWJ0IGxldmVscywgYSBiZXR0ZXIgY29tcGFyaXNvbiBpc+KApiIsIm9wdGlvbnMiOlt7ImlkIjoiYSIsImxhYmVsIjoiRVYvRUJJVERBLCB3aGljaCBpcyBjYXBpdGFsLXN0cnVjdHVyZSBuZXV0cmFsIn0seyJpZCI6ImIiLCJsYWJlbCI6IlAvRSBvbmx5In0seyJpZCI6ImMiLCJsYWJlbCI6IlNoYXJlIHByaWNlIn0seyJpZCI6ImQiLCJsYWJlbCI6IkRpdmlkZW5kIHBlciBzaGFyZSJ9XSwicG9pbnRzIjoxMH0sCiAgICAgeyJpZCI6InE4IiwidHlwZSI6Im51bWVyaWMiLCJsYWJlbCI6IkltcGxpZWQgRVYiLCJwcm9tcHQiOiJFQklUREEg4oKxMzAwbSBhdCBhIDZ4IG11bHRpcGxlLiBJbXBsaWVkIEVWICjigrFtKT8iLCJ1bml0Ijoi4oKxbSIsInBvaW50cyI6MTB9LAogICAgIHsiaWQiOiJxOSIsInR5cGUiOiJudW1lcmljIiwibGFiZWwiOiJJbXBsaWVkIGVxdWl0eSIsInByb21wdCI6IldpdGggbmV0IGRlYnQgb2Yg4oKxNTAwbSwgdGhlIGltcGxpZWQgZXF1aXR5IHZhbHVlIGZyb20gdGhhdCBFViAo4oKxbSk/IiwidW5pdCI6IuKCsW0iLCJwb2ludHMiOjEwfSwKICAgICB7ImlkIjoicTEwIiwidHlwZSI6Im1jcSIsImxhYmVsIjoiVGhlIGJyaWRnZSIsInByb21wdCI6IldoaWNoIGl0ZW1zIGFyZSBhZGRlZCB0byBlcXVpdHkgdmFsdWUgdG8gcmVhY2ggZW50ZXJwcmlzZSB2YWx1ZT8iLCJvcHRpb25zIjpbeyJpZCI6ImEiLCJsYWJlbCI6IkRlYnQsIHByZWZlcnJlZCBzdG9jayBhbmQgbWlub3JpdHkgaW50ZXJlc3QifSx7ImlkIjoiYiIsImxhYmVsIjoiQ2FzaCBhbmQgaW52ZXN0bWVudHMifSx7ImlkIjoiYyIsImxhYmVsIjoiUmV2ZW51ZSBhbmQgcHJvZml0In0seyJpZCI6ImQiLCJsYWJlbCI6Ik9ubHkgZGl2aWRlbmRzIn1dLCJwb2ludHMiOjEwfV0=', 'base64'), 'UTF8')::jsonb,
 convert_from(decode('eyJxMSI6eyJhbnN3ZXIiOjEwMDAsInRvbGVyYW5jZV9wY3QiOjAuNX0sInEyIjp7ImFuc3dlciI6MTI1MCwidG9sZXJhbmNlX3BjdCI6MC41fSwicTMiOnsiYW5zd2VyIjoiYSJ9LCJxNCI6eyJhbnN3ZXIiOiJhIn0sInE1Ijp7ImFuc3dlciI6NSwidG9sZXJhbmNlX3BjdCI6MC41fSwicTYiOnsiYW5zd2VyIjoxMi41LCJ0b2xlcmFuY2VfcGN0IjowLjV9LCJxNyI6eyJhbnN3ZXIiOiJhIn0sInE4Ijp7ImFuc3dlciI6MTgwMCwidG9sZXJhbmNlX3BjdCI6MC41fSwicTkiOnsiYW5zd2VyIjoxMzAwLCJ0b2xlcmFuY2VfcGN0IjowLjV9LCJxMTAiOnsiYW5zd2VyIjoiYSJ9fQ==', 'base64'), 'UTF8')::jsonb)
), upd as (
  update public.lessons l set check_questions = qs.questions::jsonb
  from qs where l.slug = qs.slug and jsonb_array_length(l.check_questions) = 0
  returning l.id, qs.answers
)
insert into public.lesson_check_keys (lesson_id, answers)
select id, answers::jsonb from upd
on conflict (lesson_id) do nothing;
