-- seed_011_personal_interview: part 2 of 3. Run the parts in order.
-- ---------------------------------------------------------------------
-- 3. Practice activities
-- ---------------------------------------------------------------------
insert into public.lesson_activities (lesson_id, slug, position, kind, title, instructions, content)
select l.id, v.slug, v.pos, v.kind, v.title, v.instructions, v.content::jsonb
from (values
('budgeting-503020', 'need-or-want', 1, 'matching', 'Need or want?',
 'Sort each expense into the right bucket.',
 '{"categories":[{"id":"need","label":"Need"},{"id":"want","label":"Want"}],
     "items":[{"id":"i1","label":"Rent"},{"id":"i2","label":"Groceries"},{"id":"i3","label":"Streaming subscription"},{"id":"i4","label":"Dining out"},
              {"id":"i5","label":"Public transport to work"},{"id":"i6","label":"Concert tickets"},{"id":"i7","label":"Minimum loan payment"},{"id":"i8","label":"Electricity"}]}'),
('budgeting-503020', 'build-a-budget', 2, 'worked_example', 'Worked example: build a budget',
 'Split a salary and see what an overspend does. Hints are available but cost points.',
 '{"intro":"Take-home pay is ₱36,000 a month. Actual rent, food, transport and utilities add up to ₱21,000.",
     "steps":[{"id":"s1","prompt":"The 50% needs target (₱)?","unit":"₱"},{"id":"s2","prompt":"The 30% wants target (₱)?","unit":"₱"},{"id":"s3","prompt":"The 20% savings target (₱)?","unit":"₱"},
              {"id":"s4","prompt":"By how much do actual needs exceed the needs target (₱)?","unit":"₱"},
              {"id":"s5","prompt":"If that overspend comes out of savings, savings as a % of take-home (two decimals)?","unit":"%"}]}'),
('compound-interest-saving', 'simple-vs-compound', 1, 'matching', 'Simple or compound?',
 'Which kind of interest does each statement describe?',
 '{"categories":[{"id":"simple","label":"Simple interest"},{"id":"comp","label":"Compound interest"}],
     "items":[{"id":"i1","label":"Interest only on the original principal"},{"id":"i2","label":"Interest on principal plus past interest"},{"id":"i3","label":"Grows in a straight line"},
              {"id":"i4","label":"Grows faster each year"},{"id":"i5","label":"Typical of long-term investment growth"},{"id":"i6","label":"Used by some short-term loans"}]}'),
('compound-interest-saving', 'compounding-steps', 2, 'worked_example', 'Worked example: compounding year by year',
 'Compare simple and compound growth. Hints are available but cost points.',
 '{"intro":"You invest ₱100,000 at 5% a year for 3 years.",
     "steps":[{"id":"s1","prompt":"Total simple interest over 3 years (₱)?","unit":"₱"},{"id":"s2","prompt":"Value after 3 years with simple interest (₱)?","unit":"₱"},
              {"id":"s3","prompt":"Compound value after year 1 (₱)?","unit":"₱"},{"id":"s4","prompt":"Compound value after year 2 (₱)?","unit":"₱"},{"id":"s5","prompt":"Compound value after year 3 (₱, two decimals)?","unit":"₱"}]}'),
('investing-basics-funds', 'which-investment', 1, 'matching', 'Stock, bond or fund?',
 'Match each description to the investment it fits best.',
 '{"categories":[{"id":"stock","label":"Stock"},{"id":"bond","label":"Bond"},{"id":"fund","label":"Fund (mutual fund / ETF)"}],
     "items":[{"id":"i1","label":"An ownership share in a company"},{"id":"i2","label":"A loan to a government or company"},{"id":"i3","label":"Pools money from many investors"},{"id":"i4","label":"Pays a coupon and returns face value at maturity"},
              {"id":"i5","label":"May pay dividends"},{"id":"i6","label":"Gives instant diversification"},{"id":"i7","label":"Price can swing widely with company results"},{"id":"i8","label":"Run by a professional manager or tracks an index"}]}'),
('investing-basics-funds', 'peso-cost-averaging', 2, 'worked_example', 'Worked example: peso-cost averaging',
 'Invest ₱5,000 each month while the price moves. Hints are available but cost points.',
 '{"intro":"You invest ₱5,000 a month for 4 months in a fund. The unit price in each month is ₱50, ₱40, ₱25 and ₱50.",
     "steps":[{"id":"s1","prompt":"Units bought in month 1?","unit":"units"},{"id":"s2","prompt":"Units bought in month 2?","unit":"units"},{"id":"s3","prompt":"Units bought in month 3?","unit":"units"},
              {"id":"s4","prompt":"Total units after month 4?","unit":"units"},{"id":"s5","prompt":"Average cost per unit (₱, two decimals)?","unit":"₱"},{"id":"s6","prompt":"Value of the holding at the month-4 price of ₱50 (₱)?","unit":"₱"}]}'),
('emergency-fund-inflation', 'plan-flaws', 1, 'spot_error', 'Spot the flaws in this money plan',
 'Two parts of Ana''s plan are poor choices. Select them, then check.',
 '{"context":"Ana takes home ₱30,000 a month; essential expenses are ₱18,000.","columns":["Part of the plan","Choice"],"select_count":2,
     "rows":[{"id":"r1","cells":["Emergency fund target","3 to 6 months of essentials: ₱54,000 to ₱108,000"]},
             {"id":"r2","cells":["Where the emergency fund is kept","In a volatile stock fund"]},
             {"id":"r3","cells":["Debt","Pays only the minimum on a card charging 36% a year while investing in a 6% bond fund"]},
             {"id":"r4","cells":["Monthly saving","₱6,000 (20% of take-home)"]},
             {"id":"r5","cells":["Review","Revisits the plan once a year"]}]}'),
('emergency-fund-inflation', 'fund-target', 2, 'worked_example', 'Worked example: set an emergency fund target',
 'Work out the target and how long it takes. Hints are available but cost points.',
 '{"intro":"Essential expenses are ₱24,000 a month. You can save ₱4,000 a month. Inflation is 4% a year.",
     "steps":[{"id":"s1","prompt":"A 3-month emergency fund target (₱)?","unit":"₱"},{"id":"s2","prompt":"A 6-month emergency fund target (₱)?","unit":"₱"},
              {"id":"s3","prompt":"Months to reach the 3-month target?","unit":"months"},{"id":"s4","prompt":"Months to reach the 6-month target?","unit":"months"},
              {"id":"s5","prompt":"The 3-month target''s value in today''s pesos after one year of 4% inflation (₱, two decimals)?","unit":"₱"}]}'),
('interview-three-statements', 'where-first', 1, 'matching', 'Where does it first appear?',
 'Sort each line item into the statement where it first appears.',
 '{"categories":[{"id":"is","label":"Income statement"},{"id":"bs","label":"Balance sheet"},{"id":"cfs","label":"Cash flow statement"}],
     "items":[{"id":"i1","label":"Depreciation expense"},{"id":"i2","label":"Accounts receivable"},{"id":"i3","label":"Purchase of equipment"},{"id":"i4","label":"Retained earnings"},
              {"id":"i5","label":"Dividends paid"},{"id":"i6","label":"Interest expense"},{"id":"i7","label":"Inventory"},{"id":"i8","label":"Proceeds from a bond issue"}]}'),
('interview-three-statements', 'twenty-of-depreciation', 2, 'worked_example', 'Worked example: ₱20 of extra depreciation',
 'Walk through the interview classic. Tax rate is 25%. Use negative numbers for decreases.',
 '{"intro":"Depreciation rises by ₱20. Revenue, cash expenses, capex and financing are unchanged. The tax rate is 25%.",
     "steps":[{"id":"s1","prompt":"Change in EBIT (₱)?","unit":"₱"},{"id":"s2","prompt":"Change in taxes paid (₱, negative if taxes fall)?","unit":"₱"},
              {"id":"s3","prompt":"Change in net income (₱)?","unit":"₱"},{"id":"s4","prompt":"Change in cash from operations (₱)?","unit":"₱"},
              {"id":"s5","prompt":"Change in total assets on the balance sheet (cash up, PP&E down) (₱)?","unit":"₱"}]}'),
('interview-dcf-walkthrough', 'dcf-order', 1, 'matching', 'Put the DCF pieces in the right step',
 'Match each piece to the step of the DCF it belongs to.',
 '{"categories":[{"id":"cf","label":"Project cash flows"},{"id":"rate","label":"Discount rate"},{"id":"tv","label":"Terminal value"},{"id":"bridge","label":"Bridge to equity"}],
     "items":[{"id":"i1","label":"Revenue and margin assumptions"},{"id":"i2","label":"EBIT × (1 − t) + D&A − capex − change in NWC"},{"id":"i3","label":"CAPM and after-tax cost of debt"},{"id":"i4","label":"Weights of debt and equity"},
              {"id":"i5","label":"Gordon growth formula"},{"id":"i6","label":"Exit multiple"},{"id":"i7","label":"Subtract net debt"},{"id":"i8","label":"Divide by diluted shares"}]}'),
('interview-dcf-walkthrough', 'mini-dcf', 2, 'worked_example', 'Worked example: a two-year DCF',
 'Discount two years of cash flow and a terminal value, then bridge to a share price.',
 '{"intro":"Free cash flow: ₱100 in year 1 and ₱110 in year 2. The terminal value at the end of year 2 is ₱1,320. WACC is 10%. Net debt is ₱300 and there are 100 shares.",
     "steps":[{"id":"s1","prompt":"PV of year-1 cash flow (₱, two decimals)?","unit":"₱"},{"id":"s2","prompt":"PV of year-2 cash flow (₱, two decimals)?","unit":"₱"},
              {"id":"s3","prompt":"PV of the terminal value (₱, two decimals)?","unit":"₱"},{"id":"s4","prompt":"Enterprise value (₱, two decimals)?","unit":"₱"},
              {"id":"s5","prompt":"Equity value (₱, two decimals)?","unit":"₱"},{"id":"s6","prompt":"Value per share (₱, two decimals)?","unit":"₱"}]}'),
('interview-ev-equity', 'added-or-subtracted', 1, 'matching', 'Added or subtracted?',
 'Moving from equity value to enterprise value, is each item added or subtracted?',
 '{"categories":[{"id":"add","label":"Added"},{"id":"sub","label":"Subtracted"}],
     "items":[{"id":"i1","label":"Bank debt"},{"id":"i2","label":"Preferred stock"},{"id":"i3","label":"Minority interest"},{"id":"i4","label":"Cash and equivalents"},{"id":"i5","label":"Short-term investments"},{"id":"i6","label":"Bonds payable"}]}'),
('interview-ev-equity', 'equity-to-ev', 2, 'worked_example', 'Worked example: equity value to EV and multiples',
 'Build the bridge and compute the multiples. Hints are available but cost points.',
 '{"intro":"Share price ₱40; diluted shares 25 million. Debt ₱350m; preferred stock ₱50m; minority interest ₱20m; cash ₱120m. EBITDA ₱260m; net income ₱80m.",
     "steps":[{"id":"s1","prompt":"Equity value (₱m)?","unit":"₱m"},{"id":"s2","prompt":"Enterprise value (₱m)?","unit":"₱m"},{"id":"s3","prompt":"EV/EBITDA (x)?","unit":"x"},
              {"id":"s4","prompt":"P/E (x)?","unit":"x"},{"id":"s5","prompt":"Implied EV at 6x EBITDA (₱m)?","unit":"₱m"},{"id":"s6","prompt":"Implied share price at 6x EBITDA (₱, two decimals)?","unit":"₱"}]}')
) as v(lesson, slug, pos, kind, title, instructions, content)
join public.lessons l on l.slug = v.lesson
on conflict (lesson_id, slug) do update
  set position = excluded.position, kind = excluded.kind, title = excluded.title,
      instructions = excluded.instructions, content = excluded.content;

insert into public.lesson_activity_keys (activity_id, key)
select a.id, v.key::jsonb
from (values
('budgeting-503020', 'need-or-want', '{"i1":"need","i2":"need","i3":"want","i4":"want","i5":"need","i6":"want","i7":"need","i8":"need"}'),
('budgeting-503020', 'build-a-budget', '{
  "s1":{"answer":18000,"tolerance_pct":0.5,"hint":"50% of take-home.","explanation":"36,000 × 50% = 18,000."},
  "s2":{"answer":10800,"tolerance_pct":0.5,"hint":"30% of take-home.","explanation":"36,000 × 30% = 10,800."},
  "s3":{"answer":7200,"tolerance_pct":0.5,"hint":"20% of take-home.","explanation":"36,000 × 20% = 7,200."},
  "s4":{"answer":3000,"tolerance_pct":0.5,"hint":"Actual needs minus the target.","explanation":"21,000 − 18,000 = 3,000."},
  "s5":{"answer":11.67,"tolerance_pct":1,"hint":"Savings fall to 7,200 − 3,000, then divide by 36,000.","explanation":"4,200 ÷ 36,000 = 11.67%. Overspending on needs eats into savings."}}'),
('compound-interest-saving', 'simple-vs-compound', '{"i1":"simple","i2":"comp","i3":"simple","i4":"comp","i5":"comp","i6":"simple"}'),
('compound-interest-saving', 'compounding-steps', '{
  "s1":{"answer":15000,"tolerance_pct":0.5,"hint":"Principal × rate × years.","explanation":"100,000 × 5% × 3 = 15,000."},
  "s2":{"answer":115000,"tolerance_pct":0.5,"hint":"Principal plus interest.","explanation":"100,000 + 15,000 = 115,000."},
  "s3":{"answer":105000,"tolerance_pct":0.5,"hint":"100,000 × 1.05.","explanation":"100,000 × 1.05 = 105,000."},
  "s4":{"answer":110250,"tolerance_pct":0.5,"hint":"105,000 × 1.05.","explanation":"105,000 × 1.05 = 110,250."},
  "s5":{"answer":115762.5,"tolerance_pct":0.5,"hint":"110,250 × 1.05.","explanation":"110,250 × 1.05 = 115,762.50 — more than simple interest, because interest earns interest."}}'),
('investing-basics-funds', 'which-investment', '{"i1":"stock","i2":"bond","i3":"fund","i4":"bond","i5":"stock","i6":"fund","i7":"stock","i8":"fund"}'),
('investing-basics-funds', 'peso-cost-averaging', '{
  "s1":{"answer":100,"tolerance_pct":0.5,"hint":"5,000 ÷ 50.","explanation":"5,000 ÷ 50 = 100 units."},
  "s2":{"answer":125,"tolerance_pct":0.5,"hint":"5,000 ÷ 40.","explanation":"5,000 ÷ 40 = 125 units."},
  "s3":{"answer":200,"tolerance_pct":0.5,"hint":"5,000 ÷ 25.","explanation":"5,000 ÷ 25 = 200 units — more units when the price is low."},
  "s4":{"answer":525,"tolerance_pct":0.5,"hint":"Add all four months: the last buys 100 units at ₱50.","explanation":"100 + 125 + 200 + 100 = 525 units."},
  "s5":{"answer":38.1,"tolerance_pct":0.5,"hint":"Total invested ÷ total units.","explanation":"20,000 ÷ 525 = 38.10 — lower than the average of the four prices."},
  "s6":{"answer":26250,"tolerance_pct":0.5,"hint":"Units × ₱50.","explanation":"525 × 50 = 26,250."}}'),
('emergency-fund-inflation', 'plan-flaws', '{"errors":["r2","r3"],"explanations":{"r2":"An emergency fund must be safe and accessible. A volatile stock fund can be down exactly when you need the money.","r3":"Paying 36% on a card while earning about 6% loses money. Pay off high-interest debt before investing for modest returns."}}'),
('emergency-fund-inflation', 'fund-target', '{
  "s1":{"answer":72000,"tolerance_pct":0.5,"hint":"3 × 24,000.","explanation":"3 × 24,000 = 72,000."},
  "s2":{"answer":144000,"tolerance_pct":0.5,"hint":"6 × 24,000.","explanation":"6 × 24,000 = 144,000."},
  "s3":{"answer":18,"tolerance_pct":0.5,"hint":"72,000 ÷ 4,000.","explanation":"72,000 ÷ 4,000 = 18 months."},
  "s4":{"answer":36,"tolerance_pct":0.5,"hint":"144,000 ÷ 4,000.","explanation":"144,000 ÷ 4,000 = 36 months."},
  "s5":{"answer":69230.77,"tolerance_pct":0.5,"hint":"72,000 ÷ 1.04.","explanation":"72,000 ÷ 1.04 = 69,230.77: inflation shrinks what cash can buy."}}'),
('interview-three-statements', 'where-first', '{"i1":"is","i2":"bs","i3":"cfs","i4":"bs","i5":"cfs","i6":"is","i7":"bs","i8":"cfs"}'),
('interview-three-statements', 'twenty-of-depreciation', '{
  "s1":{"answer":-20,"tolerance_pct":0.5,"hint":"Depreciation is an operating expense.","explanation":"EBIT falls by 20."},
  "s2":{"answer":-5,"tolerance_pct":0.5,"hint":"25% of the 20 reduction in pre-tax profit.","explanation":"Taxes fall by 25% × 20 = 5."},
  "s3":{"answer":-15,"tolerance_pct":0.5,"hint":"EBIT change minus the tax saving.","explanation":"−20 + 5 = −15."},
  "s4":{"answer":5,"tolerance_pct":0.5,"hint":"Start with the net income change and add back the non-cash 20.","explanation":"−15 + 20 = +5 (the tax shield)."},
  "s5":{"answer":-15,"tolerance_pct":0.5,"hint":"Cash +5 and PP&E −20.","explanation":"+5 − 20 = −15, matching the −15 fall in retained earnings. It balances."}}'),
('interview-dcf-walkthrough', 'dcf-order', '{"i1":"cf","i2":"cf","i3":"rate","i4":"rate","i5":"tv","i6":"tv","i7":"bridge","i8":"bridge"}'),
('interview-dcf-walkthrough', 'mini-dcf', '{
  "s1":{"answer":90.91,"tolerance_pct":0.5,"hint":"100 ÷ 1.10.","explanation":"100 ÷ 1.1 = 90.91."},
  "s2":{"answer":90.91,"tolerance_pct":0.5,"hint":"110 ÷ 1.10².","explanation":"110 ÷ 1.21 = 90.91."},
  "s3":{"answer":1090.91,"tolerance_pct":0.5,"hint":"Discount the terminal value by two years.","explanation":"1,320 ÷ 1.21 = 1,090.91."},
  "s4":{"answer":1272.73,"tolerance_pct":0.5,"hint":"Add the three present values.","explanation":"90.91 + 90.91 + 1,090.91 = 1,272.73."},
  "s5":{"answer":972.73,"tolerance_pct":0.5,"hint":"Subtract net debt.","explanation":"1,272.73 − 300 = 972.73."},
  "s6":{"answer":9.73,"tolerance_pct":0.5,"hint":"Divide by 100 shares.","explanation":"972.73 ÷ 100 = 9.73. Note the terminal value is 86% of EV."}}'),
('interview-ev-equity', 'added-or-subtracted', '{"i1":"add","i2":"add","i3":"add","i4":"sub","i5":"sub","i6":"add"}'),
('interview-ev-equity', 'equity-to-ev', '{
  "s1":{"answer":1000,"tolerance_pct":0.5,"hint":"Price × diluted shares.","explanation":"40 × 25 = 1,000."},
  "s2":{"answer":1300,"tolerance_pct":0.5,"hint":"Add debt, preferred and minority interest; subtract cash.","explanation":"1,000 + 350 + 50 + 20 − 120 = 1,300."},
  "s3":{"answer":5,"tolerance_pct":0.5,"hint":"EV ÷ EBITDA.","explanation":"1,300 ÷ 260 = 5.0x."},
  "s4":{"answer":12.5,"tolerance_pct":0.5,"hint":"Equity value ÷ net income.","explanation":"1,000 ÷ 80 = 12.5x."},
  "s5":{"answer":1560,"tolerance_pct":0.5,"hint":"EBITDA × 6.","explanation":"260 × 6 = 1,560."},
  "s6":{"answer":50.4,"tolerance_pct":0.5,"hint":"Subtract the net claims (350 + 50 + 20 − 120 = 300), then divide by shares.","explanation":"(1,560 − 300) ÷ 25 = 50.40."}}')
) as v(lesson, slug, key)
join public.lessons l on l.slug = v.lesson
join public.lesson_activities a on a.lesson_id = l.id and a.slug = v.slug
on conflict (activity_id) do update set key = excluded.key, updated_at = now();

-- ---------------------------------------------------------------------
-- 4. Flashcards
-- ---------------------------------------------------------------------
insert into public.flashcards (lesson_id, position, front, back)
select l.id, v.pos, v.front, v.back
from (values
('budgeting-503020',1,'The 50/30/20 rule','50% needs, 30% wants, 20% savings and debt repayment.'),
('budgeting-503020',2,'Take-home pay','Pay after tax and mandatory contributions.'),
('budgeting-503020',3,'Examples of needs','Rent, groceries, utilities, transport to work, minimum debt payments.'),
('budgeting-503020',4,'Examples of wants','Dining out, streaming, hobbies, travel, shopping.'),
('budgeting-503020',5,'Pay yourself first','Move savings out when you are paid, before spending.'),
('budgeting-503020',6,'Needs above 50% of pay','Trim wants or raise income, and adjust the split rather than quit budgeting.'),
('budgeting-503020',7,'Why track spending?','To see where money really goes before setting limits.'),
('budgeting-503020',8,'What goes in the 20%?','Emergency fund, investments and extra debt payments.'),
('budgeting-503020',9,'Needs % of take-home =','Total needs ÷ take-home pay.'),
('budgeting-503020',10,'A budget is…','A decision about what your money should do before it disappears.'),
('compound-interest-saving',1,'Simple interest','Interest only on the original principal.'),
('compound-interest-saving',2,'Compound interest','Interest on principal plus previously earned interest.'),
('compound-interest-saving',3,'Compound value','Principal × (1 + rate)^years.'),
('compound-interest-saving',4,'Rule of 72','Years to double ≈ 72 ÷ rate (%).'),
('compound-interest-saving',5,'Why start early?','More time for compounding to work.'),
('compound-interest-saving',6,'Real return','≈ nominal return − inflation.'),
('compound-interest-saving',7,'Savings rate below inflation','Purchasing power falls.'),
('compound-interest-saving',8,'Two levers of saving','How much you save and how long it compounds.'),
('compound-interest-saving',9,'Simple vs compound growth shape','Simple is a straight line; compound accelerates.'),
('compound-interest-saving',10,'Total simple interest','Principal × rate × years.'),
('investing-basics-funds',1,'Stock','A share of ownership in a company.'),
('investing-basics-funds',2,'Bond','A loan that pays a coupon and returns face value at maturity.'),
('investing-basics-funds',3,'Mutual fund / ETF','A pooled basket of securities giving instant diversification.'),
('investing-basics-funds',4,'ETF vs mutual fund','ETFs trade on an exchange all day; mutual funds are priced once a day.'),
('investing-basics-funds',5,'Risk and return','Higher potential return comes with higher risk.'),
('investing-basics-funds',6,'Diversification','Spread money so no single investment can sink you.'),
('investing-basics-funds',7,'Expense ratio','The yearly fee a fund charges, as a % of assets.'),
('investing-basics-funds',8,'Time horizon rule','Money needed within about 2 years belongs in low-risk assets.'),
('investing-basics-funds',9,'Dividend yield','Annual dividend ÷ share price.'),
('investing-basics-funds',10,'Peso-cost averaging','Invest a fixed amount at regular intervals.'),
('emergency-fund-inflation',1,'Emergency fund','Cash set aside for job loss, medical bills or urgent repairs.'),
('emergency-fund-inflation',2,'How much to hold','Typically 3–6 months of essential expenses.'),
('emergency-fund-inflation',3,'Where to keep it','A safe, accessible account such as savings or a money-market fund.'),
('emergency-fund-inflation',4,'Inflation','Rising prices that erode the purchasing power of cash.'),
('emergency-fund-inflation',5,'Real return','≈ interest rate − inflation.'),
('emergency-fund-inflation',6,'Order of priorities','Starter emergency fund, then high-interest debt, then long-term investing.'),
('emergency-fund-inflation',7,'Who needs a bigger fund?','Freelancers and single-income households.'),
('emergency-fund-inflation',8,'Purchasing power after inflation','Amount ÷ (1 + inflation).'),
('emergency-fund-inflation',9,'Why not invest the emergency fund in stocks?','They can fall exactly when you need the money.'),
('emergency-fund-inflation',10,'Why revisit the target yearly?','As prices rise, a fixed peso amount covers less.'),
('interview-three-statements',1,'How are the three statements linked?','Net income feeds the cash flow statement and retained earnings; the cash flow statement ends in the change in cash on the balance sheet.'),
('interview-three-statements',2,'Depreciation +₱20, tax 25%: net income','Falls by ₱15.'),
('interview-three-statements',3,'Depreciation +₱20, tax 25%: operating cash flow','Rises by ₱5 (the tax shield).'),
('interview-three-statements',4,'Depreciation +₱20: balance sheet','Cash +5, PP&E −20, assets −15; retained earnings −15.'),
('interview-three-statements',5,'Increase in receivables','Lowers operating cash flow.'),
('interview-three-statements',6,'Buy equipment with cash','Total assets unchanged (cash down, PP&E up).'),
('interview-three-statements',7,'Borrow to buy inventory','Assets and liabilities both rise.'),
('interview-three-statements',8,'Retained earnings change','Net income minus dividends.'),
('interview-three-statements',9,'After-tax effect of an expense','Expense × (1 − tax rate).'),
('interview-three-statements',10,'What do interviewers want?','The why, not only the steps.'),
('interview-dcf-walkthrough',1,'60-second DCF answer','Project UFCF, add terminal value, discount at WACC to get EV, subtract net debt for equity value, divide by diluted shares.'),
('interview-dcf-walkthrough',2,'UFCF','EBIT × (1 − t) + D&A − capex − increase in NWC.'),
('interview-dcf-walkthrough',3,'Gordon growth terminal value','FCF × (1 + g) ÷ (WACC − g).'),
('interview-dcf-walkthrough',4,'Other terminal value method','Exit multiple (e.g. EBITDA × EV/EBITDA).'),
('interview-dcf-walkthrough',5,'Discount rate for UFCF','WACC.'),
('interview-dcf-walkthrough',6,'Equity bridge','Equity value = EV − net debt (and preferred, minorities).'),
('interview-dcf-walkthrough',7,'Why is TV so important?','Often 60–80% of EV; most value is beyond the forecast.'),
('interview-dcf-walkthrough',8,'Classic DCF mistake','Using levered cash flows with WACC.'),
('interview-dcf-walkthrough',9,'WACC up means…','DCF value down.'),
('interview-dcf-walkthrough',10,'Standard sensitivity table','WACC against terminal growth (or exit multiple).'),
('interview-ev-equity',1,'Equity value','Share price × diluted shares.'),
('interview-ev-equity',2,'Enterprise value','Equity value + debt + preferred + minority interest − cash.'),
('interview-ev-equity',3,'Why subtract cash?','It is not part of the operating business and offsets the price a buyer pays.'),
('interview-ev-equity',4,'Multiples paired with EV','EV/EBITDA, EV/Revenue.'),
('interview-ev-equity',5,'Multiples paired with equity value','P/E (equity value ÷ net income).'),
('interview-ev-equity',6,'Best multiple across different debt levels','EV/EBITDA (capital-structure neutral).'),
('interview-ev-equity',7,'From EV/EBITDA to a share price','EBITDA × multiple → subtract net debt → ÷ diluted shares.'),
('interview-ev-equity',8,'Items added in the equity-to-EV bridge','Debt, preferred stock, minority interest.'),
('interview-ev-equity',9,'Items subtracted in the bridge','Cash and equivalents (and non-operating investments).'),
('interview-ev-equity',10,'Why use diluted shares?','Options and convertibles can increase the share count.')
) as v(lesson, pos, front, back)
join public.lessons l on l.slug = v.lesson
on conflict (lesson_id, position) do update set front = excluded.front, back = excluded.back;
